### ISSUE TITLE
FR: re-index-footnotes Should not Overwrite Duplicate References

### ISSUE THREAD

**Issue by LloydThinks** [platers/obsidian-linter#625] opened 2023-02-07 13:28 UTC
## Describe the Bug

`re-index-footnotes` doesn't seem to allow multiple references to the same footnote. Using footnotes for references will often lead to situations where the same footnote is used again and again, so the text has multiple of the same footnote reference. The Re-Index Footnotes rule simply changes the duplicate numbers into false, non-existent footnote references.

## How to Reproduce

1. Create a file with the following text:
```markdown
First,[^1] followed by the Second,[^2] and then the First[^1] again.

[^1]: First Reference
[^2]: Second reference
```
2. Run Linter with rule `re-index-footnotes` enabled.
3. The text above is changed to the following:
```markdown
First,[^1] followed by the Second,[^2] and then the First[^3] again.

[^1]: First Reference
[^2]: Second reference
```

## Expected Behavior

Leave the second `[^1]` reference alone, as it is a valid reference to the first footnote.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-04-08 03:01
I need to double check the logic here, but I believe reorder is working as intended here. I do need to recheck that it is working as intended though.

**Comment by pjkaufman** [comment] 2023-04-08 03:08
This is working as documented: https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#re-index-footnotes

Re-index has no understanding of multiple references to the same footnote as it was written to have the same amount of footnotes as the amount of footnote references. There is a feature request to make this more sensible by having the logic work by not assuming all footnote references are to be their own footnote: https://github.com/platers/obsidian-linter/issues/466#issuecomment-1297151277.

I am not sure if I want to close this as it overlaps with the feature request or if leaving this open would be the right call here.

**Comment by pjkaufman** [comment] 2023-04-08 14:58
I believe I have a simple version of the fix for this working. I am going to add a more comprehensive test and then see if the results are as expected. If so, I will refactor the logic and then move forward with the change. It should kill 3 birds with one stone.

**Comment by pjkaufman** [comment] 2023-04-08 15:06
It looks like the more complex scenario failed, so I need to rework it, but it will hopefully not be too bad to get working and  out there.

**Comment by pjkaufman** [comment] 2023-04-08 18:43
I am changing the label from a bug to an enhancement. The PR to change this has been created and should be merged in a couple of minutes barring a CI issue.

**Comment by pjkaufman** [comment] 2023-04-08 18:45
This should now be on master and will go out with the next release. Please let us know if this is not fixed or if there is some other issue with footnotes.

**Closed** 2023-04-08 18:45 UTC
Labels: enhancement, footnote
