### ISSUE TITLE
Bug: Tags are not moved into the YAML frontmatter if they have emoji in it

### ISSUE THREAD

**Issue by chablo** [platers/obsidian-linter#1138] opened 2024-08-16 08:43 UTC
- [X] I have verified that I am on the latest version of the Linter

## Describe the Bug

Tags are not moved into the YAML frontmatter if they have emoji in it

## How to Reproduce

1. Enable the rule "Move all tags to YAML frontmatter of the document"
2. Add a tag with an emoji
3. Lint the file
4. The tag hasn't moved

To clarify :
- if the emoji is at the beginning of the tag, nothing is moved in the YAML frontmatter.
- If the emoji is in the middle, everything before the emoji is moved, and everything after is ignored.
- If the emoji is at the end, everything except the emoji is moved.

## Expected Behavior

The whole tag with the emoji is moved in the YAML frontmatter.

## Device

- [X] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2024-08-18 00:32
Thanks for reporting this @chablo . This is caused by the tag regex. It needs to be updated to allow for emojis as well.

**Comment by pjkaufman** [comment] 2024-08-19 12:00
I believe I have a fix for this. I am going to push up a PR and see about getting it merged into master.

**Closed** 2024-08-19 12:06 UTC
Labels: bug, reproducible
