### ISSUE TITLE
How do the prevent double checklist item and litem indicators work? I don't think its working.

### ISSUE THREAD

**Issue by YousufSSyed** [platers/obsidian-linter#693] opened 2023-04-21 06:01 UTC
I have both enabled. If I have a blank bullet point like this: `- ` and paste in this: `- list item`, I get `- - list item`. Same thing if I do `- [ ] ` and `- [ ] task list item`: `- [ ] - [ ] task list item`.

**Comment by pjkaufman** [comment] 2023-04-21 09:34
If you are running the regular rules that are not for pasting, if you could provode the actual example of a simple version of the file that you are having trouble linting.

Based on the info provided, I canmot tell if you are running the linting rules or not.

**Comment by YousufSSyed** [comment] 2023-04-21 13:49
> If you don't want a double list item indicator, https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#prevent-double-list-item-indicator-on-paste should do the trick.

What I said is "I have both enabled." As in I have both "Prevent Double Checklist Indicator on Paste" and "Prevent Double List Item Indicator on Paste" turned on in the plugin settings.

Here's an example with four lines:
```
- [ ] task 
- [ ]
- task 
-
```
If I cut the 1st and 3rd lines and paste them into the 2nd and 4th lines, respectively and do nothing else, I want it to look like this:
```
- [ ] task 
- task 
```

**Comment by pjkaufman** [comment] 2023-04-21 15:12
@YousufSSyed , could you provide your `data.json`. I am not seeing what you are where the list or task item duplication is not working. I will need the `data.json` to see if the issue is caused by another plugin handling the paste event or if it is the Linter itself.

**Comment by YousufSSyed** [comment] 2023-04-21 19:46
[data.json.zip](https://github.com/platers/obsidian-linter/files/11298807/data.json.zip)

**Comment by YousufSSyed** [comment] 2023-04-21 20:11
@pjkaufman I did what I could. Look at my edits if you haven't.

**Comment by pjkaufman** [comment] 2023-04-21 20:19
@YousufSSyed , if the issue is gone after disabling and re-enabling, I think we can close the issue. I think we should keep the issue open until Wednesday the 26th. If you don't experience the issue again by then, it should be safe to close this ticket. Otherwise you can comment here again, and we can try to fix whatever is going on.

**Comment by YousufSSyed** [comment] 2023-04-21 20:20
Alright, I'll set a reminder for Wednesday and then I'll test it again. if I don't experience the issue again, then I'll reply and close it.

**Comment by pjkaufman** [comment] 2023-04-21 20:21
Thanks!

**Comment by pjkaufman** [comment] 2023-05-01 12:55
I don't see any statement that this has happened again, so I am closing this.

**Closed by pjkaufman** 2023-05-01 12:55 UTC

**Comment by YousufSSyed** [comment] 2023-05-01 16:18
Oh I had made a reminder to test it again but didn't write down to reply back here, lol.

**Comment by pjkaufman** [comment] 2023-05-01 16:24
No worries.
