### ISSUE TITLE
Bug: `<!-- linter-disable -->` can only be used once for V1.15.0

### ISSUE THREAD

**Issue by wenbopeng** [platers/obsidian-linter#733] opened 2023-05-25 02:30 UTC
##`<!-- linter-disable -->` can only be used once for V1.15.0

If `<!-- linter-disable -->` is used more than twice, the result will be confused

Example to reproduce issue with

``` markdown
content

<!-- linter-disable -->

$$
abc
$$
{#eq:a}

<!-- linter-enable -->

content

<!-- linter-disable -->

$$
abc
$$
{#eq:b}

<!-- linter-enable -->

content
```

## Expected Behavior

Expected output if applicable:

``` markdown
Same as Example
```

## Screenshots

![image.png](https://obsidian-weber.oss-cn-hangzhou.aliyuncs.com/picgo/202305251030214.png)

## Device

- [ x] Desktop V1.15.0
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-05-25 09:07
@wenbopeng , thanks for reporting this.

Please provide your `data.json`. This looks to be an issue with custom ignore and some rule interacting with each other.

**Comment by pjkaufman** [comment] 2023-05-25 09:19
I will have to take a closer look at this. I tried this out and can reproduce.

The issue is likely related to using the `{#eq:a}`  and `{#eq:b}` values as they look similar to some of the underlying ignore logic. I will need to double check which rule is causing the issue on my device, but it could be the same one you are encountering.

**Comment by pjkaufman** [comment] 2023-05-25 12:57
The issue is with 1 or more custom ignore ranges being present. They were being identified correctly, but were being replaced in the wrong order which caused the issue. I plan to patch this this morning.

**Comment by pjkaufman** [comment] 2023-05-25 13:05
This should be fixed on master now and it should be in the patch that should go out shortly. Please let us know if the issue persists after the next release/the patch.

**Closed** 2023-05-25 13:05 UTC
Labels: bug, reproducible
