### ISSUE TITLE
FR: Get modified date property behave like created date property

### ISSUE THREAD

**Issue by edofe99** [platers/obsidian-linter#890] opened 2023-09-14 07:53 UTC
The created date property has the option "Force Date Created Key Value Retention" which is useful to retain created date when moving the vault around. Unfortunately the "Date modified" property does not have that option and thus the only practical way to keep it from updating when moving the vault around is to use another plugin "Update frontmatter modified date" by Alan Grainger. 

Hope the problem is clear, [here](https://forum.obsidian.md/t/how-to-add-an-automatically-updated-last-edit-time-in-document-properties/67224/4?u=ironhak) is a slightly better explaination if needed.

**Comment by ironhak** [comment] 2023-09-14 09:16
Hello, honestly I don’t know. The other plug-in I mentioned seems to work properly tough, maybe you can look into it.

I‘m sorry if I can’t be more useful, unfortunately I’m just the end-user and I don’t know nothing about coding.

I perfectly understood what you mean, I wouldn’t know how to answer it, but as said apparently that plug-in solve the problem.

**Comment by pjkaufman** [comment] 2023-09-14 11:01
So this is a slight variation on #392 . Once that gets added (assuming I have time to do it), then the only thing to do would be to add a boolean or list to determine what the user considers the date modified to be: the filesystem time or the last user/Linter edit in Obsidian.

**Comment by redactedscribe** [comment] 2023-09-18 00:13
Ignoring the file system's metadata for the modified date would be the simplest solution I think; only update the modified date when Obsidian saves the file. The `date modified` property could be older than what the file system reports, but does it really matter? It matters if you care about edits to files done externally to Obsidian, or if you want the modified date to update when moving to a new drive or something, but I'd say both cases shouldn't be what this feature aims to track. I'd be happy with `date created` and `date modified` sticking to events caused by Obsidian itself (then there'd be no need for the former's retention feature).

**Comment by pjkaufman** [comment] 2023-09-18 00:27
@redactedscribe , the rules in the Linter are device agnostic. So they were never designed to be run on multiple devices that sync to each other. That would be why the retain key was added. The same would need to be added for date modified. However, the Linter does not run on all vault modifications right now so it is not feasible to add that logic for forcing retention of the date modified until #392  is added.

**Comment by ironhak** [comment] 2023-09-18 08:04
What I don't get is why for creation data there's the option to switch from only internal or external, while for modified date you don't have that option.

**Comment by pjkaufman** [comment] 2023-09-18 09:03
> What I don't get is why for creation data there's the option to switch from only internal or external, while for modified date you don't have that option.

The reason for that is because in order to do that #392 would need to be complete. This is because the Linter would only know when it makes a change as it stands.

**Comment by pjkaufman** [comment] 2023-12-14 17:50
I want to update this and mention that this actually relates to #183 .

**Comment by redactedscribe** [comment] 2023-12-14 21:54
Just an FYI, there's a useful plugin to update the modified date, although not perfect, which doesn't rely on the OS metadata: [Update frontmatter modified date](https://obsidian.md/plugins?search=update%20modified). Been using it some months and works well.

**Comment by pjkaufman** [comment] 2023-12-14 22:04
It is not 100% feasible to do the same right now. It may be that modified date and time gets converted into a special case where it can run by itself to update the date modified and date created times. But I would likely need to think through what that would look like as a whole.

**Closed** 2024-09-28 21:15 UTC
Labels: rule suggestion

**Comment by pjkaufman** [comment] 2024-09-28 21:20
I just added the ability to only update the date modified when either the Linter updates a file or the user modifies a file. It may encompass any other editor updates as well, but I am not certain on that. Feel free to test this out in the next release or on master. I plan to release a BRAT update soon.
