### ISSUE TITLE
Bug: There is a bug regarding the auto-update of the modification time when saving a note. 

### ISSUE THREAD

**Issue by zhaihao** [platers/obsidian-linter#903] opened 2023-09-26 09:19 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

There is a bug related to the auto-update of the modification time when saving a note. The issue is caused by an incorrect date format during the note-saving process. Notably, this issue occurs exclusively in preview mode; it functions correctly in source mode.

## How to Reproduce

Refer to the video below.

## Expected Behavior

Expected output if applicable:

``` markdown
ctime: 2023-04-23T14:26:15
mtime: 2023-09-26T10:59:47
enable: false
```

## Screenshots

https://github.com/platers/obsidian-linter/assets/4202032/2ed3f4ba-cbed-4b38-b0e6-415d61cafc7d

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

I've made modifications to the style of property

**Comment by zhaihao** [comment] 2023-09-26 09:36
I tried to dig into the code to understand the reason behind it:

```ts
 else if (type == DiffMatchPatch.DIFF_DELETE) {
        const start = endOfDocument(curText);
        let tempText = curText;
        tempText += value;
        const end = endOfDocument(tempText);
        editor.replaceRange('', start, end);
}
```
It seems that the last line of code doesn't work correctly in preview mode.

**Comment by pjkaufman** [comment] 2023-09-26 10:35
> I tried to dig into the code to understand the reason behind it:
> 
> ```ts
>  else if (type == DiffMatchPatch.DIFF_DELETE) {
>         const start = endOfDocument(curText);
>         let tempText = curText;
>         tempText += value;
>         const end = endOfDocument(tempText);
>         editor.replaceRange('', start, end);
> }
> ```
> 
> It seems that the last line of code doesn't work correctly in preview mode.

Last time this happened, it was an issue on Obsidian's side that caused the problem since the editor should work practically the same in both modes (see #882 ). I am not really able to do much if for some reason it is failing to do something like it would in source mode. I can take a look in a couple of weeks when I get a chance to dive further into these issues that have piled up.

**Comment by pjkaufman** [comment] 2023-09-26 10:43
Looking at the video, I do have a couple of questions that hopefully will help me better understand the issue:
- What is updating the time value when you modify the properties view? That looks like some other plugin is making a modification to the value.
- What is the Linter not doing right based on the video? Based on the video, everything looks correct to me (i.e. something set the value of the property to be in a different format from the current one, so a modificaton is needed).

_Note: the expected and actual output match according to the issue mentioned above:_
> Expected output if applicable:
> ---
> ctime: 2023-04-23T14:26:15
> mtime: 2023-09-26T10:59:47
> enable: false
> ---

**Comment by zhaihao** [comment] 2023-09-27 13:16
@pjkaufman Thank you for your prompt response.

1. Regarding the question "What is updating the time value when you modify the properties view? That looks like some other plugin is making a modification to the value."

   Here is a breakdown of my configuration: The "linter" plugin is designed to update the "mtime" field when I modify the properties view and save the note using a hotkey. Below is the relevant configuration snippet:

   ```json
   "yaml-timestamp": {
     "enabled": true,
     "date-created": true,
     "date-created-key": "ctime",
     "force-retention-of-create-value": true,
     "date-modified": true,
     "date-modified-key": "mtime",
     "format": "YYYY-MM-DDTHH:mm:ss"
   }
   ```

2. In response to your query, "What is the Linter not doing right based on the video? Based on the video, everything looks correct to me (i.e. something set the value of the property to be in a different format from the current one, so a modification is needed)."

   Allow me to provide a detailed explanation of the video:

   1. Initially, the text appears as: `mtime: 2023-09-26T17:12:23`.
   2. When I modify the properties view and save the note, the "linter" updates the "mtime" value.
   3. The system time at this point is `2023-09-26T17:12:41`. Consequently, the seconds part is set to `41`. However, the old seconds text, which was `23`, cannot be replaced with a space character when `type == DiffMatchPatch.DIFF_DELETE`. As a result, the new seconds text, `41`, is inserted. This leads to the observed result: `mtime: 2023-09-26T17:12:4123`, as depicted in the video.

I hope this additional information clarifies the issue further. Your assistance in resolving this matter is greatly appreciated.

**Comment by pjkaufman** [comment] 2023-10-22 00:17
I am taking a look to see if this is reproducible on my end. If it works in source mode, it should work in live preview mode. But some of the recent changes seem to have made live preview mode act a little differently than source mode with regards to how modifications are made. I am hoping this was just an Obsidian bug that got ironed out in the last few weeks, but I am not sure this will be that simple.

**Comment by pjkaufman** [comment] 2023-10-22 00:23
@zhaihao , could you try this again on the latest version of Obsidian (v.1.4.16 or higher)?

I just tried this and was not able to reproduce. If you are still able to reproduce this issue, could you provide your entire `data.json`? Thanks!

**Comment by christyray** [comment] 2023-10-22 23:14
Hello!

I am having what I think is the same issue. I am currently on v.1.4.16 of Obsidian (installer v.1.4.16 as well), and I disabled all plugins except Linter. I have "Lint on Save" enabled, and that is what I was using for these tests. 

Also, this is _definitely_ overkill on the "testing the issue" front, but I was so bewildered trying to find what pattern led to the issue that I wanted to include everything!

## Testing

### Testing TL;DR

The Linter log showed the correct `date-modified` after performing the `yaml-timestamp` step, even in cases where the file itself was not updated correctly. 

`date-modified` in the file updated correctly when either:

1. Any edits were made in the main text of the file after the blank line after the YAML block
2. "Substantial enough" edits were made in the blank line after the YAML block

Changes to just the metadata of the file without editing the text of the file caused issues with `date-modified`. 

### Tests and Results

From testing, I believe the issue is related to when the YAML metadata of the file or the blank line underneath the YAML block has changed since the last file update. 

To replicate:

1. Created an empty note named "Testing" and added an H1 and a single line of text
2. Saved the file so Linter would populate the initial metadata fields
3. Restarted Obsidian
4. Edited the file in Preview View as noted in the table below
5. Saved the file in Preview View and noted the result
6. Used "Undo" until the file was back in it's original state
7. Repeat steps 4-6

❌ = `date-modified` field did not update as expected (see example below)
✅ = `date-modified` field did update as expected
❌ / ✅ = inconsistent results

| Test | Result |
| ----- | ----- |
| Adding 1 letter to the blank line after the YAML block | ❌ |
| Adding 2 letters to the blank line after the YAML block | ❌ / ✅  |
| Adding 3 letters to the blank line after the YAML block | ✅ |
| Adding a newline after the blank line after the YAML block | ❌ |
| Adding a newline and a space after the blank line after the YAML block | ✅ |
| Adding and deleting 1 letter to the blank line after the YAML block | ❌ |
| Adding and deleting characters with net +1 or +2 characters to the blank line after the YAML block | ❌ |
| Adding and deleting characters with net +3 characters to the blank line after the YAML block | ✅ |
| Adding 1 letter to the blank line at the end of the file | ✅ |
| Adding 1 letter to the sentence "This is a test." | ✅ |
| Adding 1 letter to the H1 heading | ✅ |
| Deleting 1 letter from "This is a test." | ✅ |
| Adding and deleting 1 letter from "This is a test." | ✅ | 
| Editing the `title` field in the Properties block | ❌ |
| Editing the `title` field and adding 1 or 2 letters to the blank line after the YAML block | ❌ |
| Editing the `title` field and adding 3 letters to the blank line after the YAML block | ✅ |
| Adding the `tags` field with the value "troubleshooting" to the Properties block | ❌ |
| Removing the `title` field from the Properties block | ❌<sup>1</sup> |
| Adding the `tags` field and adding 1 or 2 letters to the blank line after the YAML block | ❌<sup>2</sup> |
| Adding the `tags` field and adding 3 letters to the blank line after the YAML block | ✅ |
| Adding the `tags` field and editing "This is a test." or the blank line at the end of the file | ✅ |
 
<sup>1</sup>This caused Linter to split the time across two lines and led to an error in the YAML block - see output below.
<sup>2</sup>Separate from the `date-modified` field, this changes split the `---` at the end of the YAML block into two lines: `--\n-`

### Linter Debug Logs

The Linter log showed the correct `date-modified` after performing the `yaml-timestamp` step, even in cases where the file itself was not updated correctly. This makes me think that the issue is not with Linter itself, but possibly with how the Properties view is handling the changes? 

### Examples

<details>
<summary><strong>Original File</strong></summary>

```
---
date-created: 2023-10-22 17:49:43-04:00
date-modified: 2023-10-22 17:49:47-04:00
title: "Testing"
---

# Testing

This is a test.

```
</details>

<details>
<summary><strong>YAML after Linting in Source Mode (✅ Output)</strong></summary>

```
---
date-created: 2023-10-22 17:49:43-04:00
date-modified: 2023-10-22 17:55:35-04:00
title: "Testing"
---

# Testing

This is a test.

```
</details>

<details>
<summary><strong>YAML after Linting in Preview Mode (❌ Output)</summary></strong>

```
---
date-created: 2023-10-22 17:49:43-04:00
date-modified: 2023-10-22 17:564009:47-04:00
title: "Testing"
---

# Testing

This is a test.

```
</details>

<details>
<summary><strong>YAML after Removing Title Field (Example for <sup>1</sup>)</strong></summary>

```
---
date-created: 2023-10-22 17:49:43-04:00
date-modified: 2023-10-22 18:041:123-04:
title: "Testing"00
---

# Testing

This is a test.

```
</details>

## Config

<details>
<summary><strong>Linter</strong></summary>

```
{
  "ruleConfigs": {
    "Remove Space around Fullwidth Characters": {
      "Ensures that fullwidth characters are not followed by whitespace (either single spaces or a tab). Note that this may causes issues with markdown format in some cases.": false
    },
    "escape-yaml-special-characters": {
      "enabled": true,
      "try-to-escape-single-line-arrays": false
    },
    "force-yaml-escape": {
      "enabled": true,
      "force-yaml-escape-keys": "aliases\ntitle"
    },
    "format-tags-in-yaml": {
      "enabled": true
    },
    "format-yaml-array": {
      "enabled": true,
      "alias-key": true,
      "tag-key": true,
      "default-array-style": "multi-line",
      "default-array-keys": true,
      "force-single-line-array-style": "",
      "force-multi-line-array-style": ""
    },
    "insert-yaml-attributes": {
      "enabled": false,
      "text-to-insert": "folder:"
    },
    "move-tags-to-yaml": {
      "enabled": true,
      "how-to-handle-existing-tags": "Nothing",
      "tags-to-ignore": ""
    },
    "remove-yaml-keys": {
      "enabled": false,
      "yaml-keys-to-remove": ""
    },
    "yaml-key-sort": {
      "enabled": true,
      "yaml-key-priority-sort-order": "date-created\ndate-modified\nfolder\ntitle\naliases\ntags\nfileClass\ncssclass\nproject\ncitekey\nyear\nauthor\npublicationType\nurl\nevent-date\nevent-type\nspeaker\npi\ntopics\nconference\nstatus\nstarted\ncompleted\naim\nmodel\ntask\nheaderLevel\ncrossrefYaml\nflag-note",
      "priority-keys-at-start-of-yaml": true,
      "yaml-sort-order-for-other-keys": "None"
    },
    "yaml-timestamp": {
      "enabled": true,
      "date-created": true,
      "date-created-key": "date-created",
      "force-retention-of-create-value": true,
      "date-modified": true,
      "date-modified-key": "date-modified",
      "format": "YYYY-MM-DD HH:mm:ssZ"
    },
    "yaml-title": {
      "enabled": true,
      "title-key": "title",
      "mode": "first-h1-or-filename-if-h1-missing"
    },
    "yaml-title-alias": {
      "enabled": true,
      "preserve-existing-alias-section-style": true,
      "keep-alias-that-matches-the-filename": false,
      "use-yaml-key-to-keep-track-of-old-filename-or-heading": true
    },
    "capitalize-headings": {
      "enabled": true,
      "style": "Title Case",
      "ignore-case-words": true,
      "ignore-words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript",
      "lowercase-words": "via, a, an, the, and, or, but, for, nor, so, yet, at, by, in, of, on, to, up, as, is, if, it, for, to, with, without, into, onto, per"
    },
    "file-name-heading": {
      "enabled": true
    },
    "header-increment": {
      "enabled": true,
      "start-at-h2": false
    },
    "headings-start-line": {
      "enabled": true
    },
    "remove-trailing-punctuation-in-heading": {
      "enabled": false,
      "punctuation-to-remove": ".,;:!。，；：！"
    },
    "footnote-after-punctuation": {
      "enabled": true
    },
    "move-footnotes-to-the-bottom": {
      "enabled": true
    },
    "re-index-footnotes": {
      "enabled": false
    },
    "auto-correct-common-misspellings": {
      "enabled": true,
      "ignore-words": ""
    },
    "convert-bullet-list-markers": {
      "enabled": true
    },
    "emphasis-style": {
      "enabled": true,
      "style": "asterisk"
    },
    "no-bare-urls": {
      "enabled": true
    },
    "ordered-list-style": {
      "enabled": true,
      "number-style": "ascending",
      "list-end-style": "."
    },
    "proper-ellipsis": {
      "enabled": true
    },
    "remove-consecutive-list-markers": {
      "enabled": true
    },
    "remove-empty-list-markers": {
      "enabled": true
    },
    "remove-hyphenated-line-breaks": {
      "enabled": true
    },
    "remove-multiple-spaces": {
      "enabled": true
    },
    "strong-style": {
      "enabled": true,
      "style": "asterisk"
    },
    "two-spaces-between-lines-with-content": {
      "enabled": false
    },
    "unordered-list-style": {
      "enabled": true,
      "list-style": "-"
    },
    "compact-yaml": {
      "enabled": true,
      "inner-new-lines": true
    },
    "consecutive-blank-lines": {
      "enabled": true
    },
    "convert-spaces-to-tabs": {
      "enabled": true,
      "tabsize": "4"
    },
    "empty-line-around-blockquotes": {
      "enabled": true
    },
    "empty-line-around-code-fences": {
      "enabled": true
    },
    "empty-line-around-math-blocks": {
      "enabled": true
    },
    "empty-line-around-tables": {
      "enabled": true
    },
    "heading-blank-lines": {
      "enabled": true,
      "bottom": false,
      "empty-line-after-yaml": true
    },
    "line-break-at-document-end": {
      "enabled": true
    },
    "move-math-block-indicators-to-their-own-line": {
      "enabled": true
    },
    "paragraph-blank-lines": {
      "enabled": false
    },
    "remove-empty-lines-between-list-markers-and-checklists": {
      "enabled": true
    },
    "remove-link-spacing": {
      "enabled": true
    },
    "remove-space-around-characters": {
      "enabled": false,
      "include-fullwidth-forms": true,
      "include-cjk-symbols-and-punctuation": true,
      "include-dashes": true,
      "other-symbols": ""
    },
    "space-after-list-markers": {
      "enabled": true
    },
    "space-between-chinese-japanese-or-korean-and-english-or-numbers": {
      "enabled": false
    },
    "trailing-spaces": {
      "enabled": true,
      "twp-space-line-break": false
    },
    "add-blockquote-indentation-on-paste": {
      "enabled": true
    },
    "prevent-double-checklist-indicator-on-paste": {
      "enabled": true
    },
    "prevent-double-list-item-indicator-on-paste": {
      "enabled": true
    },
    "proper-ellipsis-on-paste": {
      "enabled": true
    },
    "remove-hyphens-on-paste": {
      "enabled": false
    },
    "remove-leading-or-trailing-whitespace-on-paste": {
      "enabled": false
    },
    "remove-leftover-footnotes-from-quote-on-paste": {
      "enabled": false
    },
    "remove-multiple-blank-lines-on-paste": {
      "enabled": true
    },
    "blockquote-style": {
      "enabled": false,
      "style": "space"
    },
    "quote-style": {
      "enabled": false,
      "single-quote-enabled": true,
      "single-quote-style": "''",
      "double-quote-enabled": true,
      "double-quote-style": "\"\""
    },
    "remove-space-before-or-after-characters": {
      "enabled": false,
      "characters-to-remove-space-before": ",!?;:).’”]",
      "characters-to-remove-space-after": "¿¡‘“(["
    }
  },
  "lintOnSave": true,
  "recordLintOnSaveLogs": true,
  "displayChanged": true,
  "lintOnFileChange": false,
  "displayLintOnFileChangeNotice": false,
  "settingsConvertedToConfigKeyValues": true,
  "foldersToIgnore": [
    "00 Meta/05 Templates",
    "30 Working/34 Writing/Projects"
  ],
  "linterLocale": "system-default",
  "logLevel": "DEBUG",
  "lintCommands": [],
  "customRegexes": [],
  "commonStyles": {
    "aliasArrayStyle": "single string to multi-line",
    "tagArrayStyle": "single string to multi-line",
    "minimumNumberOfDollarSignsToBeAMathBlock": 2,
    "escapeCharacter": "\""
  }
}
```
</details>

<details>
<summary><strong>Obsidian</strong></summary>
```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 22.6.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 77
	Plugins enabled: 1
		1: Linter v1.20.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```
</details>

**Comment by pjkaufman** [comment] 2023-12-08 21:23
I believe I have a fix for this that has just been merged in. The changes should be in the next release and on master. Please let us know if either master or the next release has issues.

**Closed by pjkaufman** 2023-12-08 21:23 UTC
Labels: bug, resolution/update-made, live-preview

**Comment by zhaihao** [comment] 2023-12-14 06:00
@pjkaufman I upgraded the plugin to version 1.22.0 today, and the issue has been fixed. Thank you for your efforts

**Comment by pjkaufman** [comment] 2023-12-14 10:13
That's great!
