### ISSUE TITLE
Bug: Malformed Table Hangs Linter

### ISSUE THREAD

**Issue by grantx2016** [platers/obsidian-linter#652] opened 2023-03-16 12:04 UTC
## Describe the Bug

Malformed tables (e.g. incorrect header syntax) cause linter to hang indefinitely. 

## How to Reproduce

Lint the attached example markdown file which contains a malformed table: "Malformed Table Hangs Linter.md"

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run. > Logs are not produced so unable to provide them.

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

data.json attached. I am unclear which rule causes the issue.

## Expected Behavior

Linting is not expected to transform malformed tables, so it should just ignore them in that case. 

## Screenshots

NA

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

This bug makes it very difficult to bulk lint large folders since only one malformed table causes linter to hang and very difficult to find the troublesome file.

[data.json.zip](https://github.com/platers/obsidian-linter/files/10990321/data.json.zip)
[Malformed Table Hangs Linter.md](https://github.com/platers/obsidian-linter/files/10990337/Malformed.Table.Hangs.Linter.md)

**Comment by pjkaufman** [comment] 2023-03-17 22:07
@grantx2016 , what you are requesting here is a lot harder said than done. Parsing tables is already super difficult in markdown and creates problems. If I were to force the use of a specific markdown table format, then the performance could be greatly improved, but as of right now, I have been unable to find a good way to parse tables.

I have used a markdown parser, but long files caused issues https://github.com/platers/obsidian-linter/issues/458 and now it seems that the regex that is more performant, but may not be as accurate is also having performant is also having issues. I am not sure I can fix this as it stands, but I do appreciate the notice about the issue.

**Comment by pjkaufman** [comment] 2023-03-17 22:25
Dev Note:
Take a look at the following links and see if any of them help with this performance issue:
https://github.com/tgrosinger/advanced-tables-obsidian/blob/main/src/table-editor.ts
https://github.com/aidenlx/table-extended
https://www.npmjs.com/package/@gerhobbelt/markdown-it-regexp
https://www.npmjs.com/package/markdown-it-multimd-table
https://github.com/tgrosinger/advanced-tables-obsidian

**Comment by grantx2016** [comment] 2023-03-17 22:28
@pjkaufman Thanks for the quick reply and confirmation on the issue.

For clarity, I don't expect linter to fix the table issues. I appreciate that fixing them is a nightmare (I think I have aged 10 years trying writing regexes to fix them). However, some possible ways to reduce the impact of this issue would be:

1. Ignore whatever it is that is causing linter to hang, or if you know the malformed syntax that is causing the issue, I could possible write a regex to fix at least fix that.
2. Offer some way of identifying the troublesome markdown file that is causing the hang (so that I could manually fix the table). I could not see any way of doing this with Chome Dev Tools.

**Comment by grantx2016** [comment] 2023-03-17 22:30
> Dev Note:
> Take a look at the following links and see if any of them help with this performance issue:

Just saw your latest reply. I will take a look. Thanks.

**Comment by pjkaufman** [comment] 2023-03-17 22:33
> @pjkaufman Thanks for the quick reply and confirmation on the issue.
> 
> For clarity, I don't expect linter to fix the table issues. I appreciate that fixing them is a nightmare (I think I have aged 10 years writing regexes to fix them). However, some possible ways to reduce the impact of this issue would be:
> 
> 1. Ignore whatever it is that is causing linter to hang, or if you know the malformed syntax that is causing the issue, I could possible write a regex to fix at least fix that.
> 2. Offer some way of identifying the troublesome markdown file that is causing the hang (so that I could manually fix the table). I could not see any way of doing this with Chome Dev Tools.

I tried looking for a way to kill the regex processing if it took more than a minute or 2 to run and then log the error, but it seems that is not really feasible. I am not sure what is causing the regex to hang exactly and there is no good way of doing that from what I can tell. Since I have little experience diagnosing problems with regex except via trial and error, I am not sure I can do much on that front. I may have to shift to another package and see if it alleviates this issue without creating another performance issue.

**Comment by pjkaufman** [comment] 2023-03-17 22:34
Also, the Linter does not try to fix the table. Trying to determine if a table is present in the file is what is causing the issue in this case.

**Comment by pjkaufman** [comment] 2023-04-20 00:08
> Dev Note: Take a look at the following links and see if any of them help with this performance issue: https://github.com/tgrosinger/advanced-tables-obsidian/blob/main/src/table-editor.ts https://github.com/aidenlx/table-extended https://www.npmjs.com/package/@gerhobbelt/markdown-it-regexp https://www.npmjs.com/package/markdown-it-multimd-table https://github.com/tgrosinger/advanced-tables-obsidian

Based on what I am seeing here is my research on each of the links to look at:
| Link | Result |
| ------ | --------- |
| https://github.com/tgrosinger/advanced-tables-obsidian/blob/main/src/table-editor.ts | requires the table to start with and end with `\|` which makes it not line up with markdown specs, but it may allow for further extensibility. More research is needed. |
| https://github.com/tgrosinger/advanced-tables-obsidian | Same issue as the previous one |
| https://github.com/aidenlx/table-extended | uses https://fletcher.github.io/MultiMarkdown-6/syntax/tables.html as its spec which does not follow markdown and would not work with markdown tables in blockquotes or other kinds of nesting |
| https://www.npmjs.com/package/markdown-it-multimd-table | Same issue as the previous one |
| https://www.npmjs.com/package/@gerhobbelt/markdown-it-regexp | Looks to deal with regex and a different set of plugins and is seemingly unrelated to the logic in question |

**Comment by pjkaufman** [comment] 2023-04-20 00:40
Note that it may be worthwhile to try building the regex onload based on https://github.com/fletcher/MultiMarkdown/blob/master/Utilities/table_cleanup.pl and seeing if it works any better than the current regex.

**Comment by pjkaufman** [comment] 2023-04-20 01:14
Here is the markdown spec for tables: https://github.github.com/gfm/#tables-extension-
Things a table must have:
- a table header
- a table divider/delimiter row with the same amount of cells as the table header
- 0 or more table rows

We could try to parse a table via the following process:
- Check for a table separator and if there is not a table divider then there is no true table
- Check the line previous to the table divider to see if it exists and has the same amount of cells as the header
- Then while each subsequent line is not an empty line and matches the definition of a table row, keep moving from one line to the next

**Comment by pjkaufman** [comment] 2023-04-20 02:23
Possible regex that is generic enough that it may work:
`/^[^\n]*?\|[^\n]*?(\n|$)/gm`.

**Comment by pjkaufman** [comment] 2023-04-20 02:35
Looks like the following regex may do the trick and be pretty fast:
`/^([^\n]*?\|[^\n]*?(\n|$)){2,}/gm`. I will need to test it against a really large file yet and fix one of the UTs. But assuming not issue with either of those, the matlformed table should get ignored as a table despite not truly matching the specs for a table.

I am debating whether that is considered acceptable or whether it would be better to adhere to the specs using a function. I will probably adhere to the specs using a function instead to prevent erroneous matches.

**Comment by pjkaufman** [comment] 2023-04-20 22:14
I hope to have a potential alternative either today or tomorrow for the table identifier. But it will likely take a little time to iron out the kinks with it.

**Comment by pjkaufman** [comment] 2023-04-20 22:14
The change may allow for a fix for https://github.com/platers/obsidian-linter/issues/597 as well.

**Comment by pjkaufman** [comment] 2023-04-21 18:28
I think I have an algorithm for identifying proper tables. I still need to check its performance on the example provided here and the really large example that was the reason for the move to regex, but it is looking like that I will go with this implementation. It is currently passing all of my tests, and I will run it against my notes to see if it has any adverse affects there on a real dataset.

**Comment by pjkaufman** [comment] 2023-04-21 18:37
Looks like it does just fine in terms of speed as it is not really slower than what was used previously from what I can tell. Now to test it on my personal vault and see how that turns out.

**Comment by pjkaufman** [comment] 2023-04-21 18:46
Looks like there may be a minor issue. I need to figure out what is going on with a YAML related rule. It may not be related to the change for table parsing.

**Comment by pjkaufman** [comment] 2023-04-21 18:51
Looks like it is caused by the new table parser. I will look and see if I can ignore the YAML block properly in the parser.

**Comment by pjkaufman** [comment] 2023-04-21 19:13
Looks to be working now.

**Comment by pjkaufman** [comment] 2023-04-21 19:25
I believe that this is fixed now on master and will go out in the next release. Please let us know if this is not true on master or in the next release.

**Closed** 2023-04-21 19:24 UTC
Labels: bug, markdown, reproducible
