### ISSUE TITLE
FR: How to disable the automatic addition of spaces to the ends of bolded text

### ISSUE THREAD

**Issue by PaulHerrero** [platers/obsidian-linter#635] opened 2023-03-01 05:33 UTC
Hi, when I run Linter it automatically adds spaces to the ends of the bolded text, as shown
![image](https://user-images.githubusercontent.com/56058332/222053399-be9b1896-00bb-4005-a30b-73548eba553d.png)
I would like to know how to disable the automatic addition of spaces, thanks

**Comment by pjkaufman** [comment] 2023-03-01 23:13
Hey @PaulHerrero , could you post a reproducible example as well as provide the list of rules you use? More than likely you will need to disable https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#space-between-chinese-japanese-or-korean-and-english-or-numbers. But I am not sure if that is the case without a reproducible example.

**Comment by PaulHerrero** [comment] 2023-03-02 02:10
> Hey @PaulHerrero , could you post a reproducible example as well as provide the list of rules you use? More than likely you will need to disable https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#space-between-chinese-japanese-or-korean-and-english-or-numbers. But I am not sure if that is the case without a reproducible example.

Example text：
青**青园**中葵AB**CD**E

When I run Liner with Space between Chinese Japanese or Korean and English or numbers on, spaces are automatically added to the ends of the bolded Chinese characters, but not to the ends of the bolded English characters

When I turn off Space between Chinese Japanese or Korean and English or numbers, no spaces are automatically added to the ends of either the bolded characters or the bolded English

Can you fix this, when I turn on Space between Chinese Japanese or Korean and English or numbers, the bolded characters do not automatically add spaces at the ends

Thank you very much!

**Comment by pjkaufman** [comment] 2023-03-14 12:32
Sorry about the delay in responding. Without knowing what the expected result is and what the original data is for each of the scenarios you are describing, I am not sure I know a solution to what you are referring to. Bold text should not get spaces added around them as they get ignored by the space between Chinese, Japanese, or Korean characters with English characters or numbers around them.

**Comment by PaulHerrero** [comment] 2023-03-14 13:25
> Sorry about the delay in responding. Without knowing what the expected result is and what the original data is for each of the scenarios you are describing, I am not sure I know a solution to what you are referring to. Bold text should not get spaces added around them as they get ignored by the space between Chinese, Japanese, or Korean characters with English characters or numbers around them.

Sorry, I didn't make that clear

The situation now is：
When I turn this option on and run LInter, spaces are automatically added to the ends of the bolded Chinese
![image](https://user-images.githubusercontent.com/56058332/225012974-7e9463c4-fdf6-4caa-81aa-b1ea0cf28605.png)
![screenshots](https://user-images.githubusercontent.com/56058332/225013445-a26ab4d5-9419-4e29-b86a-503b59847c92.gif)

What I would like is:

When I turn this option on and run LInter, don't automatically add spaces to the ends of the bolded Chinese

**Comment by pjkaufman** [comment] 2023-03-14 14:03
Ah. I see. That might be feasible. The problem is the ignore there adds the space. I can take a look at that and see what happens at some point.

**Comment by PaulHerrero** [comment] 2023-03-15 03:46
> Ah. I see. That might be feasible. The problem is the ignore there adds the space. I can take a look at that and see what happens at some point.

Thank you

**Comment by pjkaufman** [comment] 2023-04-10 17:56
This may be fixed now, but I need to have it double checked (#667 ).

**Comment by pjkaufman** [comment] 2023-04-11 23:20
This issue seems to be fixed as of this last release. Please let us know if that is not the case.

In the meantime, I am closing this issue as having been completed.

**Closed by pjkaufman** 2023-04-11 23:20 UTC
Labels: rule suggestion
