### ISSUE TITLE
Bug: Corrupts YAML

### ISSUE THREAD

**Issue by kmaustral** [platers/obsidian-linter#958] opened 2023-12-04 03:06 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

When choose the command to Lint file, the YAML is corrupted.

## How to Reproduce

Using 1.21 Linter

For instance:
`tags: book`

becomes
`tags: book`
`formtags: book`

 becomes
`tags: book`
`formttags: `
`d - book`

Or

Example to reproduce issue with

``` markdown
example here
```

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run.

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

## Expected Behavior

Expected output if applicable:

``` markdown
expected output here
```

## Device

- [x] Desktop
- [x] Mobile

**Comment by pjkaufman** [comment] 2023-12-04 10:03
Hey @kmaustral . Could you provide your `data.json` and a sample file that causes the problem? This will help me reproduce the issue.

**Comment by pjkaufman** [comment] 2023-12-04 16:16
Hey @kmaustral , just to double check. Are you using live preview when you view a markdown file? I ask because there has been reported bugginess around that that has not been resolved since it does not seem to be consistent across vaults (I have been able to reproduce some instances of it and other times I have not been able to). I just want to rule that out since so far running the following rules individual I am not seeing any output that would cause the issue you are seeing:
- Format Tags in YAML
- Sort YAML Keys

**Comment by kmaustral** [comment] 2023-12-04 20:06
Thanks Peter. Yes, I was using Live Preview. I tried it with Source mode
and there were no problems. I'll remember to change mode when performing
the clean.

Much appreciated,

Kevin

**Comment by wenbopeng** [comment] 2023-12-10 08:15
same issue  using Live Preview

**Comment by pjkaufman** [comment] 2023-12-10 10:11
> same issue using Live Preview

This should be fixed in the next release of the Linter. If not, please let us know so we can see why it is still not working.

**Comment by pjkaufman** [comment] 2023-12-10 10:13
I believe this was fixed by #963 .

**Comment by pjkaufman** [comment] 2023-12-10 10:13
If this issue is present on master or in the next release please let us know!

**Closed by pjkaufman** 2023-12-10 10:13 UTC
Labels: bug, help wanted, yaml, resolution/update-made, live-preview
