### ISSUE TITLE
FR: Disable a custom regex without deleting it.

### ISSUE THREAD

**Issue by Bad3r** [platers/obsidian-linter#1212] opened 2024-10-29 09:01 UTC
## Is Your Feature Request Related to a Problem? Please Describe.

Regex can be annoying.. it would be nice to be able to disable some rules temporarily instead of having to delete them and add them again.

## Describe the Solution You'd Like

Add the ability to enable/disable a custom regex via a checkbox for example

**Please include an example where applicable:**
N/A

## Describe Alternatives You've Considered

N/A

## Additional Context

N/A

**Comment by pjkaufman** [comment] 2024-10-29 21:59
Hey @Bad3r , thanks for the feedback.

This issues is more descriptive here, but is this not a duplicate of #1098?

**Comment by Bad3r** [comment] 2024-10-30 03:12
> Hey @Bad3r , thanks for the feedback.
> 
> 
> 
> This issues is more descriptive here, but is this not a duplicate of #1098?


Good catch it's a duplicate. Could you edit the other issue title to be more descriptive to prevent future dubs? I wasn't able to find it while searching before creating this one.

**Comment by pjkaufman** [comment] 2024-11-15 12:48
I can go ahead and do that.

**Closed by pjkaufman** 2024-11-15 12:48 UTC
Labels: rule suggestion
