### ISSUE TITLE
Bug: double pasting

### ISSUE THREAD

**Issue by menagerie198** [platers/obsidian-linter#464] opened 2022-10-29 10:27 UTC
## Describe the Bug

Copy pasting results in two copies of the pasted text

## How to Reproduce

Ctrl+C some text -> Ctrl+P = some textsome text

## Expected Behavior

some text

## Device

- [ ] Desktop Obs 1.0.3 - Win 10, Linter 1.7.0
- [ ] Mobile

## Additional Context

This started with the most recent Linter update. I tried enabling the 'Prevent double...' toggles in the Linter settings = no effect on this problem. 
It does not happen in the sandbox vault. This suggests it is an interaction with another plugin/snippet (I have MANY). The only error message I am getting in DevTools is for the Floating Table of Contents plugin. Disabling that had no effect on this problem. Apologies if none of this is relevant - I don't really know what I am doing.

**Comment by pjkaufman** [comment] 2022-10-29 11:06
Thanks for reporting this. Do you mind providing your data.json and some text you can reproduce this with? I have been using the paste rules without a problem for several weeks now. So a reproducible example would be greatly appreciated.

**Comment by pjkaufman** [comment] 2022-10-29 14:48
It could be that there are multiple plugins that attach to the paste event which could cause issues. But without a list of installed plugins and the `data.json` for the Linter I am not really able to say for sure what the cause is.

**Comment by menagerie198** [comment] 2022-10-29 17:36
Here you go - the pligin list is BIG, iI' afraid.
[plugin_list.txt.txt](https://github.com/platers/obsidian-linter/files/9894231/plugin_list.txt.txt)
Here is the Linter data.json (github would not let me share the `'json`, so I saved it as a `txt` file)
[data_json.txt](https://github.com/platers/obsidian-linter/files/9894238/data_json.txt)

**Comment by pjkaufman** [comment] 2022-11-01 17:22
> Here you go - the pligin list is BIG, iI' afraid. [plugin_list.txt.txt](https://github.com/platers/obsidian-linter/files/9894231/plugin_list.txt.txt) Here is the Linter data.json (github would not let me share the `'json`, so I saved it as a `txt` file) [data_json.txt](https://github.com/platers/obsidian-linter/files/9894238/data_json.txt)

Gotcha, by chance are any others affecting the output of the paste command? I may need to swap how paste is handled and see if there is a way to avoid double pasting a value. But in reality there should be a way to intercept the paste value and edit it before actually pasting the result.

**Comment by menagerie198** [comment] 2022-11-01 18:15
I deactivated Linter and the issue went away - so it looks like that is the seat of the double pasting.

**Comment by pjkaufman** [comment] 2022-11-01 18:19
I wouldn't necessarily assume that. It could be that now instead of 2 plugins trying to paste, there is only 1. I am reaching out to the dev community for help on this since it is hard to tell what could cause this.

Did double pasting happen no matter what you pasted or just for specific strings?

I can check if the paste event has already been handled and add a section that specifies that the paste event has been handled, but that will only work as long as whatever else is pasting has specified it has handled the pasting event and checks to make sure that the paste event has not already been handled.

**Comment by pjkaufman** [comment] 2022-11-01 18:27
Currently the Linter does not check if the event has been handled nor does it tell other event listeners it has been handled. As a result, it may be that that is causing the issue. But I won't know until I can reproduce this issue.

**Comment by pjkaufman** [comment] 2022-11-01 22:57
I am going to add a check to only paste if the paste event has not already been handled and I will make sure to register that the paste event has been handled afterwards. If that does not fix the problem, it is either a special bug in Linter that has not yet been uncovered or there is something outside of the plugin that is pasting the content as well which would cause the issue.

Either way the Linter is involved, but though without a reproducible example to examine locally, I will not know if the cause is the Linter or 2 plugins or something else causing the problem. I the changes I am making should go out next release.

**Comment by pjkaufman** [comment] 2022-11-01 23:11
I made a change to prevent running the paste event if it has already been handled. If you want to test it out before the next release to see if it fixes the issue you were dealing with, feel free to do so. Hopefully this fixes what you were seeing. I will leave this open since I am not sure that it does fix the issue.

**Comment by pjkaufman** [comment] 2022-11-01 23:14
What happens if linter is enabled and `obsidian-smarter-paste` is disabled? Does that fix the issue? I am curious to see if both are trying to paste.

**Comment by menagerie198** [comment] 2022-11-04 23:46
I had 'smarter paste' installed via BRAT, but it was not running. I also have 'Pasta copinara' installed AND running. Turning that off returned cut'n'pasting to the desired single copy/paste. So there appears to be an interaction there --- 
oooops - scratch that it appears PastaCopinara and Smarter Paste are the same plugin!

**Comment by menagerie198** [comment] 2022-11-04 23:51
To be clear... Turning off `Obsidian smarter paste`/`Pasta Copinara`, with `Linter` on, returned the copy-paste function to normal

**Comment by pjkaufman** [comment] 2022-11-07 12:10
Thanks for the update. Smarter Paste/Pasta Coprina is what the Linter's paste rules are based on. I am going to close this as it should be resolved now and the next release of the plugin should shore up an edge case.

**Closed by pjkaufman** 2022-11-07 12:10 UTC
Labels: bug, question
