### ISSUE TITLE
Bug: Math blocks breaking on linting

### ISSUE THREAD

**Issue by bmage8923** [platers/obsidian-linter#813] opened 2023-07-20 17:13 UTC
- [X] I have verified that I am on the latest version of the Linter

## Describe the Bug

Upon linting, extra line breaks are added inside of LaTeX math blocks (surrounded with $$ in the below examples), which breaks it in reading view. Also doing weird things where it duplicates sections after the latest update, but I haven't been able to figure out what's causing that one...

## How to Reproduce

1. Add markdown to an Obsidian file.
2. Save/lint.
3. Switch to reading mode.

Or

Example to reproduce issue with

``` markdown
- **Euclidean Distance**: The straight-line distance from one point to another, calculated via the Pythagorean theorem:

$$
\sqrt{(x_1-x_2)^2+(y_1-y_2)^2+\cdots+(n_1-n_2)^2}
$$
...
- Connectivity-based:
$$
\begin{aligned}
\frac{n*(n+1)}{2}=\frac{1000*1001}{2}=500500
\end{aligned}
$$
```

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run.

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

## Expected Behavior

Expected output if applicable:

``` markdown
- **Euclidean Distance**: The straight-line distance from one point to another, calculated via the Pythagorean theorem:

$$
\sqrt{(x_1-x_2)^2+(y_1-y_2)^2+\cdots+(n_1-n_2)^2}
$$
...
- Connectivity-based:
$$
\begin{aligned}
\frac{n*(n+1)}{2}=\frac{1000*1001}{2}=500500
\end{aligned}
$$
```

Actual output:

``` markdown
- **Euclidean Distance**: The straight-line distance from one point to another, calculated via the Pythagorean theorem:

$$

\sqrt{(x_1-x_2)^2+(y_1-y_2)^2+\cdots+(n_1-n_2)^2}

$$
...
- Connectivity-based:
$$

\begin{aligned}

\frac{n*(n+1)}{2}=\frac{1000*1001}{2}=500500

\end{aligned}

$$
```

## Screenshots

What it should look like in reading view:
![image](https://github.com/platers/obsidian-linter/assets/52695653/6ec03eaa-ab0b-4508-918d-edcefcb90c73)

What it's doing in editing view:
![image](https://github.com/platers/obsidian-linter/assets/52695653/845a4d3c-9107-4975-af0f-78fc86da3388)

What happens in reading view after it adds those line breaks:
![image](https://github.com/platers/obsidian-linter/assets/52695653/d6d38beb-9a5f-4050-9c30-96296a64784d)

Additional issue where it is now duplicating sections into the latex (after latest update):
![image](https://github.com/platers/obsidian-linter/assets/52695653/bf4b3d5a-cbdd-47f3-86a1-1973de983b48)

## Device

- [X] Desktop
- [ ] Mobile

## Additional Context

Running linter
Running Format Tags in YAML
Running Escape YAML Special Characters
rules before regular rules: 0.19999999925494194 ms
Running Format Yaml Array
format-yaml-array: 0.5 ms
insert-yaml-attributes: 0 ms
Running Move Tags to Yaml
move-tags-to-yaml: 19.299999998882413 ms
remove-yaml-keys: 0 ms
Running YAML Title
yaml-title: 0.900000000372529 ms
yaml-title-alias: 0 ms
file-name-heading: 0 ms
Running Header Increment
header-increment: 3.5 ms
Running Headings Start Line
headings-start-line: 0.30000000074505806 ms
Running Remove Trailing Punctuation in Heading
remove-trailing-punctuation-in-heading: 0.40000000037252903 ms
Running Footnote after Punctuation
footnote-after-punctuation: 0.6999999992549419 ms
Running Move Footnotes to the bottom
move-footnotes-to-the-bottom: 1 ms
Running Re-Index Footnotes
re-index-footnotes: 2.900000000372529 ms
auto-correct-common-misspellings: 0 ms
Running Convert Bullet List Markers
convert-bullet-list-markers: 0.40000000037252903 ms
emphasis-style: 0 ms
no-bare-urls: 0 ms
ordered-list-style: 0 ms
Running Proper Ellipsis
proper-ellipsis: 0.5 ms
quote-style: 0 ms
Running Remove Consecutive List Markers
remove-consecutive-list-markers: 0.7999999988824129 ms
Running Remove Empty List Markers
remove-empty-list-markers: 0.5 ms
remove-hyphenated-line-breaks: 0 ms
remove-multiple-spaces: 0 ms
strong-style: 0 ms
two-spaces-between-lines-with-content: 0 ms
unordered-list-style: 0.09999999962747097 ms
compact-yaml: 0 ms
Running Consecutive blank lines
consecutive-blank-lines: 0.40000000037252903 ms
convert-spaces-to-tabs: 0 ms
empty-line-around-blockquotes: 0 ms
Running Empty Line Around Code Fences
empty-line-around-code-fences: 3.399999998509884 ms
Running Empty Line Around Math Blocks
empty-line-around-math-blocks: 9.600000001490116 ms
Running Empty Line Around Tables
empty-line-around-tables: 10.299999998882413 ms
Running Heading blank lines
heading-blank-lines: 6.399999998509884 ms
Running Line Break at Document End
line-break-at-document-end: 0 ms
Running Move Math Block Indicators to Their Own Line
move-math-block-indicators-to-their-own-line: 3.899999998509884 ms
Running Paragraph blank lines
paragraph-blank-lines: 3.900000000372529 ms
Running Remove Empty Lines Between List Markers and Checklists
remove-empty-lines-between-list-markers-and-checklists: 14.399999998509884 ms
remove-link-spacing: 0 ms
remove-space-around-characters: 0 ms
remove-space-before-or-after-characters: 0 ms
Running Space after list markers
space-after-list-markers: 0.599999999627471 ms
space-between-chinese-japanese-or-korean-and-english-or-numbers: 0 ms
trailing-spaces: 0 ms
Running Custom Regex
custom regex rules: 0 ms
Running Capitalize Headings
rules after regular rules: 3.400000000372529 ms
rules running: 89.59999999962747 ms
Running Custom Lint Commands

**Comment by pjkaufman** [comment] 2023-07-20 20:59
@bmage8923 , could you provide your `data.json`? I am not able to reproduce the issue with the provided information.

**Comment by bmage8923** [comment] 2023-07-21 15:46
Here you go!
[data.zip](https://github.com/platers/obsidian-linter/files/12130292/data.zip)

**Comment by pjkaufman** [comment] 2023-07-21 16:06
Thanks! I will try again soon and hopefully be able to reproduce the issue.

**Comment by pjkaufman** [comment] 2023-07-22 21:42
@bmage8923 , thanks for providing the `data.json`. Unfortunately, I am still unable to reproduce the issue mentioned. Does the `data.json` on your vault cause the error with the exact markdown snippet you provided?

``` markdown
- **Euclidean Distance**: The straight-line distance from one point to another, calculated via the Pythagorean theorem:

$$
\sqrt{(x_1-x_2)^2+(y_1-y_2)^2+\cdots+(n_1-n_2)^2}
$$
...
- Connectivity-based:
$$
\begin{aligned}
\frac{n*(n+1)}{2}=\frac{1000*1001}{2}=500500
\end{aligned}
$$
```

**Comment by bmage8923** [comment] 2023-07-23 17:10
Interesting... Yes, it does occur on that. I was writing up that section of notes when I noticed this happening.

**Comment by pjkaufman** [comment] 2023-07-23 17:14
@bmage8923 , to clarify, if you just have a file with the following contents the issue happens for you with the `data.json` you provided above?

``` markdown
- **Euclidean Distance**: The straight-line distance from one point to another, calculated via the Pythagorean theorem:

$$
\sqrt{(x_1-x_2)^2+(y_1-y_2)^2+\cdots+(n_1-n_2)^2}
$$
...
- Connectivity-based:
$$
\begin{aligned}
\frac{n*(n+1)}{2}=\frac{1000*1001}{2}=500500
\end{aligned}
$$
```

**Comment by pjkaufman** [comment] 2023-07-23 17:15
I am seeing the following result after linting the file (I called the file `MathBlockIssue`):
``` markdown
---
title: MathBlockIssue
---
- **Euclidean Distance**: The straight-line distance from one point to another, calculated via the Pythagorean theorem:

$$
\sqrt{(x_1-x_2)^2+(y_1-y_2)^2+\cdots+(n_1-n_2)^2}
$$

…

- Connectivity-based:

$$
\begin{aligned}
\frac{n*(n+1)}{2}=\frac{1000*1001}{2}=500500
\end{aligned}
$$
```

**Comment by pjkaufman** [comment] 2023-07-23 18:22
I likely need the markdown for either the whole file or all of the math blocks in the section of the file having the problem.

It seems to me that the fix for #783 is causing both of these issues, but I cannot confirm that until I can reproduce the scenario in question.

**Comment by pjkaufman** [comment] 2023-07-25 00:07
I took a stab at reproducing this issue by guesswork and if it is correct, the problem would have existed with or without the changes made in #783 .

Here is why.
Say I have the following markdown:
``` markdown
$$
\sqrt{(x_1-x_2)^2+(y_1-y_2)^2+\cdots+(n_1-n_2)^2}$$

- here is some text

$$
\begin{aligned}
\frac{n*(n+1)}{2}=\frac{1000*1001}{2}=500500
\end{aligned}
$$
text
```

AS you can see, there should be 2 math blocks. However the first one is incorrectly formatted. However since the closing indicators are not already on their own line and they are followed by content that the parser does not consider to be precluded from a math block, you get the following two math blocks:
``` markdown
$$
\sqrt{(x_1-x_2)^2+(y_1-y_2)^2+\cdots+(n_1-n_2)^2}$$

- here is some text

$$
```

and

``` markdown
$$
text
```

There is nothing that the Linter can do to try to fix these scenarios as the AST is too malformed to work with. It assumes that the following is a paragraph due to how malformed the closing and opening math blocks are: 
``` markdown
\begin{aligned}
\frac{n*(n+1)}{2}=\frac{1000*1001}{2}=500500
\end{aligned}
```
Thus the output is correct for the AST that is showing up. There is only so much correction that the Linter can do in this case.

Here is the AST explorer: https://astexplorer.net/#/gist/eb3a2a32b750c9b18bd8b7e3708ea7e2/f4e94d9f240279925e1ece5da0e37018e833cdd5

**Comment by pjkaufman** [comment] 2023-07-25 00:08
I can make a tiny fix, but there is only so much course correction that can be made by the Linter.

**Comment by pjkaufman** [comment] 2023-07-25 00:36
I tinkered with things and believe I have a fix for the scenario I described above. But before I fully commit to it, I would like you to try it out and make sure it fixes at least one of the issues in question. As a heads up, ff I do not hear anything back by Sunday, I will proceed with my fix and close out this issue (this is to save me time as I cannot figure out any other way to reproduce the scenario in question and have not been provided more of the math blocks that supposedly are having the issue).

Here is the zip file that has the changes I made: 
[potential-math-block-fix.zip](https://github.com/platers/obsidian-linter/files/12155957/potential-math-block-fix.zip)

To install the change
- Download the zip
- Copy the `main.js` from the zip into your vault under `.obsidian/plugins/obsidian-linter`
- Disable and enable the Linter
- Run the Linter against the file in question and see if the math blocks are properly formatted (note that the starting state of the math blocks should be considered valid for the Linter to try properly handle them)

**Comment by pjkaufman** [comment] 2023-07-25 00:37
Thanks for bearing with me as I try to troubleshoot this issue.

**Comment by bmage8923** [comment] 2023-07-25 11:14
I really appreciate your help. I've been traveling this week, been a bit busy, sorry for the slow responses! When I get back to my desk I will try this out and let you know what happens.

**Comment by pjkaufman** [comment] 2023-07-25 11:57
Gotcha. Thanks for letting me know! Hopefully this will resolve at least one of the issues.

**Comment by bmage8923** [comment] 2023-07-27 15:03
Works! Thank you for the quick responses and getting that fixed!

**Comment by bmage8923** [comment] 2023-07-27 15:33
I'm not getting the weird duplication anymore, so it looks like it!

**Comment by pjkaufman** [comment] 2023-07-27 15:34
Nice. I will go ahead and close this then. The change should go out with the next release. But feel free to continue using that `main.js` I sent above in the meantime.

**Closed by pjkaufman** 2023-07-27 15:34 UTC
Labels: bug
