### ISSUE TITLE
FR: Add inverse format rule to `format-tags-in-yaml`, to normalize tags to be prefixed with a '#' 

### ISSUE THREAD

**Issue by Mega-JC** [platers/obsidian-linter#862] opened 2023-08-24 23:24 UTC
## Is Your Feature Request Related to a Problem? Please Describe.

Starting from [**v1.4.4**](https://obsidian.md/changelog/2023-08-23-desktop-v1.4.4/), Obsidian now supports '#'-prefixed tags in the YAML frontmatter for the `tags: ` property, provided that the entire tag is in quotes. These tags aren't visually distinct in the UI from non-prefixed tags, and [**there are uses for tags prefixed with a '#'**](https://forum.obsidian.md/t/properties-do-not-strip-hashtags-in-tags/64466/), which leads to people worrying over which format to use.

## Describe the Solution You'd Like

It would be great to have a rule that automatically adds the '#' to YAML frontmatter tags and wraps them in the quotes of choice.

### Before
``` markdown
---
tags:
  - one
  - #two
  - "#three"
  - 'nested/four/five'
---
```

### After
``` markdown
---
tags:
  - "#one"
  - "#two"
  - "#three"
  - "#nested/four/five"
---
```

## Describe Alternatives You've Considered

N/A

## Additional Context

The images below show YAML fronmatter tag formats and their representation in Obsidian's Live Preview UI.

<img width="1136" alt="image" src="https://github.com/platers/obsidian-linter/assets/65417594/bb1ce756-460e-4319-9f5b-71f106d5cac4">

<img width="1141" alt="image" src="https://github.com/platers/obsidian-linter/assets/65417594/a28b7827-35f2-46bf-b20f-ddd2f471ea10">

**Comment by pjkaufman** [comment] 2023-08-25 02:07
I plan to close this as a duplicate of #845 .

**Closed** 2023-08-25 02:52 UTC
Labels: duplicate, rule suggestion
