### ISSUE TITLE
Bug: Trailing spaces  Removing extra Spaces at the end will affect the outline

### ISSUE THREAD

**Issue by jiajiala** [platers/obsidian-linter#868] opened 2023-08-28 05:23 UTC
- [ ] I have verified that I am on the latest version of the Linter

## Describe the Bug

My blank outline node is removed and becomes "-"
Like this
![image](https://github.com/platers/obsidian-linter/assets/73203026/9db3c89b-119e-479a-a6b0-cf6cf95711c6)

**Comment by pjkaufman** [comment] 2023-08-28 09:09
I don't believe I follow what the problem is @jiajiala . Could you provide the source before and after for the markdown along with the expected value after Lint?

**Comment by jiajiala** [comment] 2023-08-29 01:11
![image](https://github.com/platers/obsidian-linter/assets/73203026/3dd01f30-ec31-46ec-aefb-be76c7629186)

Like this, by removing the Spaces at the end, my outline is broken

I'll leave some outline lines blank for special needs

[23_0828_200815___Test.md](https://github.com/platers/obsidian-linter/files/12459238/23_0828_200815___Test.md)

This is my source file
---
![image](https://github.com/platers/obsidian-linter/assets/73203026/3dd01f30-ec31-46ec-aefb-be76c7629186)
类似这样，通过移除末尾的空格，我的大纲被破坏了
因为特殊需要我会保留一些大纲的行是空白的
[23_0828_200815___Test.md](https://github.com/platers/obsidian-linter/files/12459238/23_0828_200815___Test.md)
这是我的源文件

**Comment by pjkaufman** [comment] 2024-12-24 19:06
Given that I have not really heard anything about this issue in over a year, I am going to go ahead and close this. We can revisit this if this is an issue that users are encountering and want a solution for. [Ranged ignores](https://platers.github.io/obsidian-linter/usage/disabling-rules/#range-ignore) can be used to avoid this issue, but you will lose the ability to run the Linter on any logic inside ranged ignores.

**Comment by pjkaufman** [comment] 2024-12-24 19:13
I am reopening this since I think this is actually something other than what I thought initially. I will see about making it so that list items are left with a single space on them after removing the trailing whitespace if the list item is empty.

**Comment by pjkaufman** [comment] 2024-12-24 19:44
I think that this is fixed with one changes I just made. I will go ahead and push that change up. I did not notice this issue before because another rule I commonly have enabled gets rid of empty list items.

**Closed** 2024-12-24 20:12 UTC
Labels: bug

**Comment by pjkaufman** [comment] 2024-12-24 20:13
This should be fixed in the next release. Please let me know if the issue persists on master or in the next release.
