### ISSUE TITLE
FR: Add Support for Custom Auto-Correct Misspellings

### ISSUE THREAD

**Issue by Skroderider** [platers/obsidian-linter#866] opened 2023-08-26 07:32 UTC
## Is Your Feature Request Related to a Problem? Please Describe.

I would like to add in custom auto-correct misspellings for things that might be specific to me (i.e. misspelling PowerShell as Powershell) but might be too frivolous to request adding to the main auto-correct map located here [Auto-correct map.ts](https://github.com/platers/obsidian-linter/tree/master/src/utils/auto-correct-misspellings.ts)

## Describe the Solution You'd Like

A new input box similar to "Ignore Words" in the Content tab which allows me to enter in custom autocorrect words. 
I'd be happy with any format the devs choose, but I think using an array format like below makes most sense.
```
['Powershell'],['PowerShell'], 
['diahorrea', 'diarrhea']
```

**Please include an example where applicable:**

*Current example*
``` markdown
You'll need: [A supported version of Windows](https://docs.chocolatey.org/en-us/chocolatey-components-dependencies-and-support-lifecycle#supported-windows-versions)
Powershell 2.0 or higher
	Powershell 3.0 
```

*Corrected example*
``` markdown
You'll need: [A supported version of Windows](https://docs.chocolatey.org/en-us/chocolatey-components-dependencies-and-support-lifecycle#supported-windows-versions)
PowerShell 2.0 or higher
	PowerShell 3.0 
```

## Describe Alternatives You've Considered

I tried using the plugin Completr, but found it to be excessive for my needs.

## Additional Context

I have included a mockup of the UI element for your consideration.
<img width="643" alt="image" src="https://github.com/platers/obsidian-linter/assets/143239044/994af400-af01-4849-8d12-75b77f6718b3">

**Comment by pjkaufman** [comment] 2023-09-03 23:33
Hey @Skroderider , thanks for the suggestion. Is there a particular reason why Custom Regex Replacement would not work for what you are trying to do here?

**Comment by Skroderider** [comment] 2023-10-10 09:03
Honestly had never occurred to me to use regex to fix spelling mistakes! 
I can do that, no problems

**Comment by Gewerd-Strauss** [comment] 2023-11-17 13:38
I think however that this should be reconsidered, for several reasons:

1. Regex is comparatively more complicated, particularly to people who don't or rarely use it. It's not exactly a _common_ thing once you step outside programming/coding.
2. Simplicity. Editing a textfile which is read into the map allows a user to keep simple replacements which are much easier to deal with without regex.  

---

However, as I am not fluent in javascript-regex (JS is not my focus at all and time is all too short right now), I could not figure out how to do this myself to open up for PR. Instead, I have a small script which modifies the relevant line in the compiled js file installed:

```js
}, We = class extends Wi { buildOption() { return new Vn(this.configKey, this.nameKey, this.descriptionKey, this.defaultValue) } }, cs = class extends Wi { buildOption() { return new is(this.configKey, this.nameKey, this.descriptionKey, this.defaultValue) } }; var sl = new Map([["magno", "mango"], ["qpcr", "qPCR"], ["pca", "PCA"], ["arbeit", "arbeit"], ["judsa", "Judas"], ["jdusa", "Judas"], ["madnatory", "mandatory"], ["uniformaly", "uniformly"], 
```

where variable `sl` contains all custom word replacements. It prepends custom definitions to the beginning of the array, thus allowing me to sidestep the issue entirely. 
The Hot Reload plugin then deals with reloading the plugin on the fly due to its filechange.

**Comment by pjkaufman** [comment] 2023-11-17 14:22
Hey @Gewerd-Strauss , it sounds like we may be talking past each other or I have poorly explained/documented how custom replace works. Custom replaced is designed for regex usage. However regex is not necessary. If you just use values as is (i.e. type in the find text as is and the replace text as is) then no regex knowledge is necessary.

It may make sense to add a checkbox for regular find and replace to make that the type for custome replace, but it will be case sensitive in that case.

**Comment by Gewerd-Strauss** [comment] 2023-11-18 23:37
I will quickly answer this in part because I am unfortunately _extremely_ short on time and have no clue if I can answer over the coming week.

> If you have an idea on how to avoid making the settings screen clunky while adding custom replace values, I can see this being possible.

One could simply ask for a user to supply a simple file containing needle/replace pairs. THat file could be part of the vault, or be located elsewhere on the computer. I have no experience writing this, but the Zotero integration has a file dialogue in its options (clicking on the folder-icon):
![grafik](https://github.com/platers/obsidian-linter/assets/80548781/d9b3b8f4-4bc5-46fe-b6d5-3f6cf40f9137)

SUch a means (or heck, even a super simple input line to give a path to a txt-file to be read in at plugin startup) could be used to load pairs from a custom user-sided file - which then shouldn't be purged upon plugin changes/reinstalls/deinstalls/whatever.

**Comment by pjkaufman** [comment] 2023-12-12 15:24
If I were to use a file format, I would much prefer either YAML as the key value pairs or a table that has only two columns and has all `|` values present since that would make the most sense to me personally. I would really hate having to deal with JSON in a markdown file. So if I were to add a file to reference it would need likely use a table. That will be very hard to explain in the description so it would need to link out to the documentation website to handle the explanation of the expected file format.

But beyond that, if there is nothing wrong with that, I would be fine with proceeding with this.

**Comment by Gewerd-Strauss** [comment] 2023-12-13 06:08
Sounds good to me.

**Comment by pjkaufman** [comment] 2024-06-30 21:03
I am currently working on this feature. But it may take me a minute to get this ready and present. I want it to be able to have a popup that lets the user know the exact values and their replacements that were found in a file specified as well as a count of how many word replacements were found in the file. So far I have started the process of just getting the setting to show up in the UI even though it does not fit the normal kind of rule setting.

**Comment by pjkaufman** [comment] 2024-08-06 01:28
I did want to make sure I added some context here as well for how this rule worked since I looked at some of the comments here and I think there may be a slight misconception on how the rule works.

Earlier I saw that there was a reference to `Powershell` being a word to correct. That is fine so long as you want all spellings of `powershell` to get corrected and to follow the case of the original word found. As it stands right now, the auto-correct logic assumes that all words present can be either uppercase or lowercase. It will assume all initial text to search for is lowercase. The replaced value can have any casing, but the first letter's case is determined by the instance of the lowercase word found. So if you had the following with a replacement of `powershell` to `PowerShell`:
``` markdown
powershell is awesome!
```
you would get:
``` markdown
powerShell is awesome!
```

This by design at this time and there is no current functionality built in to handle casing (if casing is a deal breaker, custom replacement is the way to go at this time).

Will this be a problem or does that make sense?

**Comment by pjkaufman** [comment] 2024-08-06 01:55
Also, as an update, I have the ability to select a file and parse the tables present. Whitespace is trimmed, and the value to replace is lowercased. It currently only loads the value to replace when the Linter loads initially or when a change is made in the settings. This is not the most robust, but for an initially implementation, I think it can work. I would like to put it out as a BRAT release once I get a couple of other things ironed out. Any thoughts or suggestions so far based on what I have said here?

**Comment by Gewerd-Strauss** [comment] 2024-08-06 07:48
I can't think of any issue with this proposal right now, I will think a bit more about it over the day. So far, this sounds good.

**Comment by pjkaufman** [comment] 2024-08-06 11:50
I will definitely let you know here when I create something on BRAT.

**Comment by pjkaufman** [comment] 2024-08-11 20:55
I want to give an update on this. I am almost done with the PR that will add this to the Linter. I just need to fix one part of the logic which is preventing me from being able to generate the docs. Once that is done, I plan to verify that the new docs make sense and then will see about moving forward with a BRAT release. It may be late tonight before I get to finish this. But I hope to have it today if not in the next couple of days.

**Comment by pjkaufman** [comment] 2024-08-11 21:13
Some good news is that I figured out the issues with the docs and got it to a state I like the results in. So I plan to go ahead and merge the changes. I am first running some local tests, but should have the PR merged in the next 10 minutes barring an issue popping up.

**Closed** 2024-08-11 21:15 UTC
Labels: rule suggestion

**Comment by pjkaufman** [comment] 2024-08-11 21:26
I just went ahead and added the changes for this to a BRAT release. Please let us know if there are any issues @Gewerd-Strauss and @Skroderider .
