### ISSUE TITLE
FR: Allow Removal of Whitespace Before and/or After Characters

### ISSUE THREAD

**Issue by miu007** [platers/obsidian-linter#593] opened 2023-01-20 18:31 UTC
## Describe the Bug

**Remove Space around Characters** does not work as described

## How to Reproduce

``` 
when I type in "This is a fullwidth comma	，  with text after it."
Instead of getting "This is a fullwidth comma，with text after it."
I got "This is a fullwidth comma	， with text after it." (even after lint the file multiple times)
I also found it does not remove space before the character such as "a word , another word" 
I have it switched on <img width="792" alt="image" src="https://user-images.githubusercontent.com/7776181/213778443-90b92a0c-a249-443a-9c9b-3119d4a8f113.png">

```

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run.

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

## Expected Behavior

It consistently failed to remove space in front of characters such as "," and ".". 

Expected output if applicable:

``` markdown
expected output here
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-01-26 00:21
@miu007 , this is actually working as intended. You did not include fullwidth forms in the image you provided: ![](https://user-images.githubusercontent.com/7776181/213778443-90b92a0c-a249-443a-9c9b-3119d4a8f113.png). You need to include those in order to remove the space around fullwidth characters. Please let us know if this does not fix the issue.

**Comment by pjkaufman** [comment] 2023-01-26 00:27
This rule works on the characters specified. Those characters can be fullwidth characters, CJK symbols and punctuation, en and em dashes or other characters you manually specify. It does not do this for all characters and you have to tell it what characters to do it on. So since no options have any values, it will just not run the rule on anything. Hopefully that explanation makes it clearer why it is not working on fullwidth characters.

**Comment by miu007** [comment] 2023-01-26 06:39
Thanks for the explanation! I made a huge mistake by not able to differentiate fullwidth and half width character. It works perfectly for full width characters. I am wondering whether similar rules exist for halfwidth characters (I am just so used to halfwidth). Thanks.

**Comment by pjkaufman** [comment] 2023-01-26 09:01
I am not sure what halfwidth characters are. Is that what regular English characters are?

**Comment by miu007** [comment] 2023-01-27 07:09
Yes, that is the default size of the English characters. I tried to add it to the `other symbols`, it can remove the space before and after it. However, the consensus is to leave a space after it.

If I write `abc , efg`, it will give me `abc,efg`, but I want `abc, efg`

Do you know if there is any workarounds? Thanks.

**Comment by pjkaufman** [comment] 2023-01-27 10:02
That has not really been added to the rules at this time. So there isn't really anything that can be done in the Linter for now.

**Comment by pjkaufman** [comment] 2023-04-21 19:33
It sounds to me like you want to remove space around punctuation. I think a rule could be added to allow the removal of space before certain punctuation marks and after other punctuation marks. But that would b a user editable list as that would be difficult to get right for all use cases.

**Comment by pjkaufman** [comment] 2023-04-21 19:35
This is essentially a duplicate of https://github.com/platers/obsidian-linter/issues/257 with some extra functionality added in. I will have to think about what punctuation marks are normally do not have spaces before them, and normally do not have spaces after them.

**Closed** 2023-05-14 00:24 UTC
Labels: enhancement, markdown

**Comment by pjkaufman** [comment] 2023-05-14 00:27
The rule for removing space before and or after certain characters has now been added to master and should go out in the next release. I have turned it on for my own vault and ironed out a few kinks, so hopefully several of the edge cases have been covered. Please let us know if there are any issues in the next release.
