### ISSUE TITLE
Bug: Add space between CJK & EN Not Ignoring the Ignoring of HTML

### ISSUE THREAD

**Issue by Erimus-Koo** [platers/obsidian-linter#667] opened 2023-04-04 03:00 UTC
```
Before
<u>自己想说的</u>

After
<u> 自己想说的 </u>
```

The underline will contain the extra SPACEs.

**Comment by Erimus-Koo** [comment] 2023-04-04 03:26
There may be a tricky way is to trim the extra space after adding it, not so elegant but easy.

**Comment by pjkaufman** [comment] 2023-04-07 21:17
The problem is that it needs to ignore `{any characters here}` before or after the text. It will take me a little bit of work to get this working, but it should be feasible to do. Is there a reason that HTML is being used here instead of the equivalent in makrdown?

**Comment by pjkaufman** [comment] 2023-04-07 23:00
I have tried to come up with a solution for this, but so far nothing has either worked correctly or been performant (i.e. the logic goes from finishing in under a 20 seconds to taking more than 1 minute for 2 tests out of all  7 tests). Thus I have not found a good way to do what you are asking at this point.

Hopefully we can find something performant and simple to handle this scenario because I would prefer not to really slow down the Linter logic to handle this scenario.

**Comment by pjkaufman** [comment] 2023-04-07 23:05
If you are curious, html is being ignored, but the resulting ignore is `{HTML_PLACEHOLDER}自己想说的{HTML_PLACEHOLDER}`. Thus the regex matches it and adds spaces.

We cannot just ignore `{` and `}` before or after CJK characters because that causes the ability to add spaces around math and inline math blocks when this rule is active since they are also ignored to prevent their content from getting ignored.

Trying to pull in enough characters to determine if the CJK character is preceded or followed by a CJK character is not performant (at least the way I wrote it using regex).

**Comment by pjkaufman** [comment] 2023-04-07 23:16
It may be feasible to ignore `{` and `}` and just search for the temporary values for inline math and math blocks as their own regex functions that would get run.

**Comment by pjkaufman** [comment] 2023-04-08 02:52
Looks like I have something that fixes this scenario.

**Comment by pjkaufman** [comment] 2023-04-08 02:59
This should be fixed on master now and be fixed in the next release. Please let us know if either is not the case.

**Closed** 2023-04-08 02:58 UTC
Labels: bug, markdown, reproducible

**Comment by Erimus-Koo** [comment] 2023-04-09 07:29
Great job! Thank you so much for spending your weekend completing this fix. You are amazing!

**Comment by pjkaufman** [comment] 2023-04-12 13:30
No problem. This is something that needs to be handled in other places too, so I decided this would be a good first try for this kind of thing.
