### ISSUE TITLE
Bug: Help menu in plugin list

### ISSUE THREAD

**Issue by ms3056** [platers/obsidian-linter#565] opened 2022-12-22 06:09 UTC
## Describe the Bug
Please see screenshot. 
![image](https://user-images.githubusercontent.com/23712700/209068619-ef06712b-8208-44d2-89f7-2457be3de8e8.png)

**Comment by pjkaufman** [comment] 2022-12-22 10:03
@ms3056 , can you consistently recreate this? I have been unable to do so.

Could you try restarting Obsidian a couple times and seeing if the issue persists?

Also, how are you reproducing this issue?

This is the same as #564 which has been labeled as a fluke for now.

**Comment by pjkaufman** [comment] 2022-12-22 13:37
I reached out in the discord and found out that this may actually be a bug caused by the Linter. I will make a change and issue a patch. Hopefully it will resolve the issue, but I am not sure if it will since I am unable to reproduce this locally at this time.

**Comment by pjkaufman** [comment] 2022-12-22 14:30
I just merged in a potential fix for this and created a release. Could you update and see if the issue has been fixed @ms3056  and @Liong1976?

Thanks!

**Comment by Liong1976** [comment] 2022-12-22 17:14
It is working well now. Thanks, @pjkaufman

**Comment by pjkaufman** [comment] 2022-12-22 18:04
I am glad to hear that. I will close this issue in a couple if days if I don't hear any new reports about it.

**Comment by pjkaufman** [comment] 2023-01-12 12:24
I am closing this as I have not heard any new reports of the issue.

**Closed by pjkaufman** 2023-01-12 12:24 UTC
Labels: bug, question
