### ISSUE TITLE
FR: Consistent List Markers dropdown

### ISSUE THREAD

**Issue by codicem-ex-cinere** [platers/obsidian-linter#325] opened 2022-07-31 20:35 UTC
Currently the existing option "Convert Bullet List Markers: Converts common bullet list marker symbols to markdown list markers." covers some of this but there is no option to insure that list markers are optionally all consistent.

My case, a large portion of my imported notes designate list with * (asterisk), Obsidian created lists are - (dash) designated, my preference.

Solution: Adding a dropdown option adjacent to the existing "Convert Bullet List Markers" to select either "markdown", "-" or "*", would solve this. Alternatively a child line with dropdown below current toggle could be used.

PS. Thanks for the awesome plug-in!

**Comment by pjkaufman** [comment] 2022-07-31 20:48
@codicem-ex-cinere , thanks for request. This is a partial duplicate of #32 which covers this rule as well. The rules are slowly being added, but this one is definitely one I look forward to having added as well.

**Comment by pjkaufman** [comment] 2022-07-31 20:51
It would be a rule to let you specify which list marker you would like. I think it should not be difficult to implement, but it will take me some time to take a look and make sure it works correctly.

**Comment by codicem-ex-cinere** [comment] 2022-07-31 21:12
Awesome, thanks for the acknowledgement, looking forward to its implementation when you have time!

**Comment by yimingli** [comment] 2022-08-07 19:35
+1. Consistent list markers can also solve a pain point of mine as follows:

Before:
```markdown
* item 1
- item 2
```

After:
```markdown
* item 1

- item 2
```

Expected:
```markdown
* item 1
* item 2
```
Or:
```markdown
- item 1
- item 2
```

I can imagine people using different list markers to separate lists, although I always add a brief description between lists to separate them.

**Closed** 2022-10-01 01:45 UTC
Labels: duplicate, rule suggestion, markdown

**Comment by pjkaufman** [comment] 2022-10-01 01:47
This has been added to master. Please let us know if there are any issues with this on master or in the next release. Thanks for putting in the request and putting in the feature request!
