### ISSUE TITLE
Bug: linter breaks properties, but only when "source mode" is deactivated.

### ISSUE THREAD

**Issue by pictoys** [platers/obsidian-linter#906] opened 2023-10-03 13:38 UTC
- [x] I have verified that I am on the latest version of the Linter

## How to Reproduce

Or

Example to reproduce issue with

``` markdown
example here
```

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run.

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

## Expected Behavior

Expected output if applicable:

``` markdown
expected output here
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-10-03 13:55
Hey @pictoys . Please provide a reproducible scenario. I have gotten a couple reports along these lines, but I have not had time to look into them yet.

**Comment by pictoys** [comment] 2023-10-03 14:43
thy linting this with preview mode:


---
date created: 2023-09-18-Monday
date modified: 2023-09-23-Saturday
aliases: 
tags:
  - daily
---

**Comment by wickles** [comment] 2023-10-08 21:20
I have the same problem. It is corrupting my timestamps in normal mode (when the new properties viewer is showing). This does not appear to happen in source mode.

Reproduction (in normal mode)

1. Create a new note, lint to add YAML frontmatter with created and modified datetime keys.
2. Add some empty lines to modify the file, then lint again multiple times. After the first lint it should stop making modifications but instead it continues adding/removing characters as you can see in the notifications.
3. Go to source mode to investigate -- it is adding more digits to the seconds number, or extra colons, or other weird things.

**Comment by wickles** [comment] 2023-10-22 01:06
I have seconds (`ss`) in my timestamps format. When I hover over the timestamp properties I get a tooltip error:

> Please enter a valid value. The two nearest valid values are `T` and `T+1`.

where `T` is the existing timestamp in minutes with the seconds part stripped off.

If I change the time format to use `:[00]` instead of `:ss` the problem goes away. However this also means I lose precision in my timestamps. 

So this seems at least partially to be an obsidian properties bug. It's annoying because they document the timestamp format with an example:

```
time: 2020-08-21T10:30:00
```

So I guess `:00` for the seconds part is not an example but a strict requirement...

**Comment by pjkaufman** [comment] 2023-12-05 13:12
I may have a fix for this issue, but I am not certain it fixes all scenarios like this. There was an issue with Live Preview not working like Source Mode, so I had to change the save logic to update things all in one go. This may fix the issue and I can put the `main.js` on this issue if you want to test it out and see if it fixes your situation as well. I plan to get feedback from as many people experiencing the live preview issue as possible. Assuming all goes well, it will fix the issues seen there and go out in the next release.

**Comment by pjkaufman** [comment] 2023-12-08 21:20
I believe I have a fix for this that has just been merged in. The changes should be in the next release and on master. Please let us know if either master or the next release has issues.

**Closed by pjkaufman** 2023-12-08 21:20 UTC
Labels: bug, live-preview
