### ISSUE TITLE
Bug: linting headers level doesn't return expected results

### ISSUE THREAD

**Issue by matteobrusa** [platers/obsidian-linter#589] opened 2023-01-16 15:34 UTC
## Describe the Bug

I've enabled the 'header increment' feature.

## How to Reproduce
Create a note as follows
```
## Second 
### Third
## Second again
### Third again
```
Lint outcome:
```
# Second 
## Third
## Second again
### Third again
```

## Expected Behavior

```
# Second 
## Third
# Second again
## Third again
```

## Device

- [ x] Desktop
- [ x] Mobile

## Additional Context

I'm splitting long notes sections into new notes, this would help me reformatting the new notes.

**Comment by pjkaufman** [comment] 2023-01-26 00:57
This seems to be a duplicate of #576

**Comment by pjkaufman** [comment] 2023-01-26 00:59
As a duplicate of #576, I am going to close this and hopefully it will get fixed when that one does.

**Closed by pjkaufman** 2023-01-26 00:59 UTC
Labels: bug
