### ISSUE TITLE
Bug: Re-Index footnotes also moves footnotes to the bottom

### ISSUE THREAD

**Issue by shkarlsson** [platers/obsidian-linter#902] opened 2023-09-26 04:59 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

*Re-Index Footnotes* moves footnotes to the bottom, even when *Move Footnotes to the bottom* is unticked.

## How to Reproduce

1. In Linter settings, make sure *Re-index Footnotes* is turned on and *Move Footnotes to the bottom* is turned off.
2. Make a new document with the following text (without blockquotes):

```markdown
foo [^1]

[^1]: bar

foobar
```

3. Lint manually or via auto-lint on save.

## Expected Behavior

Expected behavior is that nothing should happen.

## Device

- [x] Desktop
- [x] Mobile (iOS)

**Comment by pjkaufman** [comment] 2023-09-26 10:45
Hey @shkarlsson , could you provide your `data.json`? When I have a chance to take a look at issues again, that will help me reproduce the issie if I have any trouble doing so.

**Comment by pjkaufman** [comment] 2023-09-26 20:18
Looks like I can reproduce. I need to take a closer look at this. But it looks like this logic has moved footnotes to the end of the text for a long time now. I do need to see if this was accidentally added or if it has been present since the rule has existed. If it is the latter, this would need to be changed to a feature request.

**Comment by pjkaufman** [comment] 2023-09-26 20:23
Looks like this is a bug that was introduced during a functionality rewrite. The original [here ](https://github.com/platers/obsidian-linter/blob/77df828d18f5a62ece2ef68d84cdbfc14bab0fe6/src/rules.ts#L579-L649)did not move the footnotes to the end of the file.

**Comment by pjkaufman** [comment] 2023-09-26 20:43
Because of https://github.com/platers/obsidian-linter/issues/359, I am likely going to need to need to either break the logic for putting footnotes in the proper order into their own rule or remove the rule for moving the footnotes to the end of the document. Both rules currently move the footnotes to the end of the document in order to properly re-index based on the order found in the file.

I am kind of in a bit of quandary around this. I am leaning towards breaking that logic out to its own rule and enabling it by default for those that currently have the re-index rule active. That way it can properly re-order the footnotes if you want (they will have to be at the end of the document) then re-index would tackle updating the indexes.

**Comment by pjkaufman** [comment] 2023-09-26 20:54
Here are several options that are coming to mind when it comes to potential solutions:
1. Add an option to re-index footnotes that will allow re-ordering the footnotes at the end of the document if they do not match order in which they are first referenced in the file
2. Break out the logic into its own rule
3. Move logic to move footnotes to the end of a file as its own option

I am leaning towards option 1 right now. But I will think on this for a little while and then decide which option to go with.

**Comment by shkarlsson** [comment] 2023-09-28 17:41
> Also, @shkarlsson , why is there content after the footnote reference? To me that seems wrong logically, but I could be wrong on that.

I wrote a PM in which I put my name and title after a "---" and exported to PDF. Tt looked very weird having the footnotes under that. :)

**Comment by redactedscribe** [comment] 2023-11-01 15:14
@pjkaufman I can confirm: "Re-Index footnotes" moves footnote to bottom without "Move Footnotes to the bottom" enabled.

It also doesn't do this cleanly: The link in my footnote which is getting moved to the bottom is getting replaced by the last `[link](addr)`-formatted link in my document. It is also causing the last item in a list to be moved to the next header for some reason. My guess that's a side effect of the original error?

**Comment by pjkaufman** [comment] 2023-12-11 18:42
I am planning on doing the following 2 things:
- Convert this rule to be as it was before where it does not move footnotes to the bottom or base indexed footnotes on the order they show up in the document
- Create a new rule for ordering footnotes based on where they show up in the document

This should address both problems.

My two main concerns are that this will change the logic for users (though it sets the logic back to the proper way this should work) and that the footnote rules may tinkering with to make sure they run in such a way that we first move footnotes, then sort them, then reindex them (assuming all 3 rules are enabled).

**Comment by pjkaufman** [comment] 2023-12-11 20:30
I have been thinking about adding a new rule and think that it makes more sense to add an option to move footnotes to the end of the file to sort them based on the order they are found in the file. That seems like it makes the most sense as opposed to trying to add a new rule for it.

**Comment by pjkaufman** [comment] 2023-12-11 20:57
If I am reading things correctly, it looks like the rule for moving footnotes to the end of the file already sorts the references by the position at which they are first found in the file. This means that there should be no issue with leaving that rule alone and just focusing on getting reindex to work with preserving the footnote definition to key relationships without breaking anything.

**Comment by pjkaufman** [comment] 2023-12-11 22:11
Hey @shkarlsson , @redactedscribe . I believe I have a footnote rework ready for this change that should handle this. If one of you could test the following main.zip, that would be great! If not, no worries, I will plan to include it in the next release.

[main.zip](https://github.com/platers/obsidian-linter/files/13641492/main.zip)

**Comment by redactedscribe** [comment] 2023-12-11 22:41
Thank you @pjkaufman.

After testing the new main.js: It looks like the Re-index option no longer moves footnotes to the bottom or sorts them. It only updates/renumbers the unnamed footnotes to be from 1 to n from top to bottom.

There is an issue I've just notice, and I don't think either footnote option is causing it (both move/re-index disabled): _Named_ footnotes with a `-` present in their name have a new line following them, so named and unnamed (numbered) footnotes won't be contiguous (if they were before).

And a double-lint-required issue: Re-indexing also has issues if there is a mix of named and unnamed footnotes. Try with only re-index enabled: First it renames the keys to be numbered, and on second lint it renames the references to be numbered.

If you again test with a mix of named and unnamed footnotes, but this time with both re-index _and_ move enabled, the re-index of keys and moving of refs happen on the same lint, and on second lint, the refs can't be re-indexed because the named ones no longer point to a key (keys are all numbered now). Maybe reorder the operations will fix this.

The move option enabled alone seems to have no bugs. Hopefully I explained the issues clearly.

Please also consider updating the Linter option names or their descriptions to accurately describe their actions if need be, such as perhaps noting moving to the bottom also orders them.

**Comment by pjkaufman** [comment] 2023-12-11 23:34
Hey @redactedscribe . I have a couple of questions and observations since I am not super familiar with footnotes as I do not use them.

> After testing the new main.js: It looks like the Re-index option no longer moves footnotes to the bottom or sorts them. It only updates/renumbers the unnamed footnotes to be from 1 to n from top to bottom.

I am not sure what is meant by from top to bottom (maybe earliest to newest). If so, that is good. Otherwise, we have a problem that would need addressing.

> There is an issue I've just notice, and I don't think either footnote option is causing it (both move/re-index disabled): _Named_ footnotes with a `-` present in their name have a new line following them, so named and unnamed (numbered) footnotes won't be contiguous (if they were before).

Does the key/name you are referring to look like the following: `[^n-1]`?

> And a double-lint-required issue: Re-indexing also has issues if there is a mix of named and unnamed footnotes. Try with only re-index enabled: First it renames the keys to be numbered, and on second lint it renames the references to be numbered.

What is an unnamed footnote? I don't think I am familiar with those kinds of footnotes.

Thanks for helping me understand these situations better!

**Comment by redactedscribe** [comment] 2023-12-12 00:01
I will provide you with some example once I narrow this down some more.

**Comment by redactedscribe** [comment] 2023-12-12 00:23
> I am not sure what is meant by from top to bottom (maybe earliest to newest). If so, that is good. Otherwise, we have a problem that would need addressing.

Yes the earliest occurrence (top of file) to the latest (bottom) I believe.

> What is an unnamed footnote? I don't think I am familiar with those kinds of footnotes.

I just mean an "anonymous" footnote, i.e. `[^n]` as opposed to `[^hello-world]`.

> Does the key/name you are referring to look like the following: [^n-1]?

No. Here are some examples that result in weirdness. Also, I'm not sure if I read somewhere, maybe the plugin's docs that named and unnamed footnotes shouldn't be mixed?

Example:

```markdown
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.
```

With only Re-index option enabled, lints as:

```markdown
AAA[^2]

BBB[^3]

Something[^1]

CCC[^4]

DDD[^5]

[^foo-bar]: Some text.

[^1]: A
[^2]: B
[^4]: C
[^5]: D

More text.
```

And on second lint:

```markdown
AAA[^3]

BBB[^3]

Something[^2]

CCC[^4]

DDD[^5]

[^1]: Some text.

[^2]: A
[^3]: B
[^4]: C
[^5]: D

More text.
```

Same example but now only with the move option enabled, lints as:

```markdown
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.
```

Doesn't change on second lint.

Same example, but with both move and re-index enabled, lints as:

```markdown
AAA[^1]

BBB[^2]

Something[^3]

CCC[^4]

DDD[^5]

More text.

[^1]: A
[^2]: B

[^foo-bar]: Some text.

[^4]: C
[^5]: D
```

And linting again, error:

```
plugin:obsidian-linter:43 [Obsidian Linter] Lint File Error in File 'Temporary/Untitled.md':
Error "Move Footnotes to the bottom" encountered an unknown error: Footnote '[^foo-bar]: Some text.' has no corresponding footnote reference before the footnote contents and cannot be processed. Please make sure that all footnotes have a corresponding reference before the content of the footnote.
Error: Footnote '[^foo-bar]: Some text.' has no corresponding footnote reference before the footnote contents and cannot be processed. Please make sure that all footnotes have a corresponding reference before the content of the footnote.
    at Ru (plugin:obsidian-linter:73:335)
    at Rr.apply (plugin:obsidian-linter:1179:354)
    at Rr.safeApply (plugin:obsidian-linter:122:1517)
    at eval (plugin:obsidian-linter:117:3435)
    at ze (plugin:obsidian-linter:117:1205)
    at Os.apply (plugin:obsidian-linter:117:3405)
    at Qe.applyIfEnabledBase (plugin:obsidian-linter:122:607)
    at ro.lintText (plugin:obsidian-linter:2706:1035)
    at Ao.runLinterEditor (plugin:obsidian-linter:2714:7921)
    at originalSaveCallback.n.callback (plugin:obsidian-linter:2714:4041)
kd @ plugin:obsidian-linter:43
```

Maybe you fix addresses these. Give them a test.

**Comment by pjkaufman** [comment] 2023-12-12 00:41
Thanks for the examples. I ironically just finished my potential fix for re-index footnotes (it does not do anything for moving footnotes to the end of the document, but I think that one avoids this problem altogether by design).

**Comment by pjkaufman** [comment] 2023-12-12 00:53
@redactedscribe , here are the outputs based on the inputs provided:
case 1 input:
``` markdown
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.
```
case 1 output:
``` markdown
AAA[^2]

BBB[^3]

Something[^1]

CCC[^4]

DDD[^5]

[^1]: Some text.
[^2]: A
[^3]: B
[^4]: C
[^5]: D

More text.
```

The multiple lints did not change things.

case 2 input (both move footnote and re-index are on) input:
``` markdown
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.
```


case 2 output:
``` markdown
AAA[^1]

BBB[^2]

Something[^3]

CCC[^4]

DDD[^5]

More text.

[^1]: A
[^2]: B
[^3]: Some text.
[^4]: C
[^5]: D
```

It looks like it is working now with multiple variations. I am pushing up my changes to my pull request.

Here is the updated [main.zip](https://github.com/platers/obsidian-linter/files/13642356/main.zip)

**Comment by redactedscribe** [comment] 2023-12-12 01:06
With your new main.js:

I got the same results as you above.

But with only the move option enabled, the example lints as:

```markdown
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

More text.

[^1]: A
[^2]: B

[^foo-bar]: Some text.

[^hello-world]: C

[^3]: D
```

That would be fine if they were all contiguous.

Also, would there be any point to be able to re-index without converting named footnotes into numbered ones?

**Comment by pjkaufman** [comment] 2023-12-12 01:12
> With your new main.js:
> 
> I got the same results as you above.
> 
> But with only the move option enabled, the example lints as:
> 
> ```
> AAA[^1]
> 
> BBB[^2]
> 
> Something[^foo-bar]
> 
> CCC[^hello-world]
> 
> DDD[^3]
> 
> More text.
> 
> [^1]: A
> [^2]: B
> 
> [^foo-bar]: Some text.
> 
> [^hello-world]: C
> 
> [^3]: D
> ```
> 
> That would be fine if they were all contiguous.

I am not sure I understand what the problem is here. There probably should not bee any spaces between the different footnote definitions, but besides that, things look fine to me.

> Also, would there be any point to be able to re-index without converting named footnotes into numbered ones?

I am not sure what this statement means. It sounds like wanting to be able to re-index, but only re-index the numeric names. I just do not know what a use case for this would look like.

**Comment by redactedscribe** [comment] 2023-12-12 01:27
> I am not sure I understand what the problem is here. There probably should not bee any spaces between the different footnote definitions, but besides that, things look fine to me.

Yes, this is what I meant. They should be grouped.

After looking at it again, it's not related to the move option. With move and re-index disabled, it still lints with those empty lines. I'm trying to track down the cause.

**Comment by pjkaufman** [comment] 2023-12-12 01:31
> > I am not sure I understand what the problem is here. There probably should not bee any spaces between the different footnote definitions, but besides that, things look fine to me.
> 
> Yes, this is what I meant. They should be grouped.
> 
> After looking at it again, it's not related to the move option. With move and re-index disabled, it still lints with those empty lines. I'm trying to track down the cause.

If you add your `data.json` to this issue or enable trace logs in the debug settings, you should be able to get the logs for what the file looks like after each rule runs eventually getting you to the point where you can determine which rule caused the issue.

**Comment by redactedscribe** [comment] 2023-12-12 01:33
Thanks for the tip! It immediately revealed that `paragraph-blank-lines` is the culprit.

**Comment by pjkaufman** [comment] 2023-12-12 01:51
Gotcha. I believe that has come up before.  I am not sure how to get past that issue or if there is a way to get it working with the current ignore setup.

**Comment by pjkaufman** [comment] 2023-12-12 01:56
> Thanks for the tip! It immediately revealed that `paragraph-blank-lines` is the culprit.

Now that I am thinking a little harder about this, I can probably fix this by doing some tinkering to some logic.

**Comment by pjkaufman** [comment] 2023-12-12 02:01
Well, I tested the logic and it looks like `paragraph-blank-lines` should be working properly and ignoring the footnote definitions. Could you copy the logs from the debug tab and post or upload them here?

**Comment by redactedscribe** [comment] 2023-12-12 02:05
Here you are:
<details>
<summary>Click to expand</summary>

```
Running linter
Running Format Tags in YAML
format-tags-in-yaml: 0.19999998807907104 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

rules before regular rules: 0.19999998807907104 ms
Running Add Blank Line After YAML
add-blank-line-after-yaml: 0 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Format YAML Array
format-yaml-array: 0.10000002384185791 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Header Increment
header-increment: 0.30000001192092896 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Headings Start Line
headings-start-line: 0.09999996423721313 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Remove Trailing Punctuation in Heading
remove-trailing-punctuation-in-heading: 0.10000002384185791 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Default Language For Code Fences
default-language-for-code-fences: 0.19999998807907104 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Emphasis Style
emphasis-style: 0.19999998807907104 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Ordered List Style
ordered-list-style: 0.10000002384185791 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Remove Multiple Spaces
remove-multiple-spaces: 0.10000002384185791 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Strong Style
strong-style: 0.20000004768371582 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Unordered List Style
unordered-list-style: 0.09999996423721313 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Consecutive blank lines
consecutive-blank-lines: 0.19999998807907104 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Empty Line Around Blockquotes
empty-line-around-blockquotes: 0 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Empty Line Around Code Fences
empty-line-around-code-fences: 0 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Empty Line Around Tables
empty-line-around-tables: 0.10000002384185791 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Heading blank lines
heading-blank-lines: 0.19999998807907104 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Line Break at Document End
line-break-at-document-end: 0.09999996423721313 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.
[^1]: A
[^2]: B
[^hello-world]: C
[^3]: D

More text.

Running Paragraph blank lines
paragraph-blank-lines: 0 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.

[^1]: A
[^2]: B

[^hello-world]: C

[^3]: D

More text.

Running Remove Empty Lines Between List Markers and Checklists
remove-empty-lines-between-list-markers-and-checklists: 0.5 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.

[^1]: A
[^2]: B

[^hello-world]: C

[^3]: D

More text.

Running Remove link spacing
remove-link-spacing: 0 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.

[^1]: A
[^2]: B

[^hello-world]: C

[^3]: D

More text.

Running Space after list markers
space-after-list-markers: 0.10000002384185791 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.

[^1]: A
[^2]: B

[^hello-world]: C

[^3]: D

More text.

Running Custom Regex
custom regex rules: 0 ms
Running Blockquote Style
blockquote-style: 0.09999996423721313 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.

[^1]: A
[^2]: B

[^hello-world]: C

[^3]: D

More text.

Running Trailing spaces
trailing-spaces: 0.10000002384185791 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.

[^1]: A
[^2]: B

[^hello-world]: C

[^3]: D

More text.

Running YAML Key Sort
yaml-key-sort: 0 ms
AAA[^1]

BBB[^2]

Something[^foo-bar]

CCC[^hello-world]

DDD[^3]

[^foo-bar]: Some text.

[^1]: A
[^2]: B

[^hello-world]: C

[^3]: D

More text.

rules after regular rules: 0.3999999761581421 ms
rules running: 3.800000011920929 ms
```
</details>

**Comment by redactedscribe** [comment] 2023-12-12 02:07
Perhaps I need an updated main.js?

**Comment by pjkaufman** [comment] 2023-12-12 02:11
> Perhaps I need an updated main.js?

I see the issue. It was a bug in the regex for the footnote definitions which was causing the issue. I already fixed it before I saw it causing the issue with your results (so like 30 minutes ago). But I need to create a new `main.zip` for testing. Then I think I am going to call it a night.

**Comment by pjkaufman** [comment] 2023-12-12 02:18
Here is the updated main.zip: 
[main.zip](https://github.com/platers/obsidian-linter/files/13642912/main.zip)

This should fix that scenario. I believe that should take care of this bug and all of the things mentioned here on this issue.

**Comment by redactedscribe** [comment] 2023-12-12 02:25
Unfortunately, it does not. The last two main.zips have identical checksums. I think you may have uploaded the same one twice.

**Comment by redactedscribe** [comment] 2023-12-12 02:37
Appears to work great now! Thanks @pjkaufman.

**Comment by pjkaufman** [comment] 2023-12-12 02:39
> Appears to work great now! Thanks @pjkaufman.

Sounds good. I will plan on merging in the code changes for this and close this issue tomorrow. Thanks for bearing with me on this one.

**Closed** 2023-12-12 12:35 UTC
Labels: bug, footnote, reproducible

**Comment by pjkaufman** [comment] 2023-12-12 12:39
I just merged in the change for this bug. Hopefully it will fix most, if not all, of the issues mentioned. It is now on master and should be in the next release. Please let us know if there is an issue with either of those.

Thanks again for all of the feedback and help on this!

**Comment by shkarlsson** [comment] 2023-12-13 08:24
Amazing, thank you so much!
