### ISSUE TITLE
Bug: data modified fails

### ISSUE THREAD

**Issue by zhl111** [platers/obsidian-linter#887] opened 2023-09-12 15:49 UTC
After Obsidian is upgraded, the text is formatted using linter. The time cannot be modified, and it will not be automatically added after deletion.

This is the timestamp of the formatted text before the upgrade.
![image](https://github.com/platers/obsidian-linter/assets/29135984/c2082c9b-17bf-4d34-89b9-aa23d132e621)

**Comment by pjkaufman** [comment] 2023-09-12 16:29
Hey @zhl111 , could you provide your `data.json`, a sample file to reproduce the issue with, and a list of steps to follow to see the issue?

It looks like there may be issues with using the Linter and properties plugins together.

**Comment by pjkaufman** [comment] 2023-09-12 18:33
Could you try what you were doing on Obsidian v1.4.12? It seems there was a bug prior to that that made edits in source mode not show in properties view.

**Comment by ishirbhan** [comment] 2023-09-12 19:38
I'm seeing the same issue. I'm using properties as well, but didn't see the issue before today. I updated both Linter and Obsidian today.

**Comment by pjkaufman** [comment] 2023-09-12 19:43
They just released a patch for what seems to be this issue @ishirbhan  and @zhl111 . Please verify that you are on Obsidian v1.4.12 or higher.

**Comment by pjkaufman** [comment] 2023-09-14 10:48
@ishirbhan  and @zhl111 , unless I hear that the latest public version of Obsidian is experiencing this issue, I plan to close this issue Saturday since Obsidian announced that they fixed an issue where changes to the fronmatter were not being picked up by properties view in v1.4.11.

**Comment by ishirbhan** [comment] 2023-09-14 16:19
This appears to be resolved for me

**Comment by pjkaufman** [comment] 2023-09-15 00:55
Alrighty. I will go ahead and close this. It can be reopened if for some reason it is still happening.

**Closed by pjkaufman** 2023-09-15 00:55 UTC
Labels: bug
