### ISSUE TITLE
Bug: re-index-footnotes & move-footnotes-to-the-bottom can cause Obsidian freeze with footnote wrapping

### ISSUE THREAD

**Issue by ben-brook** [platers/obsidian-linter#784] opened 2023-07-09 16:57 UTC
- [x] I have verified that I am on the latest version of the Linter 

## Describe the Bug

Linting a file with re-index-footnotes or move-footnotes-to-the-bottom will cause Obsidian to freeze, I think indefinitely, if a reference is wrapped in two of its footnotes -- at least that's as far as I've been able to zoom into the cause. It didn't spit out any logs when it happened.

## How to Reproduce

1. Create a new file in a vault with contents:

```markdown
[^2]: a

a[^2]

[^2]: b
```

2. On macOS (I haven't tested elsewhere), open the file in the Obsidian app
3. Lint the file with re-index-footnotes or move-footnotes-to-the-bottom enabled  
4. Notice that Obsidian freezes

## Expected Behavior

If re-index-footnotes is enabled: user notification that re-index-footnotes doesn't work if there is more than one footnote for a key.

If move-footnotes-to-the-bottom is enabled: footnotes are moved to the bottom of the file as expected.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-07-09 17:11
Gotcha. I will have to take a look at this. It looks pretty malformed as far as footnotes go, but it should be able to handle it. It likely hit an infinite loop when finding the footnote definitions, but something else could be going on.

**Comment by pjkaufman** [comment] 2023-07-09 17:12
Also, you might want to define footnote wrapping as I am not sure I am familiar with that (I see it in the title).

**Comment by pjkaufman** [comment] 2023-07-09 17:17
It would also be helpful to have your `data.json` in case this is not something I am able to reproduce on my own.

**Comment by pjkaufman** [comment] 2023-07-09 17:28
Looks like there is an infinite loop in this case. I am trying to figure out what I am doing logically wrong in the logic, but hopefully it will not take too long to figure out.

**Comment by pjkaufman** [comment] 2023-07-09 17:32
Looks like the while condition need [here](https://github.com/platers/obsidian-linter/blob/0dde092ff02b7f1e5710537133017f768e563b9d/src/utils/mdast.ts#L246) needed to be 0 and not -1 for `re-index-footnotes`. I am looking into the moving of footnotes. It could very well be the same issue.

**Comment by pjkaufman** [comment] 2023-07-09 17:38
I believe I have a fix for this. Both were the while loop condition. I will push it up.

**Comment by pjkaufman** [comment] 2023-07-09 17:45
This should be on mater now and go out with the next release. Thanks for reporting the issue!

**Closed** 2023-07-09 17:44 UTC
Labels: bug, footnote

**Comment by ben-brook** [comment] 2023-07-10 02:57
Thank you!
