### ISSUE TITLE
Bug: Tags are not removed from the body in Live Preview

### ISSUE THREAD

**Issue by kepano** [platers/obsidian-linter#1164] opened 2024-09-12 14:03 UTC
Tags are not removed from the body in Live Preview. In source mode everything seems to work fine.

This problem does not occurs in Linter version 1.23.0, so I think it is related to a change since then. The examples below are from 1.26.0

The following settings are active:

- Move all tags to frontmatter of the document: true
- Body tag operation: remove whole tag

---

Input:

```
#people 
```

Output:

```
---
tags:
  - people
---#people 
```

---

Input:

```md

#people 
```

Output:

```
---
tags:
  - people
---

#people 
```

---

Input:

```md
People

#people
```

Output:

```md
---
tags:
  - people
---People
Ppeopl
e
```

**Comment by pjkaufman** [comment] 2024-09-13 23:25
Thanks for reporting this @kepano . I will have to take a closer look at this and see what is going on. Live Preview has been a real pain for me since it was introduced. Hopefully this will be an easy fix.

**Comment by pjkaufman** [comment] 2024-09-13 23:48
I am able to reproduce this in my integration tests. I am not quite sure what is going on here yet. But hopefully I can get to the bottom of this.

**Comment by pjkaufman** [comment] 2024-09-14 00:01
It looks like I have test case 1 fixed. I will have to check the other two cases.

**Comment by pjkaufman** [comment] 2024-09-14 00:56
I have something that looks to fix both cases mentioned, but sadly it breaks proper placement of the cursor in Live Preview. So I am not sure what is going on. I will need to take a break and look at this with fresh eyes.

**Comment by pjkaufman** [comment] 2024-09-16 21:55
Ok. I think I have this fixed thanks to some help. @kepano , do you use BRAT for the Linter? I am a little hesitant to make a regular release for the changes I just made for Live Preview. I am just not very familiar with codemirror. So I would prefer to make a BRAT release first.

**Comment by pjkaufman** [comment] 2024-09-25 22:42
I am going to close this since I believe this is fixed on master. I am hoping to create a BRAT release this week/weekend which should contain the change made to attempt to fix this.

**Closed by pjkaufman** 2024-09-25 22:42 UTC
Labels: bug, reproducible, live-preview
