### ISSUE TITLE
Regression: Since release 1.21.0, switching notes results in a loss of focus of the editor

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#969] opened 2023-12-07 21:02 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug
Since release 1.21.0, switching notes results in a loss of focus of the editor. You need to click with the mouse into the editor to have it focussed again.

## How to Reproduce
1. open quick switcher
2. switch to any other note
3. try to move cursor with arrow keys, it won't work.

Testing with all plugins disabled other than linter. Only disabling/enabling linter changed that behavior. Rolling back to 1.20.1 fixes the issue.

## Expected Behavior
No focus loss when switching notes

## Device
- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-12-07 21:29
Hey @chrisgrieser , do you use custom commands? If so, this may be expected behavior since I have to open the file you were just in in order to run the custom commands against it.

**Comment by pjkaufman** [comment] 2023-12-07 21:30
Could you provide your `data.json`, so I can try to recreate the issue? Thanks!

**Comment by chrisgrieser** [comment] 2023-12-07 21:30
Yeah, I have a custom command added

**Comment by pjkaufman** [comment] 2023-12-07 21:32
> Yeah, I have a custom command added

I am not sure the Linter refocuses on the file you were just in after running the custom command. That is likely the problem, but I will have to test to be sure though. I am not sure why this would not happen in the prior version of the Linter.

**Comment by pjkaufman** [comment] 2023-12-08 11:57
Here is my guess as to what is happening (I will have to test it later):
When you change files, the custom commands are triggered once the lint completes. This opens a new active window to lint the previous file with e custom commands (custom commands generally act on the currently active file, ao this has to happen for custom commands to work). Once it finishes, it does not properly set the focus back on the file you switched to.

Two things likely need to happen that currently probably do not:
- disable lint on active file change while the Linter is changing the active file (should prevent any infinite loops so long as timing does not get messed up)
- after running custom commands that required running in the sidebar, then set active file back to what it was before running the custom commands

This should tackle several of the problems.

**Comment by chrisgrieser** [comment] 2023-12-08 12:52
okay, I am back at the desk and have removed the custom command, and can confirm that it now works as it should

**Comment by pjkaufman** [comment] 2023-12-08 12:58
> okay, I am back at the desk and have removed the custom command, and can confirm that it now works as it should

Thanks for the update. I will have to see about fixing this.

**Comment by pjkaufman** [comment] 2023-12-09 03:40
I can reproduce this scenario. I will have to see about fixing it to remember where to go back to once the custom command finishes for the custom commands that run in the side bar.

**Comment by pjkaufman** [comment] 2023-12-09 03:41
I plan to tackle this one after the custom command issue for beautifying tables.

**Comment by pjkaufman** [comment] 2023-12-10 03:36
Hey @chrisgrieser . I believe I have a fix for this issue. If you could test the attached `main.zip`. That would be great! I plan to fix one more thing after this before I make a release with the patches for the fixed bugs.

[main.zip](https://github.com/platers/obsidian-linter/files/13626399/main.zip)

**Comment by chrisgrieser** [comment] 2023-12-10 08:56
Can confirm, this fixes the issue. Many thanks for the quick fix! 😊

**Closed** 2023-12-10 18:31 UTC
Labels: bug, obsidian, reproducible

**Comment by pjkaufman** [comment] 2023-12-10 18:32
This change has been merged into master. It should go out with the next release. Please let us know if there is an issue with this on master or in the next release.
