### ISSUE TITLE
Bug: Only works on mobile if no YAML

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#395] opened 2022-09-04 17:49 UTC
## Describe the Bug

On mobile, Linter does not do anything when activated if there is existing frontmatter.

## How to Reproduce

1. Create a new document in Obsidian mobile
1. Optionally create some content that Linter could fix
2. Invoke Linter via "Lint File"
3. It will perform its rules
4. Change things that would cause it to perform rules again (put blank lines in YAML, make changes that would cause the "date modified" field to change, whatever)
5. Invoke Linter again
6. Nothing happens

Tested with YAML Timestamp and Compact YAML

## Expected Behavior

Linter's rules take effect

## Device

- [ ] Desktop
- [x] Mobile

## Additional Context

Cannot reproduce on desktop, only mobile. Tested on iPad.

**Comment by Calorion** [comment] 2022-09-04 18:13
More info: When I invoke Linter via the "Linter: Lint the current file" command when there is existing YAML, an error is generated: "An error occurred during linting. See console for details"

**Comment by pjkaufman** [comment] 2022-09-04 18:30
Do you mind providing the exact file contents to reproduce the issue? It sounds like an issue with the rule maybe not working on iOS, which woukd be odd, but I would need to see the console output to be sure.

**Comment by pjkaufman** [comment] 2022-09-04 18:44
This may be related to #367

**Comment by Calorion** [comment] 2022-09-04 18:52
Here's the console output. ![image](https://user-images.githubusercontent.com/3050950/188329046-a8234ec4-f607-4f26-aac7-56e670d76600.jpeg)

**Comment by pjkaufman** [comment] 2022-09-04 19:12
Thanks! This looks like it is something iOS specific. What are your rule settings for yaml timestamp? Is that the only active rule? If not, can you test it as the only active rule to see if that rule is the problem?

**Comment by Calorion** [comment] 2022-09-04 19:29
I've uninstalled and reinstalled Linter, and re-enabled all the rules that I think I had active before, and I can no longer reproduce the issue. I'll let you know if it reappears.

**Comment by pjkaufman** [comment] 2022-09-04 19:33
Gotcha. That is good. Hopefully it stays gone.

**Comment by pjkaufman** [comment] 2022-09-05 14:08
If this is not able to be reproduced by the end of the week, I will go ahead and close this since it is no longer reproducible. Please let me know if this would be an issue for some reason.

**Comment by pjkaufman** [comment] 2022-09-13 10:54
It looks like this is no longer reprodcible, so I am going to go ahead and close this issue. Feel free to reopen this if it starts happening again.

**Closed by pjkaufman** 2022-09-13 10:54 UTC
Labels: bug, help wanted
