### ISSUE TITLE
Bug: `Move Tags to YAML` Can Leave Whitespace on the end of the YAML Frontmatter Leadint to YAML Duplication for Running of the Next YAML Rule

### ISSUE THREAD

**Issue by yazae** [platers/obsidian-linter#573] opened 2022-12-31 17:41 UTC
Hi,

## Describe the Bug

The "remove to tag" feature from the [Move Tags to YAML](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#move-tags-to-yaml) section destroy the YAML format when :
- there is a #tag in the first line, first letter of the md document AND there is a space after this tag.
- there is a #tag just after the YAML section, first line and first letter too AND there is a space after this tag.

I have several options in the YAML section enabled, see joined config :
[configObsidianLinter.txt](https://github.com/platers/obsidian-linter/files/10327740/configObsidianLinter.txt)

## How to Reproduce

Before lint :

```
---
some YAML
---
#tag-error 

```

After lint :

```
---
title: test
date: 2022-12-31
edit: 2022-12-31
---
---
title:
aliases:
notetype:
date:
edit:
tags: tag-error
--- 

```

When I disable the "remove to tag" feature, the bug disappear, but it may be a conflict with other parameters.

## Expected Behavior

The YAML should not be duplicated.

## Screenshots

After the lint on Obsidian :
![after-linter](https://user-images.githubusercontent.com/88883564/210151440-ad890d8a-1c72-4b0c-b6bd-9d54dccde3b1.JPG)

## Device

- [x] Desktop (Windows)
- [ ] Mobile (dunno)

Thanks in advance, and thanks for this beautiful plugin !

(hope this issue wasn’t already reported, didn’t see anything with the "tag" search. 🤞)

**Comment by pjkaufman** [comment] 2023-01-13 23:43
Hey @yazae , I am not currenlty able to reproduce this issue. Could you provide me with your `data.json` for the Linter, so that I can try to reproduce with the exact rule set that you have.

**Comment by yazae** [comment] 2023-01-14 00:34
Hi !
I have already copy/pasted the data in the [configObsidianLinter.txt](https://github.com/platers/obsidian-linter/files/10327740/configObsidianLinter.txt) above, if I’m not mistaken :)

**Comment by pjkaufman** [comment] 2023-01-14 00:44
Ah. You are right. I missed it when looking at all of the bugs that piled up when I was out.

**Comment by pjkaufman** [comment] 2023-01-23 23:23
Looks like it requires the use of both `Yaml Title` and `Move Tag to Yaml`. I am looking into why that is.

**Comment by pjkaufman** [comment] 2023-01-23 23:37
The problem seems to be that `Move Tag to Yaml` is leaving whitespace on the same line as the yaml frontmatter making it so that the regex used does not recognize it as yaml frontmatter. Thus I need to figure out how to prevent that whitespace from moving onto the same line as the frontmatter.

**Comment by pjkaufman** [comment] 2023-01-23 23:56
I believe I have a fix. I am pushing it up and hopefully it will resolved this issue as I can no longer reproduce the issue.

**Comment by pjkaufman** [comment] 2023-01-24 00:05
The change has been merged. I plan to create a release tonight which should include the fix. If master or the next release do not fix the issue, please let us know.

**Closed** 2023-01-24 00:04 UTC
Labels: bug, yaml, obsidian

**Comment by yazae** [comment] 2023-01-24 02:45
Thanks it’s awesome !

Yeah I will retry and tell you when I update :)
