### ISSUE TITLE
Bug: A Comma Followed by Numbers is Removed on Paste

### ISSUE THREAD

**Issue by zhl111** [platers/obsidian-linter#814] opened 2023-07-21 05:31 UTC
When I was copying a piece of text, I occasionally found that some numbers disappeared (I didn't check whether other text would be lost). When I closed the plugin, the missing numbers came back, so I initially thought it was our plugin that caused the loss。

Even copying and pasting in Obsidian is lost!

This is the original text
![image](https://github.com/platers/obsidian-linter/assets/29135984/3478d38c-05eb-40ec-ab00-3bbbc3acf8be)

This is the text that was copied and pasted
![image](https://github.com/platers/obsidian-linter/assets/29135984/ef87d60f-b757-4a38-8227-0b14d29e4f53)

This is the text:
曾几何时,不能工作的老年人要么依靠家人照料,要么一无所有——后者是非常可怕的前景。一个世纪前,65岁以上的美国男性有58%仍参与劳动力市场:要么如此,要么成为孩子的负担,要么挨饿。这并不是一个很好的状态。但是我们现在拥有的却非常奇怪:大规模的消费养老基金使我们的整个成年生活都成为老年的前奏。你工作三四五十年,全部的目的就是为了享受从退休到死亡之间那几年简短、无用的时光。不仅如此,全世界的人现在都在努力增加你的养老基金的价值,甚至印度的煤矿工人,巴西的缝纫工,以及所有其他没有自己养老金的亿万人。整个全球经济现在都是生产满意的退休者的机器。资本主义在过去四百年盲目运转,除了自身之外别无其他目的,现在终于找到了它的目的。

**Comment by pjkaufman** [comment] 2023-07-21 10:50
@zhl111 , this is not a bug. This is how `remove-leftover-footnotes-from-quote-on-paste` works. It is seeing the `,65` as a leftover footnote reference which is expected. I would recommend turning that off if you do not want commas or periods followed by any number of digits removed on paste.

See [here](https://platers.github.io/obsidian-linter/settings/paste-rules/#remove-leftover-footnotes-from-quote-on-paste) for an example showing this happening.

**Comment by pjkaufman** [comment] 2023-07-21 10:52
If you know there are no footnote references in the text in question and you want to paste the text as is without the Linter formatting it and you want to keep `remove-leftover-footnotes-from-quote-on-paste`, use the command to paste as plaintext without modification.

**Comment by pjkaufman** [comment] 2023-07-23 17:21
Hey @zhl111 , I plan to close this issue Wednesday barring any feedback around this since this is intended functionality and the workarounds are

1. Paste the text using the Linter's command to paste without linting the text
2. Disabling `remove-leftover-footnotes-from-quote-on-paste` which is removing that number

**Closed** 2023-07-27 12:42 UTC
