### ISSUE TITLE
Bug: forbidden character combinations while copy & pasting the text of a website to a note

### ISSUE THREAD

**Issue by merlinuwe** [platers/obsidian-linter#1068] opened 2024-04-06 21:03 UTC
I have this note:

![image](https://github.com/platers/obsidian-linter/assets/4138869/6953d532-e720-45d1-9b3b-6a5300e2fdf7)

with this markdown:

```

---
aliases: [avm, Fritz, Fritzbox, AX, Router, ntp, timeserver]
tags: [avm, FritzBox, Fritz, AX, Router, privat, account, ntp, timeserver, Zeitserver, Braunschweig]
filename: muell-Linter
erstellt: Donnerstag, 22. Februar 2024, 10:24:46 Uhr
geändert: Samstag, 06. April 2024, 22:48:11 Uhr
---

`

#`

```

If I linter it, the first "[" after "tags:" is deleted and at the end there is a ", `" instead of a "]":

![image](https://github.com/platers/obsidian-linter/assets/4138869/8f75f0ba-7e8f-4fb0-8b5e-b6727b6ff8e5)

[muell-Linter.md](https://github.com/platers/obsidian-linter/files/14894965/muell-Linter.md)

This causes after lintering again this error message:

![image](https://github.com/platers/obsidian-linter/assets/4138869/2fd60b46-540d-4304-b84d-13eed7bfefa7)

(Background: I copied the text part of this website https://www.cyberciti.biz/faq/linux-unix-bsd-is-ntp-client-working/ and pasted it into a note. This error occured, but I've narrowed it down.)

It would be nice, if your linter plugin could recognize issues like this and repair them.

**Comment by pjkaufman** [comment] 2024-04-07 23:00
Hey @merlinuwe . I am having a bit of trouble understanding exactly what happened here. I have some speculation around this which leads me to believe this a bug with [move tags to frontamatter](https://platers.github.io/obsidian-linter/settings/yaml-rules/#move-tags-to-yaml). I am guessing this rule is enable and it assuming that `#\`` is a tag (that would be a regex fix to fix that issue if it is causing the issue). The tag array type is probably what is causing the removal of  `]` and `]` which is valid in Obsidian, but not elsewhere).

However I am not sure if that is the case. Could you provide your `data.json` or confirm that disabling that rule fixes the problem? If it is caused by that I can probably fix it pretty easily by adding `\`` to the list of invalid tag characters.

**Comment by merlinuwe** [comment] 2024-04-08 15:54
Sure, here is the file.

[data.json](https://github.com/platers/obsidian-linter/files/14907983/data.json)

**Comment by pjkaufman** [comment] 2024-04-22 00:58
Sorry about the delay. I believe I have a fix for this issue.

**Comment by pjkaufman** [comment] 2024-04-22 01:19
The changes for this should now be on master and should go out with the next release. Please let us know if either is not the case.

**Closed** 2024-04-22 01:19 UTC
Labels: bug
