### ISSUE TITLE
Bug: Can't insert new line with Custom Regex replacement

### ISSUE THREAD

**Issue by jeansordes** [platers/obsidian-linter#524] opened 2022-12-01 10:53 UTC
## Describe the Bug / how to reproduce / Expected Behavior
If I put `\n` in the `regex to replace` field, it puts a literal `\n` in the file instead of putting a newline

![image](https://user-images.githubusercontent.com/18046171/205034420-a8b7dcbe-45aa-4342-98d6-df25052fe452.png)
```
test
```
becomes
![image](https://user-images.githubusercontent.com/18046171/205036713-491898de-9a3c-4ece-8402-132c1eb73d33.png)

## Device
- [x] Desktop
- [x] Mobile

**Comment by pjkaufman** [comment] 2022-12-01 11:33
Thanks for reporting this. I will see about regex escaping the replace value. Hopefully that will fix the issue.

**Comment by pjkaufman** [comment] 2022-12-02 18:43
This is a bit perplexing. I am running into some issues with try to actually fix this. For some reason a variable value and the exact string `\n` are not being treated the same. I will reach out to other devs to see what they think about this and see if they have any suggested solutions.

**Comment by pjkaufman** [comment] 2022-12-02 18:53
I think I actually have a solution. The problem is `\n` is being saved as `\\n` since that is how the UI is interpreting it. Thus I need to convert `\\` into `\`.

**Comment by pjkaufman** [comment] 2022-12-02 18:57
It seems that that is not the case. I will proceed with asking the dev community if they have any idea what is going on here.

**Comment by pjkaufman** [comment] 2022-12-02 21:20
They gave a good suggestion and now I have a fix for the issue pretty much ready.

**Comment by pjkaufman** [comment] 2022-12-02 21:27
This should be fixed on master and in the next release. Please let us know if that is not the case.

**Closed** 2022-12-02 21:27 UTC
Labels: bug
