### ISSUE TITLE
Bug: File system operation  timed out.

### ISSUE THREAD

**Issue by grantx2016** [platers/obsidian-linter#592] opened 2023-01-19 04:12 UTC
## Describe the Bug

When I run linter over a folder tree containing a few thousand notes I am now getting some "File system operation timed out" errors for seemingly random files. Apart from failing, they also slow down the linting operation substantially. The files that fail can be successfully linted using exactly the same rules when they are linted one file at a time afterwards.

Specifically, the common error message for all failures is as follows:

```
Error File system operation timed out.
Error: File system operation timed out.
    at e.kill (app://obsidian.md/app.js:1:1093712)
    at s (app://obsidian.md/app.js:1:702707)
    at l (app://obsidian.md/app.js:1:702813)
oc @ plugin:obsidian-linter:69
handleLintError @ plugin:obsidian-linter:2371
eval @ plugin:obsidian-linter:2365
```

## How to Reproduce

- Right click on folder and lint. 

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run. >
- [ ] Attempting to capture logs without success as logs are not being written by the plugin even though it is set to log "Errors". I will keep trying.
- [x] `data.json` file attached:
[data.json.zip](https://github.com/platers/obsidian-linter/files/10453476/data.json.zip)

## Expected Behavior

No errors.

## Screenshots

A sample of the errors taken from the dev console follow:

![Screenshot 2023-01-19 at 8 54 45 am](https://user-images.githubusercontent.com/19563571/213353086-e8a8d9bd-2db9-43a2-a814-f430d5513a79.png)

## Device

- [x] Desktop: macOS Ventura 13.1 running Obsidian Version 1.1.9 (Installer 1.1.9)

## Additional Context

I have had no such issues previously when running the linter plugin over the same vault.

**Comment by pjkaufman** [comment] 2023-01-19 12:50
It seems to not be running on valid files since the file name is made up of whitespace in the error message. Is this consistently reproducible? If so, are you able to determine exactly which files have this problem? The output here implies the files were named incorrectly and that caused the issue, but it could be a bug in how the file name is parsed out for use.

**Comment by grantx2016** [comment] 2023-01-19 23:35
> If so, are you able to determine exactly which files have this problem?

I have been able to reproduce the issue with the attached test data.
[Linter-Plugin-Issue-Reproduction.zip](https://github.com/platers/obsidian-linter/files/10461958/Linter-Plugin-Issue-Reproduction.zip)

There are two files contained in the folder when unzipped:
1. `File1-NoAttach`: This is a simple markdown file with no attachments. It's one of the files that failed in the screenshots previously provided.
2. `File2-BrokenLinks`: This markdown file contains broken links (e.g. to a file `transparent.gif') and seems to be the cause of the linter errors.

My observations:
1. If you lint the folder containing the two files, the error in the chrome dev console identifies `File1-NoAttach`.
2. If you delete `File2-BrokenLinks` and lint the folder then linter successfully completes immediately without error on remaining file `File1-NoAttach`.
3. If you delete `File1-NoAttach` and lint the folder then linter eventually successfully completes on remaining file `File2-BrokenLInks`, but after a much longer time. 

I have no idea what is going on here other than the file with the broken links seems to cause linter to stall, preventing linting of the file that can be linted individually with no issue (`File1-NoAttach`) and the error misleadingly being associated with the good file  (`File1-NoAttach`) rather than the one causing the issue (`File2-BrokenLinks`).

Hopefully something here helps to identify the bug.

**Comment by pjkaufman** [comment] 2023-01-27 19:40
I will take a look at this soon hopefully. With the zip file I will hopefully be able to reproduce this locally for me.

**Comment by pjkaufman** [comment] 2023-02-02 00:01
It is odd. I am not able to reproduce the issue in question. It may be that there was a bug, but I am not able to confirm that there is one.

What I tried:
- I replaced my `data.json` with the one provided on this ticket
- Went ahead and copied the folder in question into the vault
- Reloaded the Linter plugin to make sure that the config got updated
- Ran lint folder to see if any errors popped up (none were displayed)
- Recopied over the folder contents and verified that linting each individual had no issue either
- Recopied over folder contents and restarted Obsidian before linting the folder again (no issues with this run either)

It could be that this is OS specific, but that would be odd if it were. I am going to note that this may still be an issue. If this issue persists after the next release, please let me know, @grantx2016 . If it does I may have to put this as a ticket I need help from other devs on as I don't own a Mac.

**Comment by grantx2016** [comment] 2023-02-02 01:06
> please let me know, @grantx2016

Will do. Thanks for investigating. I'll update you with any further observations as they may occur.

**Comment by pjkaufman** [comment] 2023-03-18 01:32
Is this issue still happening for you @grantx2016 ? I am still not able to reproduce and want to check if you are still encountering this issue as I move through the bug backlog for the Linter.

**Comment by grantx2016** [comment] 2023-03-22 00:09
> Is this issue still happening for you @grantx2016 ? I am still not able to reproduce and want to check if you are still encountering this issue as I move through the bug backlog for the Linter.

I have tested again with the test data I provided and that is not producing the issue anymore. However, I do note that I am still observing similar behaviour when linting large folders ie. I often get one file that times out and slows down the linting but find that it can be successfully linted  in isolation afterwards. 

I think you can close this out as it seems to be an edge case and not worth wasting time on. I also expect it to be less likely to recur as I have now at least managed to get one successful pass of linting completed on my 40+K of notes.

**Comment by pjkaufman** [comment] 2023-03-28 23:32
I am closing this as per the last comment.

**Closed by pjkaufman** 2023-03-28 23:32 UTC
Labels: bug, unable-to-reproduce
