### ISSUE TITLE
Bug: every lint will add a empty line before/after code fence. lint twice it will add two empty line, 3 will be 3 empty line. 

### ISSUE THREAD

**Issue by wuzhizhi22** [platers/obsidian-linter#448] opened 2022-10-10 11:47 UTC
## How to Reproduce

Or

Example to reproduce issue with

``` markdown
example here
```

Please make sure to include the rule(s) that cause the issue if applicable. If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/`.

## Expected Behavior

Expected output if applicable:

``` markdown
expected output here
```

## Device

- [ ] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2022-10-10 12:12
Thanks for reporting this @wuzhizhi22 ! Could you provide an example of a code block having the issue?

**Comment by pjkaufman** [comment] 2022-10-10 12:38
Without the example, I am currently unable to reproduce this issue. So a reproducible example, would be very helpful.

**Comment by pjkaufman** [comment] 2022-10-15 01:13
@wuzhizhi22 , by chance could you provide a reproducible example? Without one, I will be forced to close this issue as I cannot reproduce the problem.

**Comment by pjkaufman** [comment] 2022-10-20 09:02
I have not gotten any response on how to reproduce this, so I am unable to do anything about the issue. As such, I am going to go ahead and close this. Feel free to reopen this if you have a reproducible example.

**Closed by pjkaufman** 2022-10-20 09:02 UTC
Labels: bug, question
