### ISSUE TITLE
[BUG] remove-multiple-spaces inconsistent...

### ISSUE THREAD

**Issue by olearydj** [platers/obsidian-linter#226] opened 2022-06-12 23:59 UTC
I commonly see Linter leave multiple spaces after punctuation, and sometimes before:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/42705243/173258829-4aac4451-e2f2-4e65-af05-f0721d3ce108.png">

possibly relevant configuration items:
remove-multiple-spaces ON
remove-trailing-spaces ON
two space linebreak ON
space between Chinese and English or numbers OFF

**Comment by pjkaufman** [comment] 2022-06-13 01:42
@olearydj , could you paste some text here in this thread that is having the issue? That will greatly improve my chances of reproducing the issue.

The data.json for the obsidian-linter plugin would also help greatly.

**Comment by pjkaufman** [comment] 2022-06-13 09:11
I could be wrong, but in the image above, all highlighted whitespace looks to be a single space, but maybe that is just due to the image itself. If I had a text block, I should know for certain.

**Comment by olearydj** [comment] 2022-06-13 12:05
Those are definitely 2 spaces, but yes it is hard to see. I used search to find all occurrences of "  ".
I've attached the original MD file for you to test:
[Advantages of AR in Architecture, Engineering, and Construction.md](https://github.com/platers/obsidian-linter/files/8890833/Advantages.of.AR.in.Architecture.Engineering.and.Construction.md)

**Comment by pjkaufman** [comment] 2022-06-14 00:39
I seem to be able to reproduce the issue. I need to tinker with it a little and see what is going on. I hope to have a fix later on this week.

**Comment by pjkaufman** [comment] 2022-06-14 00:49
Well, after a little tinkering. I think I have a fix. For some reason, the regex we are currently using seems to think that two spaces after some non-letter results in it being weird. I will see about adding a test for that and then pushing up what I believe is the fix.

**Comment by pjkaufman** [comment] 2022-06-14 01:43
It seems my initial idea was not quite accurate. I am looking into a better longterm solution.

**Comment by pjkaufman** [comment] 2022-06-14 02:36
Ok. I was overthinking the issue. I have a fix now and it should be merged into master before the end of the day.

**Closed** 2022-06-14 02:42 UTC
Labels: bug, markdown

**Comment by pjkaufman** [comment] 2022-06-14 02:44
The issue should be fixed with the latest. Please let me know if that is not the case. It should be released in the next two weeks if you are not able to use the current master branch directly.

**Comment by olearydj** [comment] 2022-06-16 13:37
Many thanks! I look forward to the update.
