### ISSUE TITLE
FR: Time based lint

### ISSUE THREAD

**Issue by kangruixiang** [platers/obsidian-linter#754] opened 2023-06-08 17:29 UTC
## Is Your Feature Request Related to a Problem? Please Describe.

Currently, linting a file is activated upon saving a file. Although it doesn't take that much to hit the commands to save, having to do that for every file adds up. Sometimes I'm not sure if I have linted a file or not, and it's always in the back of my mind to keep hitting Ctrl+S or having to lint the whole vault from time to time.

## Describe the Solution You'd Like

Add an option to add automatic linting of currently open file with a timer.

**Comment by pjkaufman** [comment] 2023-06-08 17:33
Hey @kangruixiang . Does linting on file autosave tackle this scenario (#392 )?

**Comment by kangruixiang** [comment] 2023-07-11 12:26
> Hey @kangruixiang . Does linting on file autosave tackle this scenario (#392 )?

Hi looks like issue #188 is very similar. Seems like we haven't reached a solution yet. 

Thanks.

**Comment by pjkaufman** [comment] 2023-07-11 12:40
No problem. I tried a solution for this last week, but it ran into an issue where it could cause an infinite loop due to the way it was written.

**Comment by pjkaufman** [comment] 2023-07-14 16:44
@kangruixiang , I just merged in a change for when a file is closed or you swap to a new file the file that is closed or the previous file gets linted. I am not sure if that addresses your FR fully, but it will go out with the next release in a couple of weeks.

**Comment by pjkaufman** [comment] 2023-07-14 16:48
I do believe that this is a duplicate of #183 though. So I do plan to close this Sunday in favor of #183 .

**Closed** 2023-07-24 19:47 UTC
Labels: rule suggestion
