### ISSUE TITLE
FR: Capitalize Headings, The words in the Lowercase words list to be Uppercase when it is the first letter

### ISSUE THREAD

**Issue by Liong1976** [platers/obsidian-linter#171] opened 2022-02-16 17:32 UTC
I want to request that for the function of `Capitalize Headings`, the words listed in `the Lowercase Words` better be uppercase when it is the first letter.

For example:
## the Best of the Best 

should be
## The Best of the Best

Thanks!

**Comment by pjkaufman** [comment] 2022-05-20 18:17
This sounds more like a bug than a feature. Let me see if this issue is currently happening for me locally.

**Comment by pjkaufman** [comment] 2022-05-20 18:20
@Liong1976 , could you provide your data.json to allow me to determine what settings you have on for capitalization? This will help in the case that I cannot find the issue.

**Comment by pjkaufman** [comment] 2022-05-20 18:24
I currently am not able to reproduce this, but I may be following the wrong steps to do so.

**Comment by Liong1976** [comment] 2022-05-20 22:30
I just realized that the plugin works well regarding this issue. It is an issue for me because I use the `Number Heading` plugin. The number before the header's first letter causes that letter to become the lower case.

Here is a screenshot without a number heading.
![image](https://user-images.githubusercontent.com/88898230/169620300-c9540df9-2cd6-4a3d-9331-ee5001dc219b.png)

Here is a screenshot with a number heading.
![image](https://user-images.githubusercontent.com/88898230/169620363-bd8c88e8-1bf0-438d-95e8-f4da657ba4a6.png)

So, my request is that the words listed in `the Lowercase Words` better be uppercase when it is the first letter after heading numbers. Thanks!

**Comment by pjkaufman** [comment] 2022-05-25 01:38
@Liong1976 , please feel free to take a look and see if the issue is fixed via the master branch of the repo.

**Comment by Liong1976** [comment] 2022-05-26 12:50
Hi @pjkaufman, thank you for the fix. How to try the fixed plugin since the update is not released yet? Sorry, I no nothing about coding.

**Comment by platers** [comment] 2022-05-26 17:49
Yeah, the changes are not released yet. @pjkaufman feel free to create a release whenever you feel like it. I usually do it every 2 weeks, or after a big change. 

To release, bump the version number in the manifest, create a new release and tag on github, and upload the main.js and manifest.json files to the release.

**Comment by pjkaufman** [comment] 2022-05-26 18:47
Sounds good. I will look into creating a release this weekend.

**Comment by pjkaufman** [comment] 2022-05-29 17:59
@Liong1976 , I have created a new release. It should have the changes for this fix.

**Comment by Liong1976** [comment] 2022-05-29 18:03
Hi @pjkaufman,
Thanks for the release. Unfortunately, it still doesn't work.

This is what I got after linting the file.

![image](https://user-images.githubusercontent.com/88898230/170884857-03a80ebb-e961-4619-8ce1-a1690800f950.png)

**Comment by pjkaufman** [comment] 2022-05-29 18:37
@Liong1976 , which style are you using for capitalize headings? I thought you were using "First Letter".

**Comment by pjkaufman** [comment] 2022-05-29 22:13
It looks like I fixed it for first letter, but not the first word when doing title case. I will fix that and hopefully, we can have that go out with the next release.

**Closed** 2022-05-29 22:24 UTC

**Comment by Liong1976** [comment] 2022-06-04 22:52
Thanks, @pjkaufman!

**Comment by Liong1976** [comment] 2022-06-10 22:50
Yes, it is working! Thanks, @pjkaufman
