### ISSUE TITLE
Bug: Inline comment ending a line prevents ignoring of multiline comment later in file

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [platers/obsidian-linter#300] opened 2022-07-17 19:13 UTC
## Describe the Bug

This is related to #223 and #269 and is a minimal repro of the issue I was commenting on at the bottom of #223. Multiline comments are not successfully ignored if an inline comment earlier in the file ends a line. Putting a space between inline comment and linebreak does not fix this, putting text between does.

## How to Reproduce
Set "paragraph blank lines" rule on OR set "two spaces between lines with content" on. (Not both.)

``` markdown
%% fold %%

## R

%%
HW:: --
T:: 0
%%

```

## Expected Behavior
Linter output for the bottom of the file (starting `## R`) should be the same as if the input was:

``` markdown
%% fold %% notComment

## R

%%
HW:: --
T:: 0
%%

```

## Device

- [x] Desktop

Note: The file initially had a second multiline block comment above the inline comment which was successfully ignored by both "paragraph blank lines" and "two spaces between lines with content" rules.

**Comment by pjkaufman** [comment] 2022-07-17 20:20
Thanks for tracking the cause down. I think I have an easy fix for this. I will let you know once I get a chance to test it out. I am pretty sure all I need to do is specify that the starting perctange signs have to start the line to match the regex and it will be good to go.

**Comment by pjkaufman** [comment] 2022-07-18 04:20
I have a fix in place for the above, but I am guessing I should see about being a little more thorough on ignoring obsidian multiline comments. At this time, obsidian single line comments are not ignore by the linter.

I am guessing the following scenarios would need modification to make sure they do not cause issues:
- obsidian multiline comment in the middle of a paragraph (likely gets 2 spaces tacked on at the end if not the last line in paragraph or gets a blank line before and after it)
- Obsidian multiline at the end of a paragraph will cause the previous line to get 2 spaces on despite it being followed by a comment
- Obsidian multiline at the start of a paragraph with more than 1 line will likely get 2 spaces at the end of it and a blank line before and after it despite not counting as paragraph content

Do you think these need fixing @AnnaKornfeldSimpson ?

Thanks for all of the feedback and help pointing out issues.

**Comment by pjkaufman** [comment] 2022-07-25 02:45
This issue should be resolved on master. Please let us know if this is not resolved on master or in the next release.

**Closed** 2022-07-25 02:44 UTC
Labels: bug, obsidian
