### ISSUE TITLE
Bug: Date Format not working with property type Date & Time

### ISSUE THREAD

**Issue by sinhaaritro** [platers/obsidian-linter#944] opened 2023-11-11 03:51 UTC
- [X] I have verified that I am on the latest version of the Linter 

## Describe the Bug

I am using Linter to add the timestamp of the Date Created and the Date Modified. The date format used is DD-MM-YYYY hh:mm A. The date added by the linter based on the format is correct when the property type is Text, the format is not correct when the property type is Date & Time.

(Linter Version: 1.20.1)

## How to Reproduce

1. Created a new vault
2. Added **Linter** plugin
3. Changed the date format on the linter 
4. Create a new note
5. Lint the file (after this the dates are correct)
6. Change the property type of **date created** to **Date & Time**

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run.

```
Running linter
Running Move Math Block Indicators to Their Own Line
move-math-block-indicators-to-their-own-line: 1.199999999254942 ms
---
date created: 11-11-2023 08:14 AM
---

rules before regular rules: 1.3999999994412065 ms
Running Headings Start Line
headings-start-line: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Convert Bullet List Markers
convert-bullet-list-markers: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Ordered List Style
ordered-list-style: 0.2999999998137355 ms
---
date created: 11-11-2023 08:14 AM
---

Running Remove Hyphenated Line Breaks
remove-hyphenated-line-breaks: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Remove Multiple Spaces
remove-multiple-spaces: 0.30000000074505806 ms
---
date created: 11-11-2023 08:14 AM
---

Running Strong Style
strong-style: 0.19999999925494194 ms
---
date created: 11-11-2023 08:14 AM
---

Running Compact YAML
compact-yaml: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Consecutive blank lines
consecutive-blank-lines: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Convert Spaces to Tabs
convert-spaces-to-tabs: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Empty Line Around Code Fences
empty-line-around-code-fences: 0 ms
---
date created: 11-11-2023 08:14 AM
---

Running Empty Line Around Tables
empty-line-around-tables: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Remove Empty Lines Between List Markers and Checklists
remove-empty-lines-between-list-markers-and-checklists: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Remove link spacing
remove-link-spacing: 0 ms
---
date created: 11-11-2023 08:14 AM
---

Running Remove Space around Characters
remove-space-around-characters: 0.20000000018626451 ms
---
date created: 11-11-2023 08:14 AM
---

Running Trailing spaces
trailing-spaces: 0.2999999998137355 ms
---
date created: 11-11-2023 08:14 AM
---

Running Custom Regex
custom regex rules: 0.09999999962747097 ms
Running Blockquote Style
blockquote-style: 0.10000000055879354 ms
---
date created: 11-11-2023 08:14 AM
---

Running YAML Timestamp
yaml-timestamp: 0.599999999627471 ms
---
date created: 11-11-2023 08:14 AM
date modified: 11-11-2023 09:16 AM
---

rules after regular rules: 1 ms
rules running: 6.5 ms
Running Custom Lint Commands
```

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

[data.json](https://github.com/platers/obsidian-linter/files/13324317/data.json)

## Expected Behavior

Expected output if applicable:

![image](https://github.com/platers/obsidian-linter/assets/34037263/7065d062-3fb8-4f03-9c71-26fd4f17ca0b)

## Screenshots

The below is the wrong format
![Screenshot 2023-11-11 091042](https://github.com/platers/obsidian-linter/assets/34037263/87672014-66f1-404a-a62b-990b077f4ed4)

## Device

- [X] Desktop
- [ ] Mobile

## Additional Context

Date in source mode is correct
![image](https://github.com/platers/obsidian-linter/assets/34037263/f5d09b8b-b4a1-496c-9a48-55f640a75a5c)

**Comment by pjkaufman** [comment] 2023-11-12 17:49
Hey @sinhaaritro , I am not sure that I can reproduce this issue. Are you on the latest version of Obsidian? I ask because last time I saw this issue reported it was fixed after an Obsidian update.

Here is the version I am on and am not seeing the issue mentioned:
Obsidian v1.4.16
Installer v1.4.16

_Note that the installer and Obsidian version do matter_

If this issue still exists on the versions I listed above, please provide your `data.json` and I can try again to reproduce this issue. Thanks!

**Comment by sinhaaritro** [comment] 2023-11-13 15:12
Hi, I have checked that the installer and obsidian version are v1.4.16 and the issue is still present.
I have added the repo (in Github) that I was using to test what was wrong with my dates. 
https://github.com/sinhaaritro/obsidian-lint-date

The Untitled note has the problem: the date shown in source mode differs from in read mode.

_I don't know about the internals of Obsidisn or Obsidian Linter, but to me, it looks like the date generated by Linter is correct (because in source mode it is correct). The problem happens when Obsidian.md parses the date in the Date and Time property. So the fix can probably be done by Obsidian.md_

**Comment by pjkaufman** [comment] 2023-11-13 15:57
Thanks! I will have to see about taking a look at this to see what is going on with this to see if I can reproduce once I pull it down, If not, I am not sure what the next steps would be. But let's hope it does not come down to that.

**Comment by pjkaufman** [comment] 2023-12-05 01:12
Hey @sinhaaritro . I took a look at the repo that you put out there. I could not reproduce the issues with the Untitled note. However for some reason when I linted the the original timestamp note it really mangled the values for the date times. Something inserted dates. This seems to have thrown the Linter into confusion when it was updating the values. However I could not reproduce this issue in source mode. I will have to reach out on the discord for Obsidian and possibly add an issue on the Obsidian forums to get feedback around what might be causing the issue.

I have an idea on how to fix these issues with live preview, but I am not too fond of it since it would requiring forcing an update of the entire file despite knowing what should be updated. It would likely cause other issues as well.

**Comment by pjkaufman** [comment] 2023-12-05 13:12
I may have a fix for this issue, but I am not certain it fixes all scenarios like this. There was an issue with Live Preview not working like Source Mode, so I had to change the save logic to update things all in one go. This may fix the issue and I can put the `main.js` on this issue if you want to test it out and see if it fixes your situation as well. I plan to get feedback from as many people experiencing the live preview issue as possible. Assuming all goes well, it will fix the issues seen there and go out in the next release.

**Comment by pjkaufman** [comment] 2023-12-08 21:21
I believe I have a fix for this that has just been merged in. The changes should be in the next release and on master. Please let us know if either master or the next release has issues.

**Closed by pjkaufman** 2023-12-08 21:21 UTC
Labels: bug, help wanted, live-preview
