### ISSUE TITLE
FR: Add Blank Rows Above and Below Tables

### ISSUE THREAD

**Issue by yanwanchen720** [platers/obsidian-linter#194] opened 2022-04-29 01:00 UTC
want to add a blank row above and below the table
![image](https://user-images.githubusercontent.com/72399630/165870404-9d269ec5-6c76-4d24-b32c-8176ccedbe90.png)

**Comment by pjkaufman** [comment] 2022-06-12 09:09
This is currently a work in progress. I hit a bit of a snag when testing this and found that when a header was in between two tables it was not appropriately finding tables. I am waiting on an answer as to whether the issue is on my end or if there is a bug in `remark-gfm`: https://github.com/remarkjs/remark/discussions/1003

**Comment by pjkaufman** [comment] 2022-07-11 00:45
I think the following regex should work for identifying tables: `([ ]{0,3}\[.*?\][ \t]*\n)?([ ]{0,3}\S+.*?\|.*?\n([^\n]*?\|[^\n]*?\n)*?)?[ ]{0,3}[\|\-\+\:\.][ \-\+\|\:\.]*?\|[ \-\+\|\:\.]*(?:\n?[^\n]*?\|[^\n]*?\n)+` it may need some tweaking down the road, but hopefully the issue with the markdown parser gets fixed by then.

**Closed** 2022-07-11 02:25 UTC
Labels: rule suggestion, markdown

**Comment by pjkaufman** [comment] 2022-07-11 02:26
This request should be added now. Please let us know if for some reason this issue still exists on the master branch or in the next release.
