### ISSUE TITLE
bug with no-bare-urls

### ISSUE THREAD

**Issue by berot3** [platers/obsidian-linter#228] opened 2022-06-14 12:19 UTC
I lint on save, and every time I press save, it adds additional "<>" to bare urls (#222 )

so this:
`https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#no-bare-urls`

looks after view saves/lints like this:
`<<<<https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#no-bare-urls>>>>`

help?

**Comment by pjkaufman** [comment] 2022-06-14 13:57
Gotcha. I think I know what the issue is. I will add that to the set of characters that cannot surround it in order to add to it this evening.

**Comment by MichaBrugger** [comment] 2022-06-14 17:27
noticed it in my own files and made a quick PR (adds "<" and ">" to the list of excluded characters) 👍🏼

**Comment by pjkaufman** [comment] 2022-06-14 18:32
Thanks @MichaBrugger for the PR! I made a couple of adjustments for testing purposes and to make sure there were not any edge cases, but other than that it looks great! I believe that it fixes the issue and it has now been merged. Please let me know if using the current master branch does continue to cause this issue. Thanks again for the help and for reporting the issue!

**Closed** 2022-06-14 18:33 UTC
Labels: bug, markdown
