### ISSUE TITLE
Bug: Empty Line Around Tables not respected

### ISSUE THREAD

**Issue by icebruce** [platers/obsidian-linter#751] opened 2023-06-05 00:37 UTC
## Describe the Bug

"Empty Line Around Tables" option is enabled in Linter  but when the command is ran it removes all empty lines between a Header and the table

## How to Reproduce

1. Enable "Empty Line Around Tables"
2. In a document (not beginning or end) create a H2, create an empty line and add a table after the header
3. Run Linter
4. Empty line between H2 and table is removed and table is not rendered properly

Example to reproduce issue with

``` markdown
## Logical operators

| Operator | Meaning                  | Example               |
|----------|--------------------------|-----------------------|
|`==`| Is Equal To              | 3 == 5 gives us False |
|`!=`| Not Equal To             | 3 != 5 gives us True  |
|`>`| Greater Than             | 3 > 5 gives us False  |
|`<` | Less Than                | 3 < 5 gives us True   |
|`>=`| Greater Than or Equal To | 3 >= 5 give us False  |
|`<=`|Less Than or Equal To|3 <= 5 gives us True |
```

#### Log
Running linter
Running Format Tags in YAML
Running Format Yaml Array
Running Move Tags to Yaml
Running Remove Trailing Punctuation in Heading
Running Convert Bullet List Markers
Running Remove Consecutive List Markers
Running Remove Empty List Markers
Running Remove Hyphenated Line Breaks
Running Remove Multiple Spaces
Running Two Spaces Between Lines with Content
Running Compact YAML
Running Consecutive blank lines
Running Empty Line Around Blockquotes
Running Empty Line Around Code Fences
Running Empty Line Around Math Blocks
Running Empty Line Around Tables
Running Heading blank lines
Running Remove Empty Lines Between List Markers and Checklists
Running Remove link spacing
Running Space after list markers
Running Trailing spaces
Running Custom Regex
Running Capitalize Headings
Running Custom Lint Commands

## Expected Behavior
There should be one empty line between the H2 and the table

## Screenshots

Before
![image](https://github.com/platers/obsidian-linter/assets/66655064/df5099aa-ed76-4944-b33a-92f78ce739ed)

After
![image](https://github.com/platers/obsidian-linter/assets/66655064/7ab67e9d-1cd5-44dc-a180-869e968b3a1d)

## Device

- [ x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-06-05 01:46
I am not able to reproduce this behavior @icebruce . Could you provide your `data.json` and let me know what version of the Linter you are using?

**Comment by jake-steele** [comment] 2023-06-05 18:51
Not OP, but I can say that I experience this bug as well. I actually came here to post an issue about it!

I am on:
Windows 10 (Version 22H2 19045.2965)
Obsidian 1.3.5
obsidian-linter 1.15.2

The offending section in my notes is that I have an H1 with note title, followed by blank line, followed by table to display created and modified times.

```
# <% tp.file.title %>

|                      Created                      |                      Last Modified                      |
|:-------------------------------------------------:|:-------------------------------------------------------:|
| <% tp.file.creation_date("YYYY-MM-DD @ HH:mm") %> | <%+ tp.file.last_modified_date("YYYY-MM-DD @ HH:mm") %> |

```

When the linter is triggered (on save or otherwise), the empty line between the heading and table is removed.
Disabling the plugin eliminates this behavior.
No settings appear to be relevant to prevent this behavior (or set to act in such a way in the first place).

Below is my data.json for obsidian-linter (renamed w/ .txt extension so GH accepts it)

[data.txt](https://github.com/platers/obsidian-linter/files/11655724/data.txt)

**Comment by pjkaufman** [comment] 2023-06-05 19:02
> Not OP, but I can say that I experience this bug as well. I actually came here to post an issue about it!
> 
> I am on: Windows 10 (Version 22H2 19045.2965) Obsidian 1.3.5 obsidian-linter 1.15.2
> 
> The offending section in my notes is that I have an H1 with note title, followed by blank line, followed by table to display created and modified times.
> 
> ```
> # <% tp.file.title %>
> 
> |                      Created                      |                      Last Modified                      |
> |:-------------------------------------------------:|:-------------------------------------------------------:|
> | <% tp.file.creation_date("YYYY-MM-DD @ HH:mm") %> | <%+ tp.file.last_modified_date("YYYY-MM-DD @ HH:mm") %> |
> ```
> 
> When the linter is triggered (on save or otherwise), the empty line between the heading and table is removed. Disabling the plugin eliminates this behavior. No settings appear to be relevant to prevent this behavior (or set to act in such a way in the first place).
> 
> Below is my data.json for obsidian-linter (renamed w/ .txt extension so GH accepts it)
> 
> [data.txt](https://github.com/platers/obsidian-linter/files/11655724/data.txt)

It could be that it does not recognize the table, but I will have to test this sometime this week.

**Comment by pjkaufman** [comment] 2023-06-05 19:06
Looks like it recognizes the table. Further investigation will be needed to see what is actually going on here. Note that I am not sure what is going on with the templater code since it looks to be invalid: `<%+ tp.file.last_modified_date("YYYY-MM-DD @ HH:mm") %>`, but maybe I am missing something.

**Comment by icebruce** [comment] 2023-06-06 01:21
FYI here's a copy of my settings. Im on version 1.15.2
[data.txt](https://github.com/platers/obsidian-linter/files/11658911/data.txt)

**Comment by qazxcdswe123** [comment] 2023-06-10 03:11
Same issue here, the behaviour is introduced here: https://github.com/platers/obsidian-linter/blob/b89c67d803ac9b27725b9193f73f56d333c16407/src/rules/heading-blank-lines.ts#LL27C7-L27C52

In editing mode the line above the table need to be blank, while in reading mode the table is rendered correctly, not sure if this is intentional or bug from the obsidian side

`text = text.replace(/(^#+\s.*)(\n\|)/gm, '$1\n\n$2');`

this should fix? working on it

**Comment by pjkaufman** [comment] 2023-06-10 21:16
This sounds like an order of operations issue. Based on what has been stated by @qazxcdswe123 . Typically those are fixed by making sure that the rule that should have its results kept in that scenario run last. For example, if we are saying that the empty lines around tables should trump the rule option for removing blank lines after a heading, then the rule to add blank lines around a table needs to be moved to run after the other rules as a special rule in the after section.

**Comment by jake-steele** [comment] 2023-06-12 19:19
I found that setting the Linter > Spacing Settings > Heading Blank Lines' "Bottom" option allows the tables to function as I intended. That said, I would prefer that the spacing after my heading not be changed. Perhaps this could be copied in the regex as `/(^#+\s.*)\n(\n+)/` and replaced as `/$1\n$2/` or the like unless one of the other heading spacing options nullifies this?

(Side-note: I actually had "All headings have a blank line both before and after" enabled, but had "Bottom" disabled. The wording of the former implies that there should be an empty line here anyways from my interpretation.

As it turns out, having the "All headings have ... after" setting on negates the "Empty Line Around Tables" option unless you have "Bottom" enabled in Heading Blank Lines. However, having "All headings have ... after" disabled means that the spacing is undisturbed whether you have "Empty Line Around Tables" enabled or not.)

**Comment by pjkaufman** [comment] 2023-06-12 19:29
Yeah. That is the crux of the problem. Making the empty lines around the table rule run after the rule for heading blank lines should fix the issue code wise.

What currently seems to be happening is as follows:
- Heading Blank Lines has the Option for "Bottom" turned off
  - This removes the blank lines that follow a heading
- Blank lines around tables is enabled
- When the Linter runs, blank lines around tables runs first which ensures 1 blank line around the table
- Then heading blank lines runs and removes blank lines after the heading (i.e. below it)
- Thus the output looks as though the heading blank lines rules are not run at all

**Comment by jake-steele** [comment] 2023-06-12 19:48
Oh, okay. So having the "Bottom" option turned off REMOVES lines? That feels... Wrong. At least according to the description of "Insert a blank line after headings." My interpretation was that the setting, if enabled, would add a line, and would do nothing when disabled.

To avoid all of this confusion, it could be more effective to have the first two "Heading Blank Lines" Linter options be "Blank Lines Before" and "Blank Lines After," each with the dropdown options of "N/A, 0, 1, 2." Where 0, 1, and 2 would force there to be the respective number of blank lines while "N/A" would leave existing spacing alone (barring modification of said spacing by other rules). Then, if there are special cases, they can be listed below those two options and applied afterwards (such as the "Empty Line Between Yaml and Header" option).

The "N/A" option above could obviously be anything else... Maybe "Ignore" is more descriptive of the behavior.

**Comment by pjkaufman** [comment] 2023-06-16 11:09
Based on the description of the rule, for heading blank lines, I am going to remove the logic that affects blank lines after the header if bottom is false. I will just double check that the option was not added in order to remove blank lines. Because if it was not, this is an unintended bug.

**Comment by pjkaufman** [comment] 2023-06-16 11:18
Looks like an old bug: https://github.com/platers/obsidian-linter/pull/9
There is no indication that the intent was to actually trim blank lines after the headings.

**Comment by pjkaufman** [comment] 2023-06-16 11:31
I believe I have a fix for this. I just need to test it out and see how things go.

**Comment by pjkaufman** [comment] 2023-06-16 11:40
I am pushing up a fix and will create a PR.

**Closed** 2023-06-16 11:45 UTC
Labels: bug, markdown, reproducible

**Comment by pjkaufman** [comment] 2023-06-16 11:48
I have pushed up a potential fix for this. It is now on master. So it should go out with the next release. Please let us know if it is not fixed in that release.

The change made was to make it so that `Heading Blank Lines` does not remove multiple blank lines after any heading* when `bottom = false`.

*: There is an exception to this according to the code, but I am not sure how to describe it since I was not around when the rule was written and I currently do not understand its use in the code.

**Comment by jake-steele** [comment] 2023-06-27 03:08
That is excellent news! Thank you so much, @pjkaufman; you're amazing!
This is why I love open source development. :)

I will give it a shot next chance I get and report back. 👍🏻
