### ISSUE TITLE
Bug: After modification and saving, the title folding state of the text will be canceled

### ISSUE THREAD

**Issue by obqrn** [platers/obsidian-linter#1016] opened 2024-02-22 03:00 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

After modification and saving, the title folding state of the text will be canceled

## Device

- [x] Desktop

**Comment by pjkaufman** [comment] 2024-02-22 10:04
I am not sure of a good fix to this. This was fixed by using `editor.replaceRange` (#17 ). But then Live Preview issues came up and `editor.replaceRange` does not work for that. So it seems like there are only 2 options:
1. Do not support folding
2. Only preserve folds in source mode

Which mode are you using?

**Comment by pjkaufman** [comment] 2024-02-22 12:59
Dev note:
We can go back to how things used to be done for Source Mode. However in Live Preview, we either need to force update the full file when things changes as we are forced to do now or we have to compare the YAML contents first and if any of it has changed replace all of the YAML and then do a regular comparison of the remaining file content.

This would retain heading folds. However any YAML folds will get wiped out in Live Preview mode if anything in the YAML changes. But that is the best compromise I can come up with while thinking about this. However replacing the YAML via the editor may not work still with this method. If not, we will just have to abandon attempting to retain folds in Live Preview.

Also, this is a good opportunity to add BRAT to this plugin as this should probably be something that gets BETA tested before it gets to the end user since Live Preview is very finicky and can cause unexpected problems.

**Comment by Shenhaoyi** [comment] 2024-02-25 05:22
I've encountered this issue as well. However, I use list folding extensively. I often collapse at least dozens of places in my writing to facilitate an overview of the entire document. But now, every time I format, they all expand, which is very frustrating for me. Also, I remember that it used to be possible to preserve folding information, but it started having problems after a recent update.

**Comment by pjkaufman** [comment] 2024-02-25 10:06
Yeah. So this used to work to an extent because the logic would ise `editor.replaceRange` to only updates part of the document that changed. That works in Source Mode and it used to work in Live Preview. Then the new Properties plugin got created and the frontmatter was converted to a widget or something like that. Then `editor.replaceRange` stopped working for Live Preview's frontmatter. To fix this we stopped using `editor.replaceRange`.

So this is a pretty tricky problem that is easy to fix in Source Mode, but will be hard to fix in Live Preview mode (though I am not sure if this will get fixed in Live Preview mode).

**Comment by chablo** [comment] 2024-02-26 13:22
While waiting for a more global fix potentially resolving the live preview mode, can you detail the changes to be made to correct the problem on the source mode?

**Comment by pjkaufman** [comment] 2024-02-26 13:44
Using the code added by https://github.com/platers/obsidian-linter/pull/17 or using the code removed by #963 should fix the issue in Source Mode.

**Comment by chablo** [comment] 2024-02-27 09:42
Thank you! I did the change and surprise... It works in live preview mode 😄 (but don't know why)

Don't hesitate to let me know if you'd like me to do any specific tests or if you'd like more information.
But that makes me think it could be fixed "easily"?

**Comment by pjkaufman** [comment] 2024-02-27 10:12
Unless they fixed issues with Live Prebiew, when a lot of changes are made to the YAML by the Linter, it does not work.

**Comment by pjkaufman** [comment] 2024-03-13 22:24
I am taking a stab at this once more to see if I can get it working better in both modes without too much work. I make no promises.

Also, I wanted to mention that there are integration tests for verifying that Live Preview save does work. So if the original logic is working for those integration tests, then I can use them, but if it is not, they will be modified to do the following assuming I can properly do so:
- grab the YAML section of before and after and compare them
  - If they are not the same, then go ahead and update the YAML as a whole (you will lose your folds here, but in live preview that should not matter)
-  Make editor replacements for all other values like what is done in source mode from before (I hope that this will work, but we shall see on that...)

**Comment by pjkaufman** [comment] 2024-03-13 22:31
It did not pass the integration tests, so the modified version of this original will be necessary.

**Comment by pjkaufman** [comment] 2024-03-13 23:51
Looks like the change does work. I need to test folds in live preview and source mode to verify they do not get overwritten. If that works, then I plan to go ahead and see about making this change. I will likely put it in as a BRAT change (assuming I make time to actually set that up for early testing of features).

**Comment by pjkaufman** [comment] 2024-03-14 00:05
Looks to work for this. I will see about making a PR.

**Comment by pjkaufman** [comment] 2024-03-14 01:15
Ok. So I have a PR in place and it should get merged soon. Here is a [main.zip](https://github.com/platers/obsidian-linter/files/14595444/main.zip) which has the compiled js if you want to install the change and test it out now.

**Comment by pjkaufman** [comment] 2024-03-14 01:23
The changes for this should be on master and go out in the next release. Please let us know if there is an issue with either of those two. I also want to make a BRAT setup and include this on it, but that may take me some time. I hope this helps fix this issue.

**Comment by chablo** [comment] 2024-03-16 14:56
> Ok. So I have a PR in place and it should get merged soon. Here is a [main.zip](https://github.com/platers/obsidian-linter/files/14595444/main.zip) which has the compiled js if you want to install the change and test it out now.
> 
> It should be able to be installed by unzipping it and copying `main.js` to the `obsidian-linter` folder under `vault_path/.obsidian/plugins/`

Hello, thanks for the update! I tried it and it works on somes files I tested.
Well done!

**Comment by pjkaufman** [comment] 2024-03-16 17:54
I am glad that it worked.

**Comment by chablo** [comment] 2024-03-17 01:10
Finally, I seem to have encountered a few bugs, particularly when creating a new file.
Usually, when I saved a new file after its creation, I automatically had the file name in the header (H1) with the YAML properties (creation date, modification date and tags) above.
Now, the properties are added incorrectly formatted, and each time the linter is triggered (saving in my case), the properties are duplicated.

Don't hesitate to let me know if you can't reproduce this state.
For your information, here's the main.js file I was using (including a few modifications based on your previous recommendations) which seemed to work without this bug : [main.zip](https://github.com/platers/obsidian-linter/files/14625769/main.zip)


I haven't been able to do any more tests for the moment, so the problem may also be due to my set-up.

**Comment by pjkaufman** [comment] 2024-03-17 11:52
Hey @chablo , could you provide your `data.json` so I can see if I can reproduce the issue?

**Comment by chablo** [comment] 2024-03-17 13:22
> Hey @chablo , could you provide your `data.json` so I can see if I can reproduce the issue?

Sure : [data.json](https://github.com/platers/obsidian-linter/files/14627506/data.json)

**Comment by pjkaufman** [comment] 2024-03-17 17:06
> > Hey @chablo , could you provide your `data.json` so I can see if I can reproduce the issue?
> 
> Sure : [data.json](https://github.com/platers/obsidian-linter/files/14627506/data.json)

Thanks! I think I see the issue. I need to take a closer look. But it looks like when there was no YAML frontmatter previously the content is not being added correctly as I am getting:
``` markdown
date created: Sunday, March 17th 2024, 1:03:04 pm
date modified: Sunday, March 17th 2024, 1:03:47 pm
```

This likely means that I need to go ahead and check if there was no markdown before and add `---\n{FRONTMATTER_HERE}\n---` to the document.

**Comment by pjkaufman** [comment] 2024-03-17 17:09
I will see about addressing that scenario, but it could take a little time for that to get added since I have some things to knock out today.

**Comment by pjkaufman** [comment] 2024-03-17 17:43
Ok. I think I have a fix. I had some time, so I decided to take a look. @chablo , could you test out the following [main.zip](https://github.com/platers/obsidian-linter/files/14628277/main.zip)? It should fix that issue. I am just not sure if it breaks something else.

**Comment by chablo** [comment] 2024-03-17 19:56
@pjkaufman Thank you for your quick update!

It works in source mode but I have some bugs in live preview.
I now have the impression that I have to trigger the file lint several times for my rules to be taken into account.

Example to reproduce with my rules:
- Create a new note
- Trigger linter
- Add a tag 
- Trigger linter (the tag is put in the YAML but not removed from the rest of the document)
- Trigger the linter several times (4 or 5 times in my case) => the tag is removed from the rest of the document

This also applies, for example, to adding a line break after a header, and therefore to all rules.
What's more, every time the linter is triggered, I get a message saying that characters have been added/deleted, even though it doesn't appear that any changes have been made.

**Comment by pjkaufman** [comment] 2024-03-17 21:34
Gotcha. I will need to take a look as these scenarios are not exactly straight forward when it comes to what is going on.

**Comment by pjkaufman** [comment] 2024-03-19 21:02
I am having trouble reproducing the latest scenario that you described @chablo . Here is the latest [main.zip](https://github.com/platers/obsidian-linter/files/14656587/main.zip). I will try with your `data.json` that you provided before later and see if that works for me to reproduce it since the ITs I setup are not catching it.

**Comment by pjkaufman** [comment] 2024-03-20 22:45
I can reproduce with the `data.json` you provided prior. I need to determine what is going on and see about fixing this.

**Comment by pjkaufman** [comment] 2024-03-20 22:58
I can now reproduce it in the ITs. It looks like it requires the frontmatter to already be a certain size (?). I will dig into this some more and see what is going on.

**Comment by pjkaufman** [comment] 2024-03-20 23:07
I think I caught the culprit of that issue, though the issue was two fold. I need to see if I can address the route cause of the problem.

**Comment by pjkaufman** [comment] 2024-03-20 23:20
Here is the updated zip @chablo :  [main.zip](https://github.com/platers/obsidian-linter/files/14675688/main.zip).
Feel free to start using it.

**Comment by pjkaufman** [comment] 2024-03-20 23:21
I am going to take a stab at getting the change on BRAT. But that might take more time than I have in the near future so that could take some time.

**Comment by pjkaufman** [comment] 2024-03-20 23:24
I merged the change relating to this into master. So it can be manually compiled from there in the meantime.

**Comment by pjkaufman** [comment] 2024-03-23 16:58
The changes are available via BRAT now. So if you want to go ahead and use that to install the changes.

**Comment by ramarivera** [comment] 2024-04-22 15:47
Hi @pjkaufman ! 
I just wanted to share that I tested the latest version on BRAT, and it works wonderfully for preserving the document folding status. 
Thank you so much for fixing this, it was my only pain point when using Linter <3

**Comment by pjkaufman** [comment] 2024-04-24 01:03
I am glad to hear that. I will plan on including this in the next release of the Linter later this week.

**Comment by pjkaufman** [comment] 2024-04-24 01:03
I will close this issue since it has been fixed in the BRAT version and I have not heard anything about the issue since.

**Closed by pjkaufman** 2024-04-24 01:03 UTC
Labels: bug, obsidian, resolution/update-made, reproducible, live-preview
