### ISSUE TITLE
Bug: New blank line around code fence rule does not respect callout/blockquote line prefixes for code fence

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [platers/obsidian-linter#299] opened 2022-07-16 23:20 UTC
## Describe the Bug

New rule for [empty line around code fences](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#empty-line-around-code-fences) does not respect when a code fence is inside a blockquote or callout.

## How to Reproduce

````markdown
> [!callout-name]
> ```language-name
> myCode
> more code
> ```
> ```language-name
> different code
> ```
````

Enable [empty line around code fences](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#empty-line-around-code-fences) rule and lint. 

### Observed Output

````markdown
> [!callout-name]

```language-name
> myCode
> more code
> ```

```language-name
> different code
> ```
````

The first blank line breaks the callout because of the missing `>`. The `> ` has also been removed from the front of the code fence.

## Expected Behavior
Adds blank lines around the code fence that are at the same level of blockquote/callout nesting as the code block. Keeps the starting line of the codeblock at the same level of blockquote callout nesting.

````markdown
> [!callout-name]
>
> ```language-name
> myCode
> more code
> ```
>
> ```language-name
> different code
> ```
>
````

OR ignore codefences inside callouts/blockquotes if needed but please do not arbitrarily remove `> ` in front of code fences!
OR if codefences inside blockquotes/callouts are fundamentally contrary to this lint rule, please document that so that users will know not to turn it on! I check the diff in the release notes when updating the plugin, before turning on new rules, and did not see anything about this.

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

I have not tested with plain blockquotes or nested blockquotes/callouts but I expect it to be similarly broken there.
Use case: I use codeblocks inside callouts to get multi-column features via the excellent https://efemkay.github.io/obsidian-modular-css-layout/multi-column/
If this use case is contrary to the lint rule and I should not be using this lint rule, please document that.

PS: Thanks for all your work and updates on this plugin!

**Comment by pjkaufman** [comment] 2022-07-16 23:49
Thanks for reporting this issue. It will hopefully be addressed by the next release. In the mwantime, you may want to refrain from using this rule or disable it in files with block quotes or callouts.

**Comment by pjkaufman** [comment] 2022-07-17 00:12
Just as a heads up, some issues get past initial testing. Nesting formats inside of each other is more likely to hit these scenarios as I often do not nest formats myself and thus lack representative test cases. I would be happy to test against such situations if someone were to provide files for me to run the linter against.

Thanks for understanding!

**Comment by pjkaufman** [comment] 2022-07-17 00:22
@AnnaKornfeldSimpson , is there another code block in that file besides what is in the callouts? The regex does not seem to match the scenario provided by itself.

**Comment by pjkaufman** [comment] 2022-07-17 00:28
I have a change that will ignore the above scenario now even if it is followed by a regular code block later in the file. I do need to see about handling nested formats though.

**Comment by pjkaufman** [comment] 2022-07-17 00:41
@AnnaKornfeldSimpson , I thought the only way to escape a nested codeblock was to add 3 more backticks. Is that not the case?

**Comment by pjkaufman** [comment] 2022-07-17 09:14
Thanks for the info you provided. I eill look it over and see about fixing things up. This week will be a packed week for me, so I would not expect any fixes until the end of next week.

**Comment by pjkaufman** [comment] 2022-07-17 09:16
It also looks like he used more than just backticks for his markdown fenced code blocks unlike his examples. I will see about getting that updated, but that logic will take me a minute to get setup.

**Comment by pjkaufman** [comment] 2022-07-28 12:05
I wanted to let you know that I have not forgotten about this. But I am trying to think through how to properly handle tables and code fences in blockquotes. I am guessing I will need to ignore them in blockquotes on the initial pass and pass in the new line value after that, but that may not work for double nesting. I could grab the content up until the start of the last new line character if the table does not start a line and that could be used to create the proper new line beginning, but I have not yet decided if this has any flaws.

All in all, I have not forgotten about this, but there are some technical difficulties surrounding making the updates at this time.

**Comment by pjkaufman** [comment] 2022-07-30 14:45
I am currently trying to workout some issues upstream (in a dependency's code). Once that change is made, it should be possible to move forward with work on this issue. It makes it a lot easier to let the dependency handle the parsing of tables instead of using regex to match tables as that can be iffy some times. I initially added the regex, but handling content in blockquotes will need to wait for tables until I have the ability to get them from the parser directly.

Here is the issue that holds a decent bit of discussion around this: https://github.com/micromark/micromark-extension-gfm-table/issues/5.

I guess the easiest solution for now is to ignore tables in blockquotes (add an example showing the limitation) and then add support for blockquotes once the issue upstream gets resolved allowing for a simplified check.

**Comment by pjkaufman** [comment] 2022-07-30 15:53
Seems that the issue is not reproducible on the devs side of things, so I will go ahead and leave the dev alone and work around the issue as best I can. But the parser and Obsidian disagree on how a table is defined which may cause some issue with how things are displayed. I will add an example to make it clear that it follows github flavored tables and that may lead to some weird output if text directly follows a table.

**Comment by pjkaufman** [comment] 2022-07-30 16:13
Not really. I am working out the code for it. I have a work around for the issue, it is just a little lower level.

**Comment by pjkaufman** [comment] 2022-07-30 18:03
I have to account for multiple blank lines before and after being cut down to one. But the overall logic seems to be present and working now.

**Comment by pjkaufman** [comment] 2022-07-30 21:24
This bug should be fixed on master now. I plan on making a release either tonight or tomorrow, so it should be fixed in the release as well. Please let us know if the issue still exists.

**Closed** 2022-07-30 21:23 UTC
Labels: bug, markdown

**Comment by pjkaufman** [comment] 2022-07-30 21:25
It should also now ignore nested code blocks :crossed_fingers:

**Comment by pjkaufman** [comment] 2022-07-30 21:25
I am thinking it does, but I forgot to add a test for that. So that is why the fingers are crossed.

**Comment by pjkaufman** [comment] 2022-07-30 21:42
Seems they do get an empty line added around them. I will add an example for it.
