### ISSUE TITLE
Bug: File Menu Lint Updates Date Modified in All Cases

### ISSUE THREAD

**Issue by karmeye** [platers/obsidian-linter#745] opened 2023-05-30 07:31 UTC
Linting a file updates the yaml modification date even though the file hasn't been modified.

**For example:**

File x has modified date in yaml: 2023-04-07T13:56:26+02:00, and on file system: 2023-04-27 17:44.

After linting, the yaml modified date is set to the current date time, rather than the actual last modified date, which was recorded by the file system as 2023-04-27 17:44. 

So in this case I expected the yaml to be updated to the last modification date from the file system rather than the current time.

**Example 2:**

The yaml modified date and file system are the same — a date in the past. In this case the file shouldn't be touched. 

---

This issue occured to me as I was just modifying a few files in a folder of many files and I linted the whole folder, expecting that only the files I had modified would be linted, but every single file got their yaml modification dates updated. So this means that all mod dates for these files are now incorrect.

**Comment by pjkaufman** [comment] 2023-05-30 10:07
This is not a bug @karmeye . This is how YAML Timestamp works.

When an update is made to a file, if the last modified date was say 3 months ago. When the Linter sets the last modified sate to be 3 months ago despite being updated today. Thus your modified date could be wildly incorrect. As a result, the modification date is set to about when the Linter saves. This prevents lots of erroneous updates when doing mass updates.

If you do not believe that this is a good way to keep the modified date close to what is in the filesystem (generally within 5 seconds of it), I am open to feature suggestions.

**Comment by pjkaufman** [comment] 2023-05-31 08:05
Do note: the Linter only updates the date modified if:
- the format in the YAML differs from the expected
- the file contents are different
- the date modified of the file and what is in the YAML differ by more than 5 seconds.

**Comment by pjkaufman** [comment] 2023-06-01 10:04
Could you provide an example where it is happening? It could be that the Linter was slower than expected. However, it could also be that there is extra whitespace at the end of the value.

**Comment by pjkaufman** [comment] 2023-06-02 10:50
Could I also get your settings for the Linter? That is your `data.json` contents. You can find that value under the debug tab in thr Linter Settings.

**Comment by pjkaufman** [comment] 2023-06-16 11:52
I am able to reproduce what you are seeing. I will have to debug and see if this is a problem with the Linter or something else that is causing the problem. It could be whitespace is being added and then removed which is causing the issue.

**Comment by pjkaufman** [comment] 2023-06-16 12:33
I believe I have a fix for this issue. The problem was that it was assuming that if you had a value and you were forcing the retention of the current value, it should update the value. Thus it was updating the value no matter what for existing values that had the created timestamp value on and were forcing its retention.

**Comment by pjkaufman** [comment] 2023-06-16 12:37
Looks to be fixed from my tests against the changes I made. I am going to push them up. They should go out in the next release. Thanks for reporting the issue!

**Comment by pjkaufman** [comment] 2023-06-16 12:47
The changes for this have been merged into master. It should be fixed with the next release. Please let us know if there is any issue with this post-release or on master.

**Comment by pjkaufman** [comment] 2023-07-10 10:36
The next release is not out yet. I plan to try one or two more things in the CI for the plugin before releasing the changes.

**Comment by pjkaufman** [comment] 2023-07-10 10:37
I hope to release the changes later this week.

**Comment by pjkaufman** [comment] 2023-07-10 10:42
I will try to reproduce this with the `data.json` above and let you know if I can reproduce the issue. I at least addressed one part of the problem if there were not othera.

**Comment by pjkaufman** [comment] 2023-07-10 11:07
I am not seeing this issue with the `data.json` provided. Are you able to reproduce via linting on save? If so, could you include a reproducible file here? The test file added above is not causing the issue for me.

**Comment by pjkaufman** [comment] 2023-07-15 16:21
> @pjkaufman Why was this closed?

This was closed because an issue was identified and fixed. I could no longer reproduce the scenario described. Now I am being told there is a different scenario.

I am not sure I follow what is going on here since linting in source mode and reading view should yield the same results. Is your `data.json` still the same? If so, I will try the steps you have provided above, but if I cannot reproduce on my dev machine (a linux computer), I will not be able to fix the issue.

**Comment by pjkaufman** [comment] 2023-07-15 19:10
@karmeye , to clarify, you are on version 1.17 of the Linter now, right? I believe the fix was released in 1.16, but I am not sure.

**Comment by pjkaufman** [comment] 2023-07-15 19:39
> Please follow along:
> 
> Starting out with a linted and saved file.
> 
> 1. In Reading View
> 2. Run Save file
> 3. 2 charaters added, 2 characters removed; modified date is not changed
> 4. Check modified diff: no changes
> 
> Next
> 
> 5. Go to Source Mode
> 6. Run Save Current File
> 7. 3 charaters added, 3 characters removed; modified date is updated to current time
> 8. The modified diff only contains the modified date change, which is indeed 3 chars
> 
> ```
> -modified: 2023-07-15T20:03:21+07:00
> +modified: 2023-07-15T20:16:22+07:00
> ```
> 
> After > 1 min I run Save Current File again, still in Source mode: 0 characters changed. This time it worked as expected.
> 
> Now I do steps 1 and 2 again, which resulted in 3 and 4 as before.
> 
> After > 1 min I run Save Current File again, still in Reading view: this time I get 4 characters changed. No changes in the diff, we're still at 2023-07-15T20:16:22.
> 
> Now I do steps 5 and 6 again, which resulted in 7 and 8 again, so the file was updated:
> 
> ```
> -modified: 2023-07-15T20:03:21+07:00
> +modified: 2023-07-15T20:33:16+07:00
> ```
> 
> * So during the process I never touched any file contents.
> * Something happens when swithing modes.
> * I thought the files are locked/read-only in Read view
> * When I run lint on a folder all files updates even though only a few have changed.

I am not able to reproduce any of this behavior myself. Until I know what version of the Linter you are on, I am going to hold off on trying to reproduce this since the `data.json` added above and these steps to reproduce on the test file provided are proving to be insufficient to reproduce the issue on my device.

Hopefully this is just a version issue where getting to 1.17 fixes the issue. If not, I may have to add some extra logging to a `main.js` file and have you send the me results from that , if you are fine with that.

**Comment by pjkaufman** [comment] 2023-07-16 03:30
Thanks for letting me know that you are on the latest version.

I am not sure what is going on, but it is likely specific to the OS in use or your timezone settings (I am not sure which). However, I will go ahead and see about addressing the issue as best I can without being able to reproduce the issue myself.

Based on earlier statements that 
> Now I do steps 5 and 6 again, which resulted in 7 and 8 again, so the file was updated:
> ```
> -modified: 2023-07-15T20:03:21+07:00
> +modified: 2023-07-15T20:33:16+07:00
> ```

I can only assume it is something happening in the `yaml-timestamp` rule itself. If the date modified is the only thing changing, then it has to come from either `yaml-timestamp` or `force-yaml-escape`. In your case, `force-yaml-escape` is off, so it can only be `yaml-timestamp`. As such, I will add debug logs to that rule to see what is going on there. It should give an idea of what is going on, even if it does not solve the problem initially.

**Comment by pjkaufman** [comment] 2023-07-16 04:07
Here is the zip with the `main.js` in it: 
[main.zip](https://github.com/platers/obsidian-linter/files/12063270/main.zip)

It includes a lot of different logs for `yaml-timestamp`.

You should be able to do the following to help get information that may help shed some light on what is going on in the cases you are describing:
- Unzip the zip file
- Copy the `main.js` to your vault under `.obsidian/plugins/obsidian-linter/`
- Reload Obsidian/disable and re-enable Linter in list of community plugins
- Go to Linter settings and turn log level to `Debug`
- You can then turn on `Collect logs when linting on save and linting the current file`
  - This will make it so after you save a file logs are stored in an easier way for them to be copied
-  Lint a file where the issue is happening
- Then go to the Linter settings and Debug tab there
- Copy the contents of `Linter Logs` and post them in a code block to this issue

Once I have that info, I can see if the root cause of the issue makes more sense. I will use the logs to try to track which logic was hit in the code and why it thinks it modified something when it did not yet do so.

**Comment by pjkaufman** [comment] 2023-07-16 11:20
> Hmmm, is the `text after rule:...` supposed to show the file's content after the lint? In that case it's not correct.

@karmeye , it shows the file contents after `yaml-timestamp`. It looks like the culprit is not `yaml-timestamp`.  Since `yaml-timestamp` is returning no changes to the rule. However it does look like `yanl-key-sort` is running... I thought it was disabled, but looking above, I see that it is not. That is my bad. I will add logs to it and push up another `main.js`. That is likely where the issue is.

> `modified` was set to current time option passed in, i.e., `currentTime":"2023-07-16T07:14:43.130Z`, resulting in `modified: 2023-07-16T14:14:43+07:00`

That would have to happen after the running of `yaml-timestamp` based on the output of the logs which is indicating the following runs after `yaml-timestamp`:

```
Running YAML Key Sort
rules after regular rules: 3.199999999254942 ms
rules running: 26.299999997019768 ms
Running Custom Lint Commands
```
Since you have 0 lint commands in your `data.json` above, I am assuming the problem lies in `yaml-key-sort`. Sorry I missed that earlier.

> Note I have to lint twice for lint to run. Nothing happens after the first lint. No log either.

I am not sure what this means with regards to the Linter. However only the last run of the Linter is stored in the logs as it is designed for specifically showing what ran and any other logs that have been added during the last run.

**Comment by pjkaufman** [comment] 2023-07-16 11:37
Here is the new `main.zip`: 
[main.zip](https://github.com/platers/obsidian-linter/files/12063902/main.zip)

It should now include logs for `yaml-key-sort` which should give me an idea of what is happening.

Please follow the same steps described above and post the logs here. Hopefully this will give an idea of the cause of the problem.

**Comment by pjkaufman** [comment] 2023-07-16 11:48
I did try reproducing given the `data.json` contents pasted above. It may be better to upload the `data.json` itself just in case there is an issue with pasting it as text not preserving the contents of some of your YAML keys (it looks like you have a special unicode character in your priority sort values which I am not sure is being handled properly (the value from the pasted `data.json` works, but I am not sure that will be the case for the file itself.

**Comment by pjkaufman** [comment] 2023-07-17 01:28
> > I did try reproducing given the `data.json` contents pasted above. It may be better to upload the `data.json` itself just in case there is an issue with pasting it as text not preserving the contents of some of your YAML keys (it looks like you have a special unicode character in your priority sort values which I am not sure is being handled properly (the value from the pasted `data.json` works, but I am not sure that will be the case for the file itself.
> 
> [datajson.zip](https://github.com/platers/obsidian-linter/files/12065501/datajson.zip)

Thanks @karmeye ! Also, I did add the updated `main.zip` above for you to be able to get some logs for the yaml key sort.

> Here is the new `main.zip`: 
> [main.zip](https://github.com/platers/obsidian-linter/files/12063909/main.zip)

**Comment by pjkaufman** [comment] 2023-07-17 03:43
I seem to get the same result from the `data.json` zip. So I cannot reproduce using that. Whenever you try out the new `main.zip` file, let me know what the logs are and I can see about finding a solution from there.

**Comment by pjkaufman** [comment] 2023-07-18 09:11
> Regarding these three ways to lint a file (I haven't tested the file-context-menu options to lint).
> 
> 1. On save (if Lint on Save is enabled)
> 2. The "Lint Current File" in the command palette (only appears when Read View is off)
> 3. From the menu
> I usually lint using 3. I have "Display Message on Lint" enabled.
> 
> I assumed theae three ways to lint triggers ui events in code that then call the same "lint()" function. But 3 seems different from 1 and 2:
> 
> * 3 does not show messages on lint
> * 3 does not generate a debug log, whether I explicitly modify a file or not. But the file is nonetheless correctly linted.
> 
> What's the difference between 1/2 and 3? I assumed they function exactly the same but they don't.

Options 1 and 2 know they are running on the currently active file. However 3 can be used to lint any file in the vault. It was really mwant for linting files that were not the current file which is why it does not display the message about the amount of changes made or the logs. This can im theory be changed.

> Edit: Another question. Since 2 only appears when Reading View is off, does that mean that linting is not supposed to run, or could cause problems, in Reading View?

In this case, it is more the former. It is just incidental that you are able to lint a file in Reading View. It should be harmless, but I cannot vouch for that since I do not know the internals of how Obsidian works with Reading View.

**Comment by pjkaufman** [comment] 2023-07-19 10:12
Gotcha @karmeye . I will see if I can reproduce the issue. I am not sure why it would get updated, but for some reason the date modified is different for the file when menu-lint is run.

**Comment by pjkaufman** [comment] 2023-07-19 10:23
I can reproduce this now, so I will reopen the issue.

**Comment by pjkaufman** [comment] 2023-07-19 10:42
I may have found the issue. It looks like linting the non-current file always seems to call modify file [here](https://github.com/platers/obsidian-linter/blob/fbb522d475a95f1fafb25c05168d14f74e7355a0/src/main.ts#L295).

I assumed modify would go ahead and actually do an update iff there was a change. However that does not seem to be the case. Thus it is updating the date modified on save via that mechanism no matter what. I am updating the logic and going to see if it still works that way.

**Comment by pjkaufman** [comment] 2023-07-19 10:45
I believe that that does the trick. I will push one more change and then have you take a look and see if there is any issue with that. If not, we should be good to close this as mass linting should no longer call modify unless the starting and new text values are different.

**Comment by pjkaufman** [comment] 2023-07-19 10:51
@karmeye , thanks for bearing with me on this. I don't typically use this specific scenario and it only happens via Obsidian so it is a little bit harder to catch.

Here is the 3rd main.js instance. 
[main3.zip](https://github.com/platers/obsidian-linter/files/12094091/main3.zip)

It should fix the issue. If not, please let me know when you get a chance so I can make changes before merging the fix to master (in the next couple of days).

**Comment by pjkaufman** [comment] 2023-07-20 10:24
> Seems like it's working now!
> 
> Thanks for bearing with _me_ and your commitment to this plugin!

I amglad to hear that it is working. I will merge the changes to fix this now.

**Comment by pjkaufman** [comment] 2023-07-20 10:30
The changes for this have been merged and should go out with the next release. Please let us know if that is not the case.

**Closed** 2023-07-20 10:29 UTC
Labels: bug, yaml, resolution/update-made, reproducible
