### ISSUE TITLE
Bug: No bare URIs breaks file links with triple slashes

### ISSUE THREAD

**Issue by Martin-Milbradt** [platers/obsidian-linter#1030] opened 2024-02-29 11:46 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

A file link with the slashes `///` is broken after linting:
E.g. `file:///C:/Untitled.md` becomes `<file:///>C:/Untitled.md`

## How to Reproduce

1. Activate the rule "No Bare URIs"
2. Create a note with a file link, e.g. `file://C:/Untitled.md`
3. Lint the file

### Excerpt from the log

```
# Untitled

file:///C:/Untitled.md

Running No Bare URLs
no-bare-urls: 0.09999999403953552 ms
# Untitled

<file:///>C:/Untitled.md
```

## Expected Behavior

Brackets are around the link, not after `file:///`

Expected output:

``` markdown
<file:///C:/Untitled.md>
```

## Screenshots

![image](https://github.com/platers/obsidian-linter/assets/61841994/d410d4f6-dcc4-4e9c-85b5-49d1b09019ed)

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2024-02-29 16:08
Hey @Martin-Milbradt . It looks like I can reproduce this. I will see if I can figure out what is going on. It looks like the regex is matching correctly based on the regex tester I am using, but I am getting the result that you are. Hopefully this can be resolved soon.

**Comment by pjkaufman** [comment] 2024-02-29 16:19
Looks like it was a simple fix. I will go ahead and push that up.

**Comment by pjkaufman** [comment] 2024-02-29 16:28
This change has been merged into master and should go out in the next release. Please let us know if it does not work on master or in the next release.

**Closed as completed** 2024-02-29 16:28 UTC
Labels: bug, markdown, resolution/update-made, reproducible
