### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Fifof-hup** [platers/obsidian-linter#877] opened 2023-09-04 09:25 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug
Dear Dev Team

Tags Format allow we to update the Devonthink tags when I modify it in Obsidian.
1/ I had set my Obsidian Tags in Linter as: 
YAML Test section in :“single string comma delimited” . (screenshoot : 1.1_Innitial tag creation)
2/ But when you apply the Linter Rules in Obsidian wiht the new version 1.4.5 the tags are now in Multiline (Screenshot : 1.2 Tags modify by propreties) and I try to apply the linter rules , but It can't modify it : (screenshot : 2_Linter Can't Chage Propreties)
3/ f they are set in multiline like, DVTK not recognize it as a YAML section. (Screenshoot : 3_Result in devonthing )
It’s means that my workflow is broken.

Can you help me? 
Thanks a lot

<img width="1371" alt="1 1_Innitial tag creation" src="https://github.com/platers/obsidian-linter/assets/119171707/b228dec9-4657-406b-a784-77d2ba40434b">
<img width="1371" alt="1 2 Tags modify by propreties" src="https://github.com/platers/obsidian-linter/assets/119171707/cd4fa61d-6113-42b2-9b85-21cda903e943">
<img width="1415" alt="2_Linter Can't Chage Propreties" src="https://github.com/platers/obsidian-linter/assets/119171707/6542da5c-fbd2-42a4-b82c-85b8b1622113">
<img width="1415" alt="3_Result in devonthing" src="https://github.com/platers/obsidian-linter/assets/119171707/44038236-a6b7-4455-8d45-4b50d2636ff0">

**Comment by pjkaufman** [comment] 2023-09-04 11:16
@Fifof-hup , thanks for reaching out. I have a couple of questions for you to help me better understand what is going on.

- Does this issue happen when the properties core plugin is disabled?
- Is there a reason the tag seems to start with a dash (that value can get misconstrued as a multiline array indicator)?
- Can you put the tag that starts with `-` in quotes and see if the issue still happens?

**Comment by Fifof-hup** [comment] 2023-09-04 12:51
Thanks Paul to your Quick reply. 
1/ yes if I mask the plug in in the left bar is working better! : the tag stay on one line , **but the Comma is not automatically set** up. It's a huge issues for me because I will import 10K of my Evernote note in obsidian. 
2/ Yes the dash is my Tag structure I used also in DVTK
3/ Nothing happen
Many thanks 
Christophe

**Comment by pjkaufman** [comment] 2023-09-04 13:41
@Fifof-hup , could you provide your `data.json` and a sample file that causes the problem for debugging purposes? I am having trouble reproducing the issue you mentioned above by just formatting YAML arrays using a comma delimited string as the tag format.

I am seeing that if you use the properties view to add a value with a dash at the start it is converting the list of tags to a multiline array. However, I have no control over that.

**Comment by Fifof-hup** [comment] 2023-09-04 13:53
ok ! 
can you tell me how export the note in Jason format? 
Thanks

**Comment by pjkaufman** [comment] 2023-09-04 14:04
As for the sample markdown file, you can just upload a markdown file or paste the file contents in a code block that would look something like
\`\`\` markdown
FILE_COTNENTS_HERE
\`\`\`

**Comment by Fifof-hup** [comment] 2023-09-04 14:51
Thanks , please find the fille exemple enclosed. 

This is exactly my Tag YAML presentation objective. 
tags : Single line , wiht comma, without array ... wiht this format I can read it in DVTK
in the YAML exemple : works
in The JPEG in the note : not working
in the same note you have my config bellow the JPEG

Christophe 
[2_Test Tag YAML+ Linter Config @ Afher Propreties open , Linter can't change it.md](https://github.com/platers/obsidian-linter/files/12514741/2_Test.Tag.YAML%2B.Linter.Config.%40.Afher.Propreties.open.Linter.can.t.change.it.md)

**Comment by pjkaufman** [comment] 2023-09-04 17:19
@Fifof-hup , it looks like you are not applying any settings to actually format the YAML arrays. A lot of the settings in general are just for specifying settings used by the actual rules. When you set the value for tags to be a comma separated list, that is saying that any rules that format the tags value will try its best to reformat it into the desired format. You will need to turn on `Format YAML Arrays` and enable the option for formatting tags:
![image](https://github.com/platers/obsidian-linter/assets/29898683/572aff0d-6344-427f-9d5c-e6ea937eaedf)

It looks like based on the screenshot that you have disabled the format YAML arrays rule which is why the Linter can do nothing to the tags format. Could you turn that rule on and let me know if it starts working?

**Comment by Fifof-hup** [comment] 2023-09-04 18:11
It's works @pjkaufman ! 
I activated the Array section and it's done 
Many thanks ! I will Xrite a pst hoax to use the YAML in. Obsidian and DVTK  with Linter!

**Comment by pjkaufman** [comment] 2023-09-04 21:14
Sounds good. I am going to close this since it looks to have been resolved.

**Closed by pjkaufman** 2023-09-04 21:14 UTC
Labels: bug
