### ISSUE TITLE
Bug: Linter 3 consecutive callouts ads unwanted sign ">" between them

### ISSUE THREAD

**Issue by merlinuwe** [platers/obsidian-linter#671] opened 2023-04-06 08:11 UTC
Thanks for your great plugin.

I have some callouts in a note, here is a screenshot:

![image](https://user-images.githubusercontent.com/4138869/230315406-4a5c20ed-ec07-4b1d-8cf9-6675c7a334a6.png)

When I linter the note, they are connected with an additional > sign:

![image](https://user-images.githubusercontent.com/4138869/230315639-134707a1-01e6-4340-944d-e47a72746741.png)

What can I do to avoid this?

**Comment by nerumi** [comment] 2023-04-06 10:15
+1
I have the same question/issue.

**Comment by pjkaufman** [comment] 2023-04-06 11:56
This looks to be a duplicate of https://github.com/platers/obsidian-linter/issues/668. This is a bug that I need to take a look at fixing later on this week.

**Closed** 2023-04-07 14:07 UTC
Labels: bug, duplicate
