### ISSUE TITLE
Bug: Trying to Load Disabled Rules Before Formatting Tags Causes Error

### ISSUE THREAD

**Issue by computbiol** [platers/obsidian-linter#333] opened 2022-08-04 07:53 UTC
When format `tags: [#aa, #bb]`:

>There is an error in the yaml:
unexpected end or the stream within a
flow collection (3:1)

**Comment by pjkaufman** [comment] 2022-08-04 09:03
Thanks for reporting this @computbiol , by chance do you have the rule to remove hashtags in place?

If you do, it may be that we do not currently support the above format for fixing invalid Yaml tags.

**Comment by pjkaufman** [comment] 2022-08-04 09:05
Here is the rule I am referring to: https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#format-tags-in-yaml

**Comment by pjkaufman** [comment] 2022-08-04 10:48
Looks like the issue does still exist when I have the rule on. I will see what I can do about this.

**Comment by pjkaufman** [comment] 2022-08-04 11:20
Seems to be an issue with it running in the right order. I need to take a closer look at this which will likely be tomorrow. It looks like something is not being handled correctly as my attempts to console log values is not showing up, but that may be operator error.

I did notice that the rule for fixing Yaml values showed up before removing the hashtags which will be fixed in the next release, but that does not seem to be the cause of this issue.

**Comment by pjkaufman** [comment] 2022-08-04 11:22
The problem is the loading of disabled rules before removing the hashtags. It will likely need to be rewritten to handle the new order of events.

**Comment by pjkaufman** [comment] 2022-08-04 11:36
I think I have a fix, but I need to make sure it is a good option before proceeding with it. This issue should be fixed for next release.

**Comment by computbiol** [comment] 2022-08-04 11:43
> Thanks for reporting this @computbiol . By chance do you have the rule to remove hashtags in place?
> 
> If you do, it may be that we do not currently support the above format for fixing invalid Yaml tags.

Thank you for your re[ly. It was working until today, but today there was a sudden error. The rule? This is the effect I want: 

```
Example: Format tags in array

Before:

---
tags: [#one #two #three]
---
After:

---
tags: [one two three]
---
```

**Comment by pjkaufman** [comment] 2022-08-04 12:13
That makes sense. It is likely that you updated to one of the more recent versions of the plugin recently. The rule is working fine, but some logic was getting run before the rule got applied, so it hit the error you are seeing. This should be fixed on master in the next couple of days. It will likely be released next week since there have not been a lot of changes this week, and I don't have a lot of time to work on it this weekend.

**Comment by computbiol** [comment] 2022-08-04 12:47
> That makes sense. It is likely that you updated to one of the more recent versions of the plugin recently. The rule is working fine, but some logic was getting run before the rule got applied, so it hit the error you are seeing. This should be fixed on master in the next couple of days. It will likely be released next week since there have not been a lot of changes this week, and I don't have a lot of time to work on it this weekend.

Thank you very much for your kind reply.

**Closed** 2022-08-04 17:13 UTC
Labels: bug, yaml

**Comment by pjkaufman** [comment] 2022-08-04 17:16
The changes have been merged into master. Please let us know if the next release or master does not fix your issue.
Sorry for the inconvenience that this bug may have caused.

If you would like to manually install master, you can follow the steps mentioned here: https://github.com/platers/obsidian-linter#manual-installation
Otherwise you may need to wait for the next release or use a plugin to pull master for you for the plugin (I think this may exist, but I may be misremembering).
