### ISSUE TITLE
Bug: Indentations for math block removed from callouts or block quotes

### ISSUE THREAD

**Issue by Dxyk** [platers/obsidian-linter#1087] opened 2024-05-05 17:24 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Hello,

When using math blocks with sublists in a callout or block quote, the indentations for math blocks are removed, which causes the list to be rendered incorrectly. Please see code blocks and screenshots bellow. From a quick search through the issues, I think this might be related to [#289](https://github.com/platers/obsidian-linter/issues/289).

Thanks in advance for the help, and also thanks for maintaining this awesome plugin :)

## How to Reproduce

Example to reproduce the issue with

``` markdown
>[!INFO] Linter sublist latex repro
> text
> - list item 1
>     $$
>     f = ma
>     $$
>     - sublist item 1
>         $$
>         y = ax + b
>         $$
```

On lint, this gets converted to

``` markdown
> [!INFO] Linter sublist latex repro
> text
> - list item 1
> $$
> f = ma
> $$
>     - sublist item 1
> $$
> y = ax + b
> $$
```

Please see my [data.json](https://github.com/platers/obsidian-linter/files/15213830/data.json).

## Expected Behavior

I'm actually not sure what the proper format for using math blocks in lists is, but I expected at least some indentation instead of completely removing them on lint.

The expected output should be should be the same (or similar) as the input

``` markdown
>[!INFO] Linter sublist latex repro
> text
> - list item 1
>     $$
>     f = ma
>     $$
>     - sublist item 1
>         $$
>         y = ax + b
>         $$
```

## Screenshots

Before linting
![Screenshot 2024-05-05 at 1 18 49 PM](https://github.com/platers/obsidian-linter/assets/16347901/a11e4b6e-fb50-4fd4-bf03-8ca6dcad7706)

After linting
![Screenshot 2024-05-05 at 1 19 13 PM](https://github.com/platers/obsidian-linter/assets/16347901/dc051aea-67f1-4aa0-b92f-83006f35755a)

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2024-05-06 13:24
Hey @Dxyk . I have taken a quick look at this and it does seem to be correctly recognized as a math block for the AST. I will have to determine what is going on here. But that may take some time given my current availability. Hopefully this will not be too difficult of an issue.

**Comment by pjkaufman** [comment] 2024-05-07 23:29
So, if I am understanding correctly, the problem is `blockquote-style` is causing the issue. So I need to ignore math blocks for that rule.

**Comment by pjkaufman** [comment] 2024-05-07 23:33
Looks like it is a little more complicated than I originally thought. I may just ignore list items, but that could cause issues as well.

**Comment by pjkaufman** [comment] 2024-05-07 23:54
I believe I have a fix. It should handle the scenarios in question, but it will require manually adding styling for the blockquote lines that have math or code blocks on them since there is currently no way to know whether or not they are in a list item. So we just have to ignore them all.

**Comment by pjkaufman** [comment] 2024-05-08 00:00
I have gone ahead and merged the fix. It should be on master and go out in the next release, Please let us know if either has an issue.

**Closed** 2024-05-07 23:59 UTC
Labels: bug, markdown, reproducible
