### ISSUE TITLE
Bug: Add space need to ignore filenames

### ISSUE THREAD

**Issue by Erimus-Koo** [platers/obsidian-linter#662] opened 2023-03-28 07:31 UTC
Turn on the option "Space between Chinese Japanese or Korean and English or numbers"

```html
before
<img src="中文small.png" />

after
<img src="中文 small.png" />
```
Then the image file won't be found.

**Comment by pjkaufman** [comment] 2023-03-28 23:17
Thanks for pointing this out. It looks like I need to ignore html for "Space between Chinese Japanese or Korean and English or numbers".

**Comment by pjkaufman** [comment] 2023-03-28 23:23
I can reproduce this issue and I have a potential fix for this.

**Comment by pjkaufman** [comment] 2023-03-28 23:29
This change should be on Test and master now. I plan to release it later this week.

Please let us know if this issue exists in the next release or on master.

**Closed** 2023-03-28 23:28 UTC
Labels: bug

**Comment by Erimus-Koo** [comment] 2023-03-29 04:13
I've tried the current master version, and it looks great. Thank you for fixing it so quickly.

**Comment by pjkaufman** [comment] 2023-03-29 09:04
No problem. Easy fixes like this are something I tend to pick up and fix more quickly since I can do it in one sitting.

**Comment by Erimus-Koo** [comment] 2023-04-01 05:18
And there's one more thing I've just found,

```
Before
<u>「知識」ではなく</u>

After (a Space on the left of the </u> will be created, and the underline will appear on the Space.)
<u>「知識」ではなく </u>
```

I don't want to open a new issue so append it here.

**Comment by pjkaufman** [comment] 2023-04-01 09:02
> And there's one more thing I've just found,
> 
> ```
> Before
> <u>「知識」ではなく</u>
> 
> After (a Space on the left of the </u> will be created, and the underline will appear on the Space.)
> <u>「知識」ではなく </u>
> ```
> 
> I don't want to open a new issue so append it here.

This one is actually quite different as it deals with html and will be a decwnt bit harder to deal with.

**Comment by Erimus-Koo** [comment] 2023-04-04 03:02
Yes, agree.
I add a new issue here #667
