### ISSUE TITLE
FR: Add space after callout block's leading '>'.

### ISSUE THREAD

**Issue by wirano** [platers/obsidian-linter#591] opened 2023-01-17 13:19 UTC
When I was using callout blocks with unordered list inside it. I found Linter adds a blank line between items, for example:  

Before:  
```markdown
>[!NOTE]
>- a
>- b
>- c
``` 

After:
```markdown
>[!NOTE]

>- a

>- b

>- c
``` 

It confused me a while, I finally recognized that there has a space after the '>' in Obsidian's [demo](https://help.obsidian.md/How+to/Use+callouts). I fixed my code and it works well. So I think it would be helpful if Linter could help us add a space after the '>', to avoid such problem like these.

It would work like this:
Before:  
```markdown
>[NOTE]
>a  
>b  
>- c
>- d
```

After:  
```markdown
> [NOTE]
> a  
> b  
> - c
> - d
```

Thank you!

**Comment by BonjourL** [comment] 2023-03-24 04:54
感觉这样确实不错

**Comment by pjkaufman** [comment] 2023-04-24 19:05
This seems to be a duplicate of #487 . I am closing this in favor of that issue.

**Closed by pjkaufman** 2023-04-24 19:05 UTC
Labels: rule suggestion
