### ISSUE TITLE
FR: Run Commander hotkey on save / file change instead of linting

### ISSUE THREAD

**Issue by redactedscribe** [platers/obsidian-linter#930] opened 2023-10-29 13:57 UTC
## Is Your Feature Request Related to a Problem? Please Describe.

I'm using the [Advanced Tables](https://obsidian.md/plugins?id=table-editor-obsidian) plugin to format tables since Linter doesn't currently support this. To make the process smoother, I've used the [Commander](https://obsidian.md/plugins?id=cmdr) plugin to create a macro which triggers two hotkeys: The first formats all tables in the file (via Advanced Tables), and the second then lints 250 ms later (via Linter). This is great, but doesn't tie into on-save or on-file-change events that Linter tracks, requiring manual triggering of the Commander macro.

## Describe the Solution You'd Like

When Linter detects a save or file change, instead of triggering linting itself, it could allow a user to assign a hotkey to be triggered. This would let one trigger a hotkey created by Commander when a macro has been defined. Being able to trigger a hotkey (rather than tying into Commander specifically) would allow other plugins which may be for creating macros to also work.

If the feature was enabled, on file save or change, Linter would trigger the assigned hotkey and nothing more. The result in my case would be that my Markdown tables would get formatted, and then the file would get linted.

If Linter does anything time-specific, a big delay in a Commander macro could produce odd results. Linter should probably state that any unexpected behaviour as a result of triggering a hotkey on save/change is not Linter's problem but that of whichever plugin is responsible for the hotkey (e.g. Commander).

## Describe Alternatives You've Considered

Manually trigger the hotkey when dealing with tables in Markdown.

Thanks.

**Comment by pjkaufman** [comment] 2023-11-13 16:45
Hey @redactedscribe . Is there a particular reason to not use custom commands? This is designed for this particular scenario that you have described (note that time delays are not a thing the Linter does). However if you export a macro as an obsidian command (I think that should be possible, but I am not certain on that), it should be feasible to tie that into the Linter's custom commands to make sure it runs on file save.

**Comment by redactedscribe** [comment] 2023-11-14 11:30
I will have to look into it as I haven't noticed such a feature before. Thanks for pointing it out @pjkaufman.

**Comment by pjkaufman** [comment] 2023-11-14 11:40
I know QuickAdd allows creating Obsidian commands from macros/scripts/actions so if Commander does not allow it, maybe QuickAdd can be used.

**Comment by redactedscribe** [comment] 2023-11-15 17:02
I discovered the Custom tab and added my Commander command "Format tables in file and lint". That was not good since it entered an infinite loop of linting! I should've expected that...

I was hoping I could format the tables _and then_ lint (not lint then format). That way I could be sure Linter has had the last say so that the file is linted as I expect. I guess this desire isn't strictly necessary as I don't think the table formatter is adding any unexpected formatting, but it could, or some other command could.

Maybe if there was an option to do a final lint after running the custom commands then the infinite loop could be avoided. So, Linter would lint and afterwards run the custom commands, and then do a final lint.

Thanks.

**Comment by pjkaufman** [comment] 2023-11-15 20:40
I think there is a feature request to allow a user to specify that a custom command should run before the Linter runs. I think that is where this applies. However there is no garuantee that the custom command will finsoh before the Linter starts running if they run it async.

**Comment by redactedscribe** [comment] 2023-11-16 09:31
If there's a way for Linter to detect that linting was triggered via a custom command rather than itself, then it could avoid the infinite loop.

Commander's delays can be used to give enough time for previous commands in a set of commands to finish. Or without any manual delays inserted, perhaps its smart enough to track that sort of thing, I don't know.

**Comment by pjkaufman** [comment] 2023-11-16 10:11
> If there's a way for Linter to detect that linting was triggered via a custom command rather than itself, then it could avoid the infinite loop.
> 
> Commander's delays can be used to give enough time for previous commands in a set of commands to finish. Or without any manual delays inserted, perhaps its smart enough to track that sort of thing, I don't know.

I don't think that is possible to determine. I can know that a call was made from outside Obsidian, but not where it came from exactly so it would break cutsom commands to do that.

What I am thinking would be the best solution is as follows:
- Linter Change: Add an option to the Linter to run Custom Comands before the Linter runs
- A change to your commander function: no longer run lint from it, just do the table formatting and time delay

That would likely take care of what you are looking for. However linting the vault or a folder would be really slow in that case.

**Comment by redactedscribe** [comment] 2023-11-16 10:33
That would indeed take care of it. I'd just need to experiment with what delay is sufficient, but this is acceptable.

> That would likely take care of what you are looking for. However linting the vault or a folder would be really slow in that case.

Really slow because the delay would happen for every note in the vault / folder I presume. In my case I've left the default delay of 250ms since that's not an issue when linting a single file, but for many notes it definitely would noticeably add up. I have a feeling that in my particular case I could reduce it to 50 ms and it'd still work without problems. I only really lint one file at a time.

I think the user shouldn't expect Linter to behave optimally when using it to trigger commands created by third-party plugins. These commands could be from Commander for example, use delays, and have multiple steps. However I do think it's fair to expect Linter to work reasonably well with the built-in Obsidian commands.

**Comment by pjkaufman** [comment] 2023-11-16 12:47
How the Linter reacts with commands is dictated by the command. If it runs synchronously, it should work well. If not, then it is anyone's guess. That is just how JavaScript works though.

**Comment by pjkaufman** [comment] 2023-12-06 20:12
Out of curiosity, if Commander has a hotkey, then why not bind the Macro or whatever Commander calls things, to `Ctrl+s` and disable the Linter's setting for running on `Ctrl+s`?

I just saw this again and was wondering why this would not be feasible since the title here implies that Commander is already exposing a hotkey to do this so it should be able to take the place of the Linter here.

**Comment by pjkaufman** [comment] 2023-12-06 20:15
Do note that there already is a thread that is trying to do something similar to this that would remove the need for this: #827 .

The issue is asking for a better way to handle running custom commands for single file lints (the likely solution is to pass off running custom commands to a callback for the metadata cache for single file lints). This would hopefully remove the need for Commander to be involved altogether. The main thing is I have not taken the time to look into this approach too much since I am not using advanced tables and do not have a good setup for testing this right now.

**Comment by pjkaufman** [comment] 2023-12-06 20:59
@redactedscribe , I may have a fix for this to where you do not need Commander to do the delay anymore. See https://github.com/platers/obsidian-linter/issues/827#issuecomment-1843670156 which has the `main.zip` on it if you want to test it out to confirm whether or not it does actually work. It worked for me for a scenario that was supposedly having the problem, but confirmation that it is working from an actual person that uses custom commands and the bueatifying of tables would be helpful. Thanks!

**Comment by redactedscribe** [comment] 2023-12-09 14:58
> @redactedscribe , I may have a fix for this to where you do not need Commander to do the delay anymore. See [#827 (comment)](https://github.com/platers/obsidian-linter/issues/827#issuecomment-1843670156) which has the `main.zip` on it if you want to test it out to confirm whether or not it does actually work. It worked for me for a scenario that was supposedly having the problem, but confirmation that it is working from an actual person that uses custom commands and the bueatifying of tables would be helpful. Thanks!

I'm a bit confused.

I have continued to use Commander to format the table and then lint. The delay between those commands was only added as a precaution and using current or new main.js makes no difference if this delay is present or not (so I guess it does mean linting a folder/vault is faster). I will remove the delay.

> * Linter Change: Add an option to the Linter to run Custom Comands before the Linter runs
> 
> * A change to your commander function: no longer run lint from it, just do the table formatting and time delay

Adding my Commander command to Linter's custom command isn't much use since without the Commander command linting or delaying, it's identical to just running the Advanced Tables command directly. I don't think Linter supports running custom commands before linting yet, which is when I'd convert to using that over Commander.

**Comment by pjkaufman** [comment] 2023-12-09 21:19
You can continue to use Commander if you so choose. The change here basically changes the logic from running the custom commands right after the Linter runs to do the following:
- if a change was made, run the custom commands after the cache for that file updates
- if no change was made, run the custom commands right away since there will be no need to wait on the cache to update

This should fix any issues with things like Advanced Tables that does require the cache to be up to date for a file to properly update tables. I have an integration test for that specific scenario (just need to iron out a couple of things with the integration setup).

**Closed** 2023-12-10 00:09 UTC
Labels: rule suggestion, obsidian

**Comment by pjkaufman** [comment] 2023-12-10 00:11
I have merged the change for custom commands that allows it to run after the cache updates. This should affect all custom command usage. Please let us know if this does not work on master or in the next release.

**Comment by pjkaufman** [comment] 2023-12-11 22:06
> @pjkaufman Not sure if this is the right issue to report this but, I can't actually seem to get _any_ command to run via the custom command. Not sure what's up. Maybe a plugin conflict? E.g. Adding "Toggle pin" command to the custom command and linting won't pin the tab. It seems completely functionless on my end.

I believe that you said that you used Obsidian Advanced tables. Have you tried that plugin and seen if that works? I ask because I cannot attest to UI related commands as I have not tested them (they should work, but I am not sure how to test those kinds of commands unless I use them myself and know what the expected behavior is).

> ![Obsidian_2023-12-11_23-47-42](https://private-user-images.githubusercontent.com/25013746/289682091-8eeffd80-7a20-48f0-aec7-ec0bd5d6ce1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMzI0NDAsIm5iZiI6MTcwMjMzMjE0MCwicGF0aCI6Ii8yNTAxMzc0Ni8yODk2ODIwOTEtOGVlZmZkODAtN2EyMC00OGYwLWFlYzctZWMwYmQ1ZDZjZTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDIyMDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNTUyNjA1ZjgwZjk3NmY0NzgzZWZhMzhhMmQ2YWQwYTM0ZTY2MmExOWNkOWNkMDVkMTNhNjcyN2Q1Nzk1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79CLYcy2mLfADiDQcCPjE-q0RF7CNn56kPvi5V96ht4)
> 
> Also for whatever reason, the UI/UX doesn't make me confident that the custom command has been added. Maybe only selected. Just an observation.

I am not a UI/UX designer, so I personally am better at creating functionality. As such, I am open to suggestions around how to make things clearer when a command has been added.

**Comment by pjkaufman** [comment] 2023-12-11 22:26
Would it make sense to you if I were to add a checkmark versus an x icon to the right of the command search that indicates whether or not the displayed value is the saved value?

| Icon | Meaning | Possible Values |
| ---- | ---- | ---- |
| checkmark | value shown is what is saved in the config | any valid obsidian command or an empty string |
| x | value shown is not valid and thus not saved to the config | any non-obsidian command and non-empty string |

**Comment by redactedscribe** [comment] 2023-12-11 23:15
> I believe that you said that you used Obsidian Advanced tables. Have you tried that plugin and seen if that works? I ask because I cannot attest to UI related commands as I have not tested them (they should work, but I am not sure how to test those kinds of commands unless I use them myself and know what the expected behavior is).

I do use it. And the command to format the tables does work when run by Advanced Tables command (or as a Commander command). ~~But it doesn't not work as a custom command.~~ Something very strange must've happened, or maybe the new main.js fixed it, but now it _does_ work?! I tied at least 5 times with different commands and custom commands simply wouldn't trigger. But now they do... Very odd. Tried with both pin command and format tables command, both now work...

> I am not a UI/UX designer, so I personally am better at creating functionality. As such, I am open to suggestions around how to make things clearer when a command has been added.

I believe I am decent with those topics. The majority of my lack of confidence stemmed from the fact that I thought custom commands originally worked, and then they didn't, and now they do again. That's not a UI fault, so my criticism isn't that valid any more. It is in fact clear enough: Add new command button creates a new row. Selecting a command populates the field. It's functional, even if it may lack a little in presentation.

> Would it make sense to you if I were to add a checkmark versus an x icon to the right of the command search that indicates whether or not the displayed value is the saved value?

An `X` must be present to remove the command. A checkmark could appear on the left of the field when the value is valid. That would help to indicate the selection made is now in effect.
