### ISSUE TITLE
Bug: Empty Line Around Tables breaks table when cell values are hyphens

### ISSUE THREAD

**Issue by adamhl8** [platers/obsidian-linter#1235] opened 2024-12-03 20:54 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

When `Empty Line Around Tables` is active, if you have a cell where the value is just hyphens (doesn't seem to matter how many), linting breaks the table.

## How to Reproduce

1. Paste the following into a note:

```
| test  |
|:-----:|
|  ---  | 
|  one  |
|  two  |
|  ---  |
|  ---  |
| three |
|  ---  |
|  ---  |
|  ---  |
|  ---  |
| four  |
| five  |
```

2. Run the linter.

It turns into this:

```
| test  |
|:-----:|
|  ---  |
|  one  |

|  two  |

|  ---  |
|  ---  |

| three |

|  ---  |

|  ---  |

|  ---  |
|  ---  |
| four  |
| f
i
v
e

|
```

## Device

- [x] Desktop

**Comment by pjkaufman** [comment] 2024-12-03 21:02
Hey @adamhl8 . Thanks for reporting this. This is likely caused by how tables are recognized by the Linter using regex to make parsing faster. There may be a way to fix this without greatly degrading the speed of the parsing, but this may not be feasible without doing so.

**Comment by pjkaufman** [comment] 2024-12-24 17:55
I think that I have a fix for this. The only problem I can foresee with it is that it will not allow for identifying a table if it is directly proceeded by another table which does not seem to be valid in github markdown anyways.

**Comment by pjkaufman** [comment] 2024-12-24 18:07
The changes for this should be on master and go out in the next release after 1.28.0. Please let us know if there is an issue with in either of those.

**Closed** 2024-12-24 18:06 UTC
Labels: bug, reproducible
