### ISSUE TITLE
FR: adding an "Enable/Disable" toggle for each command and regular expression rule

### ISSUE THREAD

**Issue by baoyu0** [platers/obsidian-linter#1223] opened 2024-11-15 04:55 UTC
Thank you very much, respected developers:

Feature Request: I suggest adding an "Enable/Disable" toggle for each command and regular expression rule in the custom commands and regex settings of the plugin. This toggle would allow users to activate or deactivate specific commands and rules as needed, without having to repeatedly add or delete them. By pre-configuring a set of commands or rules, I can simply enable them when needed and disable them when not in use, making the plugin more convenient and flexible to operate.

**Comment by pjkaufman** [comment] 2024-11-15 12:49
Hey @baoyu0 , would it be correct to say this is a duplicate of #1212 and #1098?

**Comment by baoyu0** [comment] 2024-11-16 06:23
Yes, that's pretty much what it means, can this feature be implemented? Will this new feature be added in the next release?

**Comment by baoyu0** [comment] 2024-11-16 06:24
> Hey @baoyu0 , would it be correct to say this is a duplicate of #1212 and #1098 with a slight expansion of scope to also include custom commands?


Yes, that's pretty much what it means, can this feature be implemented? Will this new feature be added in the next release?

**Comment by pjkaufman** [comment] 2024-11-16 11:42
Hey @baoyu0 . I can say that both features are feasible to implement. But as far as when they will get implemented, I am not sure. I am open to PRs to add this.

**Comment by pjkaufman** [comment] 2024-11-23 19:43
I believe this code change is ready to go. I made some display changes to make some things more like obsidian so I need to retake a couple of screenshots, but after that, it should be good to go up.

**Comment by pjkaufman** [comment] 2024-11-23 20:05
I have gone ahead and merged the changes for this. Please let us know if master or the next release is not working correctly with these changes.

**Closed** 2024-11-23 20:04 UTC
Labels: rule suggestion, obsidian
