### ISSUE TITLE
Bug: move-footnotes-to-the-bottom Incorrectly Changes Order of Footnotes

### ISSUE THREAD

**Issue by LloydThinks** [platers/obsidian-linter#626] opened 2023-02-07 13:33 UTC
## Describe the Bug

move-footnotes-to-the-bottom incorrectly changes the order of footnotes at the bottom when multiple footnote references to the same footnote are used.

## How to Reproduce

1. Enable the rule `move-footnotes-to-the-bottom`, and disable the rule `re-index-footnotes`.
2. Create a file with the following text:
```markdown
First,[^1] followed by the Second,[^2] and then the First[^1] again.

[^1]: First Reference
[^2]: Second reference
```
3. Run Linter.
4. The text above is changed to the following:
```markdown
First,[^1] followed by the Second,[^2] and then the First[^1] again

[^2]: Second reference
[^1]: First Reference
```

## Expected Behavior

Don't re-order the footnotes, leave them in order as 1, 2, ...

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-04-08 03:09
Thanks for reporting this issue. I don't know that the rule was designed to run with multiple footnote references in place, so that was an oversight on my part for this particular functionality. I will need to see about fixing this.

**Comment by pjkaufman** [comment] 2023-04-08 04:00
Looks like the reason for this was because of a scenario where you could add a footnote with the same footnote key in the middle of two footnotes and it needed to be moved to the end of the file in the proper location for ordering of values:
``` markdown
reference A [^1]
        ${''}
        reference C [^2]
        [^2]: footnote C (inserted between A and B)
  
        reference B [^2]

        [^1]: footnote A (first in document)
        [^2]: footnote B (last in document
```

In order to handle both scenarios, I will need to take a less simplistic route and go ahead and create a relationship between the number of times a footnote has shown up and the location of its reference in the document.

Dev note (for me later):

Currently it is a map of the footnote to its position in the markdown file. However that cannot be calculated correctly at the start and accommodate both scenarios.

Thus we will need to look up the values when we sort them to determine which one goes where.  We can take one of a couple of approaches:
- Store the amount of references to a particular index in a specific map with each reference in a map to an array of reference locations allowing us to determine if the amount of reference to the footnote index matches the amount in the array
  - if it does, then proceed with the set value
  - if not, we need to use the minimum value in the array
- We can keep a map of footnote indexes to footnote, footnote index to the amount of footnotes using that key, and a footnote index to the amount of reference locations present which would allow us to determine if we need to change any of our map values for specific footnotes

There probably is some other way that is escaping me right now as well.

When a footnote is

**Comment by pjkaufman** [comment] 2023-04-08 13:13
I believe I have a fix for this. It took a lot of trial and error, but I think this should nicely take care of the issue in question while still retaining old functionality. I also plan to tackle the other issue #625  by rewriting the logic to work more like tidy notes does. However that will have to happen a little later on either this weekend or at some other time.

**Comment by pjkaufman** [comment] 2023-04-08 13:16
This hopefully will not cause any other problems as I tried to make it mostly backwards compatible. If an issue does arise, please let us know.

**Closed** 2023-04-08 13:16 UTC
Labels: bug, footnote, reproducible

**Comment by LloydThinks** [comment] 2023-04-09 22:15
Thank you @pjkaufman ! Appears to be fixed. Thank you
