### ISSUE TITLE
Bug: Space after frontmatter is not respected when frontmatter is created

### ISSUE THREAD

**Issue by chmac** [platers/obsidian-linter#1188] opened 2024-10-09 06:26 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

When a new frontmatter block is created, the space after is not also created. This results in linting twice in a row producing different results.

## How to Reproduce

1. Ensure the "Add Blank Line After YAML" setting is enabled
2. Enable any YAML timestamp
3. Create a new note without any frontmatter
4. Lint that note
5. Observe that there is no space between the frontmatter and the content
6. Lint again

## Expected Behavior

I expect the linting to be idempotent.

## Device

- [x] Desktop
- [x] Mobile

## Additional Context

I believe this is irrespective of which rules result in the creation of frontmatter, so I skipped my whole rule config, etc.

**Comment by pjkaufman** [comment] 2024-10-10 01:56
Hey @chmac . This is expected behavior. The description of that rule says `Adds a blank line after the YAML block if it does not end the current file or it is not already followed by at least 1 blank line`. So if the file does not currently have content after the YAML frontmatter that is not whitespace, no blank line is added until some content is added after the frontmatter and the file is linted again.

**Comment by pjkaufman** [comment] 2024-10-10 01:56
Is this still an issue given the description of the rule?

**Comment by chmac** [comment] 2024-10-10 05:20
@pjkaufman I think so, yes. The situation I'm describing is starting without any YAML block, just any content in the file. Then the YAML block gets inserted, and does not have a blank line after it. From my understanding there must always be a blank line, unless the file ends after the block, which is not the case I'm describing.

For examlpe, after running the linter the first time I get this:

```
---
created_at: xxx
---
Content
```

But if I lint it immediately again, I get this:

```
---
created_at: xxx
---

Content
```

Sorry, I could have posted the example in my original issue, would have been clearer. I think the first example doesn't comply with the rule if I understood it correctly.

**Comment by pjkaufman** [comment] 2024-10-10 09:04
Ah. I see. This is another order of operations issue.

**Comment by pjkaufman** [comment] 2024-10-12 21:43
The issue is that this rule needs to run after the YAML timestamp rule if the frontmatter does not exist and before it if it does. That is a fixable problem, it just needs a little work to run that way.

**Comment by chmac** [comment] 2024-10-13 04:28
@pjkaufman Makes sense. What about running the rule twice? Don't know if that makes anything easier, was just a thought. :)

**Comment by pjkaufman** [comment] 2024-10-21 15:17
I believe I have a fix for this scenario. I am just adding one more integration test for this to make sure it is indeed working.

**Comment by pjkaufman** [comment] 2024-10-21 15:28
Looks like it passes the tests. I will go ahead and create a PR for this change.

**Comment by pjkaufman** [comment] 2024-10-21 15:43
The fix for this should be on master and go out with the next release. If there is an issue with either please let us know.

**Closed** 2024-10-21 15:43 UTC
Labels: bug, yaml, rule conflict

**Comment by chmac** [comment] 2024-10-21 17:25
@pjkaufman Thanks so much. I'm really impressed with how responsive you've been to the couple of issues I posted. Obsidian Linter makes my Obsidian experience a whole lot better, thanks. 🧡

**Comment by pjkaufman** [comment] 2024-10-21 17:48
I am glad to hear that. I can often forget about issues, so I am trying to get better at that.

Thanks for bringing up these issues! The more issues that are fixed, the better the Linter can be.
