### ISSUE TITLE
IOS message "An error occurred during linting. See console for details"

### ISSUE THREAD

**Issue by gdigesu** [platers/obsidian-linter#367] opened 2022-08-20 05:09 UTC
### Is Your Feature Request Related to a Problem? Please Describe.

On IOS 15.6.1, and iPad OS 15.6.1, I get the above message every time I run Linter.

### Describe the Solution You'd Like

Linter did work fine on IOS.
Can you help?

**Comment by pjkaufman** [comment] 2022-08-20 13:01
It may be some of the negative lookaheads in the regex. But since I don't have an ios device I cannot confirm.

**Comment by pjkaufman** [comment] 2022-08-20 13:09
If you edit the `data.json` file to have the loglevel of 1, what rule seems to have the problem?

You will also likely need a developer tools plugin to help you see the console on ios.

The `data.json` is located at `path_to_vault/.obsidian/plugins/obsidian-linter/`.

**Comment by gdigesu** [comment] 2022-08-20 15:57
> It may be some of the negative lookaheads in the regex. But since I don't have an ios device I cannot confirm.

I am not technically qualified to solve it.

Maybe in the future you'll solve it.
It is a great plugin, and it would be great to have it on IOS and iPad OS.

Thanks for your prompt reply.

**Comment by pjkaufman** [comment] 2022-08-20 16:18
If you know what rules you have active I might be able to figure out which ones could be the problem.

**Comment by gdigesu** [comment] 2022-08-20 16:59
> If you know what rules you have active I might be able to figure out which ones could be the problem.

Sure. Here they are:

- Display the number of characters changed after linting
- Insert the given YAML attributes into the YAML frontmatter. Put each attribute on a single line. Text to insert  
  - date created
  - date modified
- Keep track of the date the file was last edited in the YAML front matter.
- Date create
- Date modified
- Move all footnotes to the bottom of the document
- Make sure that two spaces are added to the ends of lines with content continued on the next line for paragraphs, ...
- Ensure that there is an empty line around github flavored tables ...
- All heading have a blank line ...
- Bottom ...
- Ensures that there is exactly one line break at the end of a document

**Comment by jandamm** [comment] 2022-08-31 21:07
I have the same issue.

This is the log:
```
runLinterEditora
a
yH@capacitor:/localhost/app.js:1:1672622
@capacitor://localhost/app.js:1:1719007
@capacitor://localhost/app.js:1:1522764
@capacitor://localhost/app.js:1:1522320
@capacitor://localhost/app.js:1:1402648
@capacitor://localhost/app.js:1:1402385
@native code]
s@capacitor:/
localhost/enhancejs:1:8736
```

**Comment by pjkaufman** [comment] 2022-08-31 22:12
I am looking at the regex to see if I can correct any of this. I will have no way of knowing until the next release if it is fixed for you both. A lot of rules use negative lookaheads, so without a list of rules that are being used it will be a gradual change so it might not get fixed all at once.

**Comment by pjkaufman** [comment] 2022-08-31 23:05
The list of places that negative lookaheads are used in the rules:

- [ ] `footnote-after-punctuation`
  - may not be able to fix
- [ ] `no-bare-urls`
- [ ] `re-index-footnotes`
  - may not be able to fix
- [ ] `remove-empty-lines-between-list-markers-and-checklists`
- [ ] `remove-multiple-spaces`
- [x] Anywhere that ignores yaml:
  - trying to get disabled rules (runs by default (this is the likely culprit for everyone since this always runs now)
  - `heading-blank-lines`
  - `insert-yaml-attributes`
  - `remove-yaml-keys`
  - `yaml-key-sort`
  - `yaml-title-alias`
  - etc.

I seem to be able to fix the yaml regex easily without breaking any UTs. So that should be fine. The other places like footnotes may not be something I can get working for iOS as it seems that the negative lookaheads are needed for the identification of the footnotes to work properly. This leaves the other areas which I should be able to shore up for this coming release (hopefully Friday or Saturday).

**Comment by pjkaufman** [comment] 2022-08-31 23:06
However I am also not yet certain that fixing the negative lookahead will fix the issue for users. So I cannot promise anything at this time.

**Comment by pjkaufman** [comment] 2022-08-31 23:08
The issue does appear to be with negative lookaheads being in the yaml regex which would be why no rules are listed as having run in the logs listed. But that is me assuming that console log output is what the logs you are referring to are, @jandamm .

**Comment by pjkaufman** [comment] 2022-09-01 21:53
Seems I was incorrect about the above scenarios and negative lookbehinds. Negative lookbehinds are not supported on iOS, but that does not seem to be the problem here. I will go ahead and check the other regexes for issues.

**Comment by jandamm** [comment] 2022-09-02 06:09
@pjkaufman I can test a commit so you don't have to make a full release.

For me it broke with `1.4.x`. I had this issue with `1.3.6` but was able to get it working by disabling yaml key sorting.
So your idea could be right.

**Comment by pjkaufman** [comment] 2022-09-02 11:49
I found the negative lookbehind. But I am not sure I can just go ahead and update it. I see why some things started breaking with `1.3.6` and `1.4.x`. Now I just need to figure out how to update it to not use a negative lookbehind.

**Comment by pjkaufman** [comment] 2022-09-02 11:50
Looks like it is not supported on iOS, so I will see about updating it. Here is to hoping it is a simple fix.

**Comment by pjkaufman** [comment] 2022-09-02 13:55
I think I have a fix for the positive lookbehind usage, but I won't be able to create it until later today.

**Comment by jandamm** [comment] 2022-09-02 15:12
If you tell me which rule has a positive and which one a negative lookbehind i could run both rules and see which fails.

**Comment by pjkaufman** [comment] 2022-09-02 16:09
Try truning off all lint rules and then run it. If it fails, it is the get helper method that uses the positive lookahead.

**Comment by jandamm** [comment] 2022-09-02 20:13
I've turned everything off and I still get the same error 🤔

**Comment by pjkaufman** [comment] 2022-09-02 20:16
Gotcha. Then it is likely the logic I am creating a PR to update. It gets run no matter what since it tries to determine if any rules are expressly disabled before it tries to run any rules (this prevents rules that were previously run before the disable check to run even when disabled by the file yaml).

**Comment by pjkaufman** [comment] 2022-09-02 20:41
@jandamm , could you try it with what I just pushed to master on this repo and let me know if the issue still persists?

**Comment by pjkaufman** [comment] 2022-09-02 21:45
Here it is: 
[main.zip](https://github.com/platers/obsidian-linter/files/9481188/main.zip)

**Comment by jandamm** [comment] 2022-09-03 07:35
Yes this is working with the settings I had before.
Even `yaml key sort` didn't produce an error which previously errored.
But the output was broken:

```
---
aliases: 
tags: 
---
```
became
```
---
: 
aliasestags: 
---
```

**Comment by pjkaufman** [comment] 2022-09-03 09:02
Coukd you provide your yaml key sort rule info? I did not encounter that issue, but I may not be using that rule as much.

**Comment by jandamm** [comment] 2022-09-03 09:30
This is my current config:
```
{
  "ruleConfigs": {
    "Escape YAML Special Characters": {
      "Escapes colons with a space after them (: ), single quotes ('), and double quotes (\") in YAML.": false,
      "Default Escape Character": "\"",
      "Try to Escape Single Line Arrays": false
    },
    "Format Tags in YAML": {
      "Remove Hashtags from tags in the YAML frontmatter, as they make the tags there invalid.": true
    },
    "Format Yaml Array": {
      "Allows for the formatting of regular yaml arrays as either multi-line or single-line and `tags` and `aliases` are allowed to have some Obsidian specific yaml formats. Note that single string to single-line goes from a single string entry to a single-line array if more than 1 entry is present. The same is true for single string to multi-line except it becomes a multi-line array.": false,
      "Yaml aliases section style": "single-line",
      "Format yaml aliases section": true,
      "Yaml tags section style": "single-line",
      "Format yaml tags section": true,
      "Default yaml array section style": "single-line",
      "Format yaml array sections": true,
      "Force key values to be single-line arrays": "",
      "Force key values to be multi-line arrays": ""
    },
    "Insert YAML attributes": {
      "Inserts the given YAML attributes into the YAML frontmatter. Put each attribute on a single line.": true,
      "Text to insert": "aliases: \ntags: "
    },
    "Remove YAML Keys": {
      "Removes the YAML keys specified": false,
      "YAML Keys to Remove": ""
    },
    "YAML Key Sort": {
      "Sorts the YAML keys based on the order and priority specified. Note: removes blank lines as well.": true,
      "YAML Key Priority Sort Order": "",
      "Priority Keys at Start of YAML": true,
      "YAML Sort Order for Other Keys": "Ascending Alphabetical"
    },
    "YAML Timestamp": {
      "Keep track of the date the file was last edited in the YAML front matter. Gets dates from file metadata.": false,
      "Date Created": true,
      "Date Created Key": "date created",
      "Date Modified": true,
      "Date Modified Key": "date modified",
      "Format": "dddd, MMMM Do YYYY, h:mm:ss a"
    },
    "YAML Title": {
      "Inserts the title of the file into the YAML frontmatter. Gets the title from the first H1 or filename if there is no H1.": false,
      "Title Key": "title"
    },
    "YAML Title Alias": {
      "Inserts the title of the file into the YAML frontmatter's aliases section. Gets the title from the first H1 or filename.": false,
      "YAML aliases section style": "Multi-line array",
      "Preserve existing aliases section style": true,
      "Keep alias that matches the filename": false
    },
    "Capitalize Headings": {
      "Headings should be formatted with capitalization": true,
      "Style": "Title Case",
      "Ignore Cased Words": true,
      "Ignore Words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript",
      "Lowercase Words": "via, a, an, the, and, or, but, for, nor, so, yet, at, by, in, of, on, to, up, as, is, if, it, for, to, with, without, into, onto, per"
    },
    "File Name Heading": {
      "Inserts the file name as a H1 heading if no H1 heading exists.": false
    },
    "Header Increment": {
      "Heading levels should only increment by one level at a time": false
    },
    "Footnote after Punctuation": {
      "Ensures that footnote references are placed after punctuation, not before.": false
    },
    "Move Footnotes to the bottom": {
      "Move all footnotes to the bottom of the document.": false
    },
    "Re-Index Footnotes": {
      "Re-indexes footnote keys and footnote, based on the order of occurrence (NOTE: This rule deliberately does *not* preserve the relation between key and footnote, to be able to re-index duplicate keys.)": false
    },
    "Convert Bullet List Markers": {
      "Converts common bullet list marker symbols to markdown list markers.": true
    },
    "Emphasis Style": {
      "Makes sure the emphasis style is consistent.": true,
      "Style": "underscore"
    },
    "No Bare URLs": {
      "Encloses bare URLs with angle brackets except when enclosed in back ticks, square braces, or single or double quotes.": false
    },
    "Proper Ellipsis": {
      "Replaces three consecutive dots with an ellipsis.": false
    },
    "Remove Consecutive List Markers": {
      "Removes consecutive list markers. Useful when copy-pasting list items.": false
    },
    "Remove Empty List Markers": {
      "Removes empty list markers, i.e. list items without content.": false
    },
    "Remove Hyphenated Line Breaks": {
      "Removes hyphenated line breaks. Useful when pasting text from textbooks.": false
    },
    "Remove Multiple Spaces": {
      "Removes two or more consecutive spaces. Ignores spaces at the beginning and ending of the line. ": false
    },
    "Strong Style": {
      "Makes sure the strong style is consistent.": true,
      "Style": "asterisk"
    },
    "Two Spaces Between Lines with Content": {
      "Makes sure that two spaces are added to the ends of lines with content continued on the next line for paragraphs, blockquotes, and list items": false
    },
    "Compact YAML": {
      "Removes leading and trailing blank lines in the YAML front matter.": false,
      "Inner New Lines": true
    },
    "Consecutive blank lines": {
      "There should be at most one consecutive blank line.": true
    },
    "Convert Spaces to Tabs": {
      "Converts leading spaces to tabs.": false,
      "Tabsize": 4
    },
    "Empty Line Around Code Fences": {
      "Ensures that there is an empty line around code fences unless they start or end a document.": false
    },
    "Empty Line Around Tables": {
      "Ensures that there is an empty line around github flavored tables unless they start or end a document.": true
    },
    "Heading blank lines": {
      "All headings have a blank line both before and after (except where the heading is at the beginning or end of the document).": true,
      "Bottom": true,
      "Empty Line Between Yaml and Header": true
    },
    "Line Break at Document End": {
      "Ensures that there is exactly one line break at the end of a document.": false
    },
    "Paragraph blank lines": {
      "All paragraphs should have exactly one blank line both before and after.": false
    },
    "Remove Empty Lines Between List Markers and Checklists": {
      "There should not be any empty lines between list markers and checklists.": false
    },
    "Remove link spacing": {
      "Removes spacing around link text.": true
    },
    "Remove Space around Fullwidth Characters": {
      "Ensures that fullwidth characters are not followed by whitespace (either single spaces or a tab). Note that this may causes issues with markdown format in some cases.": false
    },
    "Space after list markers": {
      "There should be a single space after list markers and checkboxes.": true
    },
    "Space between Chinese and English or numbers": {
      "Ensures that Chinese and English or numbers are separated by a single space. Follow this [guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)": false
    },
    "Trailing spaces": {
      "Removes extra spaces after every line.": true,
      "Two Space Linebreak": false
    }
  },
  "lintOnSave": true,
  "displayChanged": true,
  "foldersToIgnore": [
    "@Templates"
  ],
  "linterLocale": "system-default",
  "logLevel": 4
}
```

**Comment by pjkaufman** [comment] 2022-09-03 19:34
I will see if I can reproduce the issue with the sort. If I can I will fix it and then go ahead with the release. I am hoping to work more on warning mode this coming week. So knocking out all of these bugs will put me in a good place to focus on that.

**Comment by pjkaufman** [comment] 2022-09-03 19:36
I can reproduce. Hopefully this will be a simple fix. It was working prior to the regex change if my memory serves.

**Comment by pjkaufman** [comment] 2022-09-03 20:03
I think I have spotted the issue, but it may take me a little while to find the root cause. It seems that it thinks there is an empty string as the sole element that is meant to be the priority sort order key and that is causing wonkiness.

**Comment by pjkaufman** [comment] 2022-09-03 20:17
I think I have that issue fixed. I will push up a PR and then include the `main.js` here. It should be smaller than the last one as I made some improvements to the build script. Hopefully that did not include messing any rules up since all the UTs pass and nothing seems broken in my own vault.

**Comment by pjkaufman** [comment] 2022-09-03 20:32
@jandamm , could you try the following file and let me know if the issue is fixed? I am pretty sure the issue with weird sort output should be resolved with the change. Once I get confirmation that it is fixed, I will go ahead and create a release.
Here is the main.js:
[main.zip](https://github.com/platers/obsidian-linter/files/9483342/main.zip)

**Comment by jandamm** [comment] 2022-09-03 21:50
Yes, this does work 🎉

**Comment by pjkaufman** [comment] 2022-09-03 22:58
Great! I will make a release either later today or some time tomorrow. Thanks for helping test this @jandamm !

**Comment by pjkaufman** [comment] 2022-09-04 15:54
I will go ahead and close this issue as it seems to have been fixed by changes that are now on master and should be put into a release soon. If master or the next release still has this issue, feel free to reopen this issue. Thanks for reporting this!

**Closed by pjkaufman** 2022-09-04 15:54 UTC
Labels: bug, help wanted
