### ISSUE TITLE
Bug: stuck on turkish localization 

### ISSUE THREAD

**Issue by arblib** [platers/obsidian-linter#917] opened 2023-10-23 11:35 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

My default system language is uk (ukrainian), when I enable Linter it is stuck on turkish localization, choosing other languages in setup menu does not have any effect, still turkish.

## Screenshots

![image](https://github.com/platers/obsidian-linter/assets/24988364/91dc82ab-d3d7-4659-963b-faa84475e39c)

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-10-23 11:44
Hey @arblib . I eill have to take a look and see wjat is going on with this since I believe the locale strings are different for these 2 languages. It may be a couple days before I can actually take a look, but hopefully this will get resolved in the next update.

**Comment by pjkaufman** [comment] 2023-10-23 12:00
I am able to reproduce this on my end, so I need to figure out why uk is getting mapped to Turkish.

**Comment by pjkaufman** [comment] 2023-10-23 12:04
Well. I found the issue really quickly. It was a bad import. I will have to make a PR for this and get a patch out shortly (I will see about doing it today or tomorrow). Thanks for reporting this @arblib !

**Comment by pjkaufman** [comment] 2023-10-23 12:14
I am merging the change into master. Please let us know if there is an issue on master or the next release (I plan to make a bug fix release tonight or tomorrow).

**Closed** 2023-10-23 12:14 UTC
Labels: bug, reproducible
