### ISSUE TITLE
Bug: regex problem

### ISSUE THREAD

**Issue by dbobak** [platers/obsidian-linter#588] opened 2023-01-14 22:18 UTC
In Custeom Regex Replacement section I'm trying to convert HTML links to markdown links with that regex:

find: `<a.*?href=["']([^"']*)["'][^>]*>([^<]*)<\/a>` `igm` `[$2]($1)`

Generally it works, but sometimes it fails, for example in this case:

```
Wycinek utworzono z: <a href="https://www.tygodnikpowszechny.pl/zycie-pod-mikroskopem-151274" class="tc-tiddlylink-external" rel="noopener noreferrer" target="_blank">https://www.tygodnikpowszechny.pl/zycie-pod-mikroskopem-151274</a>
```
the link is converted to:

```
Wycinek utworzono z: <a href="https://www.tygodnikpowszechny.pl/zycie-pod-mikroskopem-151274" class="tc-tiddlylink-external" rel="noopener noreferrer" target="_blank"><https://www.tygodnikpowszechny.pl/zycie-pod-mikroskopem-151274</a>>
```

When testing in [https://regexr.com/](https://regexr.com/), my regex works fine.

**Comment by pjkaufman** [comment] 2023-01-26 00:10
This seems interesting. I am not sure what is going on here, but I need to check the regex and make sure it doesn't need any escaping in it.

**Comment by pjkaufman** [comment] 2023-01-26 00:16
The following is what I got when I added the custom regex you provided as a custom regex replacement:
```markdown
Wycinek utworzono z: [https://www.tygodnikpowszechny.pl/zycie-pod-mikroskopem-151274](https://www.tygodnikpowszechny.pl/zycie-pod-mikroskopem-151274)
```

This looks correct to me. @dbobak, could you provide your whole `data.json` file so I can attempt to reproduce the issue with all of the rules you normally have on? It is likely one of them is causing something to be converted in a weird way so the regex no longer matches.

**Comment by dbobak** [comment] 2023-01-26 14:31
Yes, of course:

[data.json.zip](https://github.com/platers/obsidian-linter/files/10510198/data.json.zip)

**Comment by pjkaufman** [comment] 2023-01-27 19:21
I am able to reproduce. If I had to guess, you have No Bare URLs turned on which is not really good at figuring out when a link is in an anchor tag already. I will take a closer look and see if that rules is on and if turning it off will fix the issue. If so, I may need to think up a way around this issue.

**Comment by pjkaufman** [comment] 2023-01-27 19:32
I may have a fix for this. I just need to test it out and if it works. I will merge it in for next release.

**Comment by pjkaufman** [comment] 2023-01-27 19:34
Looks like my fix works with your config. I will push it up and see how it goes.

**Closed** 2023-01-27 19:43 UTC
Labels: bug

**Comment by pjkaufman** [comment] 2023-01-27 19:45
The fix for this should be on master and in the next release. Please let us know if that is not the case.

**Comment by dbobak** [comment] 2023-01-29 13:57
@pjkaufman, I confirm that this is No Bare URLs problem. After turning off that option, the regex works as expected. If the new release will be published, I'll let know if the fix is working for me. Thanks!
