### ISSUE TITLE
Bug: i can't insert yaml by using linger

### ISSUE THREAD

**Issue by Christtj14** [platers/obsidian-linter#1104] opened 2024-06-19 02:03 UTC
i was doing fine before i reinstall my system. and my loptop are doing fine on obsidna 1.5.14. in some reason，my pc that reinstall one just can using obsidna 1.4.16 and  it can't making linter work properly, i type the hotkey ctrl+alt+l , not thing happend.

**Comment by pjkaufman** [comment] 2024-06-19 02:07
Hey @Christtj14 , could you provide more details? For example, could you provide your `data.json` as well as how you set the hotkey for `ctrl+alt+l` since I don't think the latter is a default keybinding for the Linter?

**Comment by pjkaufman** [comment] 2024-06-19 11:34
I see where the keybinding is for `ctrl+alt+L` is listed, but I am not sure if that is case insensitive.

**Comment by pjkaufman** [comment] 2024-06-19 11:44
Also, note that obsidian 1.6.3 is the latest for Obsidian. Anything prior to a couple of the most recent versions will be hard to debug for me, but I can work with you to see if there are other issues that may be causing the problem for you.

**Comment by pjkaufman** [comment] 2024-06-24 11:59
I plan to close this issue Wednesday if I do not hear back on steps to reproduce or at least the `data.json` to try reproducing with by then.

**Comment by pjkaufman** [comment] 2024-06-27 00:48
I am closing this since I have not heard anything back to help debug this issue.

**Closed by pjkaufman** 2024-06-27 00:48 UTC
Labels: bug, resolution/not-enough-information
