### ISSUE TITLE
FR: Start at H2 rather than H1 (due to Obsidian 1.0: Show inline title)

### ISSUE THREAD

**Issue by sbibauw** [platers/obsidian-linter#451] opened 2022-10-13 21:30 UTC
## Related to...

With version 1.0 of Obsidian default option "Show inline title", the filename appears as H1.
This tends to make internal titles too big if they are H1 (seem hierarchically identical to filename). 

## Solution

In _Settings_ > _Heading_ > _File Name Heading_ OR _Header Increment_:
Add an option (checkbox) to start headings at level H2 rather than H1.

**Example of expected result:**

``` markdown
# Section 1
## Subsection 1.1
```

gets linted/changed into

``` markdown
## Section 1
### Subsection 1.1
```

## Partially related additional suggestion:

Eventually, consider also an option to **Remove** Heading1 if == to Inline title :

``` markdown
filename: The Title
# The Title
## Section 1
### Subsection 1.1
```

gets changed into:

``` markdown
filename: The Title
## Section 1
### Subsection 1.1
```

**Comment by pjkaufman** [comment] 2022-10-13 22:15
Thanks for the suggestion. This seems to be related to if not a duplicate of #412 .

**Comment by pjkaufman** [comment] 2022-10-13 22:16
Is there a particular reason to not merge the contents of tge 2 requests?

**Comment by sbibauw** [comment] 2022-10-14 18:38
Indeed, it's a duplicate of #412. Sorry, my search on previous issues was done with "Show inline title" and I didn't realize it was already brought up.

**Closed** 2022-10-14 18:38 UTC
Labels: duplicate, rule suggestion
