### ISSUE TITLE
Minor Visual Bug: Labels mixed up

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#710] opened 2023-05-08 17:03 UTC
"footnote settings" and "content settings" are mixed up, it should be the other way round
![CleanShot 2023-05-08 at 19 01 45@2x](https://user-images.githubusercontent.com/73286100/236885640-90db7e6b-bd74-4ba1-9d26-3e5449d3badc.png)
![CleanShot 2023-05-08 at 19 01 36@2x](https://user-images.githubusercontent.com/73286100/236885647-f1de2d78-145e-46cc-934e-f32a4bfcaf27.png)

**Comment by pjkaufman** [comment] 2023-05-08 19:17
Thanks for pointing this out. I will have to check what the issue is. It is likely one of the following:
- Wrong yaml type filtered on in the rule tab
- Wrong hedaer text in the language support file
- Wrong key mapping in the header to language key map

**Comment by pjkaufman** [comment] 2023-05-08 19:19
These 2 lines need to have their values swapped: https://github.com/platers/obsidian-linter/blob/master/src/lang/locale/en.ts#L108-L109

**Comment by pjkaufman** [comment] 2023-05-13 18:44
This should be fixed on master and in the next release. Please let us know if that is not the case.

**Closed** 2023-05-13 18:44 UTC
