### ISSUE TITLE
FR: Enabling personal additions to auto-correction map

### ISSUE THREAD

**Issue by MPica** [platers/obsidian-linter#1108] opened 2024-06-27 12:46 UTC
## Feature request: being able to add auto-correction rules

MO Word and LO Writer have this "auto-correction options" menu, which allows the user to add personal rules, which is extremely useful when taking notes in a live event: I add abbreviations, shortcuts, like "WW2" to "Second World War". I would love to have a similar possibility in Obsidian.

## A 'personal' autocorrect map?

Could a personal **auto-correction map** like [this one](https://github.com/platers/obsidian-linter/tree/master/src/utils/auto-correct-misspellings.ts) be available in the `[vault]/.obsidian/plugins/obisdian-linter` folder, and modifiable from the "content" tab?
It would mean the personal abbreviations would remain personal, within the vault itself.

I'm a data person, so I have no other alternative in mind, and if you can't do it, you can't. ^-^ But the RegEx tool seems a bit heavy for simple string replacements.

All the best,

**Comment by pjkaufman** [comment] 2024-06-28 20:47
Hey @MPica , I believe this is pretty similar to #866 . Could you elaborate on how this would be different or is it ok if I close this as a duplicate of the other ticket?

**Comment by MPica** [comment] 2024-06-29 09:13
Hi and thank you! This solves it, you can close it as a duplicate.
It's easy to get lost in issues, I probably just didn't type the right keywords when I searched. Apologies.

**Comment by pjkaufman** [comment] 2024-06-30 20:21
I will go ahead and close this. No worries about it being similar. There are a decent bit of open issues and I can find it hard to find issues hard sometimes as well.

**Closed by pjkaufman** 2024-06-30 20:21 UTC
Labels: duplicate, rule suggestion
