### ISSUE TITLE
Android - unable to load Linter

### ISSUE THREAD

**Issue by johans3** [platers/obsidian-linter#139] opened 2021-11-05 18:59 UTC
I use your plugin on my computer, everything works flawlessly.
But I am unable to load *Linter* on my **Android phone**
I get the error
`Failed to load plugin-obsidian linter`

**Comment by platers** [comment] 2021-11-05 20:39
I havn't used mobile at all, not sure what needs to be done to get it working, help appreciated!

**Comment by johans3** [comment] 2021-11-07 09:44
All I know for now is, you've to set a flag to allow usage on phones but I need more precise information

**Comment by platers** [comment] 2021-12-09 23:11
I just tried it out on my phone, it works for me. The UI can be improved, but I dont see that error.

**Comment by johans3** [comment] 2021-12-10 16:18
![Screenshot_20211210_171500](https://user-images.githubusercontent.com/48620536/145605835-c491b6eb-6056-455a-ab29-fc1c8abc3739.jpg)

On mobile, I have tried to re-install your plugin several times because Linter is very useful. 
I don't have issues with other plugins which are compatible with mobile

**Comment by pjkaufman** [comment] 2022-05-25 02:53
@johans3 , could you give some more specific information like the OS or what version of linter you are trying to install? I do not seem to have this problem myself and I use Android 8.0.0.

Without this information, I will be forced to close this issue.

**Comment by pjkaufman** [comment] 2022-06-03 09:11
Due to a lack of reproducibility and the fact that I have been provided no extra information, I am going to close this issue.

**Closed by pjkaufman** 2022-06-03 09:11 UTC
Labels: help wanted
