### ISSUE TITLE
Bug: Order List Number

### ISSUE THREAD

**Issue by seyeeL** [platers/obsidian-linter#422] opened 2022-09-20 01:33 UTC
``` markdown
1. 项目 A
	1. 类别一
	2. 类别二
		1. [ ] XXX
			1. [ ] XXX
		3. [ ] XXX
2. 项目 B
	1. 类别一
	2. 类别二
		1. XXX
			1. XXX
		1. XXX
		1. XXX
    1. 发几封积分积分
	1. 类别一
	2. 类别二
		1. XXX
			1. XXX
		1. XXX
		1. XXX
3. 发几封积分积分3. 项目 B
	1. 类别一
	2. 类别二
		1. XXX
			1. XXX
		1. XXX
		1. XXX
    2. 发几封积分积分
```

**Comment by pjkaufman** [comment] 2022-09-22 00:18
I am looking at this and it may be that it is coming back as multiple different lists which could be the problem. But if that is the case, I am not really able to address this. I am going to go ahead and try something with an English list and see if I have the same problems.

**Comment by pjkaufman** [comment] 2022-09-22 00:27
I am seeing something weird where I am getting multiple lists back in the result set, but it looks like they are all covered by the first list. I will see if I can reduce the result set which should fix part of the issue with reording the values. But I am not too sure it will fix all of the issues since I think there is an issue with sublists not actually properly updating if indented the same.

**Comment by pjkaufman** [comment] 2022-09-22 01:12
Based on what is stated here, I am not 100% certain of what the issue is, but I believe that I have a fix. I am looking to see if this is caused by using tabs instead of spaces. But I am pretty sure I have the sublist issue resolved. It should now assume that 1 tab is the same as one indentation level which will be assumed to be 2 spaces.

**Comment by pjkaufman** [comment] 2022-09-22 01:22
I found an issue in the regex I had missed prior that said that tabs needed to be followed by a space to be counted as a part of the  list marker info, so I think removing that should making things work more smoothly with tabs.

**Comment by pjkaufman** [comment] 2022-09-22 01:30
I will push up my changes. They should fix any issues you were seeing with this around tabs or with multiple sublists at the same indentation level not starting off at 1 again.

**Comment by pjkaufman** [comment] 2022-09-22 01:37
Sorry about any confusion around this. I was pretty confused when I saw the list provided as it looked like several things I had not accounted for. Thankfully it was just 2 separate issues with one being an easy fix and the other being an oversight.

This should be fixed on master. I plan to push out a bug fix for this later this week. Please let us know if this issue persists on master or in the next release.

**Closed by pjkaufman** 2022-09-22 01:37 UTC
Labels: bug, markdown
