### ISSUE TITLE
Bug: Unable to parse url correctly

### ISSUE THREAD

**Issue by YunshuaiPeng** [platers/obsidian-linter#1103] opened 2024-06-17 03:32 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Unable to parse the url: https://www.cs.cmu.edu/~213/

## How to Reproduce

1. input `https://www.cs.cmu.edu/~213/`
2. run formatting
3. you can see the text becomes: `<https://www.cs.cmu.edu/>~213/`

## Expected Behavior

The text should be becomes: `<https://www.cs.cmu.edu/~213/>`

## Device

Desktop

## Additional Context

Linter version: 1.24.0
Obsidian version: 1.6.3 (Installer 1.4.16)

**Comment by pjkaufman** [comment] 2024-06-17 11:45
Hey @YunshuaiPeng , I believe this is a duplicate of #1084 which has a fix available in the beta version (1.25.0-rc-1) which is available via BRAT.

**Comment by pjkaufman** [comment] 2024-06-28 21:10
I am going to close this since I have verified that it is fixed in the beta version I mentioned above. Please consider using that version or waiting until it is released in a non-beta version.

**Closed by pjkaufman** 2024-06-28 21:10 UTC
Labels: bug, duplicate
