### ISSUE TITLE
Bug: Header capitalization capitalizes words after words that contain numbers

### ISSUE THREAD

**Issue by mps75** [platers/obsidian-linter#601] opened 2023-01-27 01:22 UTC
## Describe the Bug

When header capitalization is selected ("first letter" style) and there's an acronym or word that contains a number the next word will be capitalized

## How to Reproduce

Examples to reproduce issue with

``` markdown
# EC2 instance
## EC2 lab05 load balancer
### lab07 bread maker
```

The result of the above markdown is:

```markdown
# EC2 Instance

## EC2 lab05 Load balancer

### lab07 Bread maker
```

(Instance, Load, and Bread are incorrectly capitalized)

Expected output if applicable:

``` markdown
# EC2 instance

## EC2 lab05 load balancer

### Lab07 bread maker
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-01-27 04:58
This looks like a simple fix. I will give it a shot. The problem is that technically speaking numbers are not a part of words which is why capitalization did not work on them. I can make it more relaxed and see how it handles them.

**Comment by pjkaufman** [comment] 2023-01-27 05:03
You will need to ignore case or add the acronyms in question to the ignore list or else the 2nd letter of the acronym will be converted to a lowercase letter (just an FYI).

**Comment by pjkaufman** [comment] 2023-01-27 05:22
This should be fixed on master and in the next release. Please let us know if that is not the case.

**Closed** 2023-01-27 05:21 UTC
Labels: bug, markdown
