### ISSUE TITLE
FR: Format YAML Arrays

### ISSUE THREAD

**Issue by ScottKillen** [platers/obsidian-linter#291] opened 2022-07-15 20:09 UTC
I would like a feature that unwraps yaml collections in frontmatter (per example 2.3 [here](https://yaml.org/spec/1.2.2/#21-collections)). This was an option on an older obsidian linter.

Example:

```
---
tags: [red, yellow, green]
aliases: [Note, 'Note , Comma', BigNote]
===
```

would convert to:

```
---
tags:
  - red
  - yellow
  - green
aliases:
 - Note
 - Note , Comma
 - BigNote
---
```

The [dataview plugin](https://github.com/blacksmithgu/obsidian-dataview) allows arbitrary fields in frontmatter, so this functionality would not be limited to fields recognized by Obsidian. (Perhaps there would be an option to list the fields that should be unwrapped)

## Describe Alternatives You've Considered

I have not been able to think of any alternatives other than manually doing this.

**Comment by pjkaufman** [comment] 2022-07-15 20:44
Thanks for this feature request @ScottKillen . This is something I have considered working on in the past. I think this should be made more generic and allow for yaml attributes that are lists to be setup to convert values to one of 3 types:
1. Single line array (i.e. `key: [...]`)
2. Multiline array (i.e. `key:\n  - ...`)
3. Single line value (i.e. `key: ...`). The latter would only be possible for `tags` and `aliases` as they are special.

I am not sure that that this has ever been a feature of Obsidian Linter, but it would be a welcome addition that I can see being useful for may users including myself.

**Comment by ScottKillen** [comment] 2022-07-15 20:58
I know it was never a feature of this project...but somewhere in my distant memory, I seem to remember some other plugin with this feature.

It could be that I ran a tool outside of Obsidian to do this, but I have some ancient notes that bear the results of whatever I did. 😉

**Comment by pjkaufman** [comment] 2022-07-15 21:01
Gotcha. I thought you were saying Obsidian Lint did makw these kinds of changes prior. I will see what can be done around this.

**Comment by pjkaufman** [comment] 2022-07-15 21:57
Note: this is a partial duplicate of #182 .

**Comment by pjkaufman** [comment] 2022-07-15 22:26
@ScottKillen , are those formats you posted valid for Obsidian? I am asking since it looks as though they are not following a valid YAML format for an array.

**Comment by pjkaufman** [comment] 2022-07-15 22:35
It looks like I will need to hold off on this in favor of a refactor that is being worked on to allow it to go through prior to this. However this will give time to think about how to best handle the code and not create a rushed solution in a matter of hours. I hope to be able to include this in the next release after the one today which will likely be two weeks from now.

**Comment by pjkaufman** [comment] 2022-07-15 22:57
Seems to also take care of https://github.com/platers/obsidian-linter/issues/172 as well.

**Comment by ScottKillen** [comment] 2022-07-16 03:08
Better to take the time to do it right!

I corrected my examples because you are right—they were not in proper format—though it looks like #172 wants linter to correct issues like this.

**Closed** 2022-08-13 16:28 UTC
Labels: rule suggestion, yaml

**Comment by pjkaufman** [comment] 2022-08-13 16:31
I believe this should now be possible on master. I plan to release it later today. I believe I have worked out several of the blatant issues with it when inspecting how it affected my local notes. Please let us know if master or the next release does not allow for the desired formatting.

@ScottKillen , this took a bit longer than expected, but hopefully most of the bugs are ironed out now.

**Comment by ScottKillen** [comment] 2022-08-13 20:17
@pjkaufman  Thanks for the effort!

**Comment by pjkaufman** [comment] 2022-08-13 20:24
No problem.
