### ISSUE TITLE
Bug: issues with reordering of footnotes

### ISSUE THREAD

**Issue by olearydj** [platers/obsidian-linter#314] opened 2022-07-26 15:21 UTC
## Describe the Bug

When using Linter to re-index and consolidate footnotes at the end of a document, I commonly see the consolidated footnotes listed out of order and associated with the incorrect label. This occurs when inserting new footnotes between existing ones. See repro steps.

## How to Reproduce

Create a file containing the following.
This simulates creating references to A and B in order, with corresponding footnotes consolidated at the end of the note, then inserting reference C between them.

``` markdown
reference A [^1]

reference C [^2]
[^2]: footnote C (inserted between A and B)

reference B [^3]

[^1]: footnote A (first in document)
[^2]: footnote B (last in document)
```

When linted this results in the following. Note that C is listed first, and all references are incorrect:

```markdown
reference A [^1]

reference C [^2]
reference B [^3]

[^1]: footnote C (inserted between A and B)
[^2]: footnote A (first in document)
[^3]: footnote B (last in document)
```

Rules are attached: [data.json.zip](https://github.com/platers/obsidian-linter/files/9191046/data.json.zip)
Software, plugins, and theme (shimmering focus) are current (version and installer 0.15.8).

## Expected Behavior
Footnotes should be listed in correct order with corresponding references.

Expected output if applicable:

``` markdown
reference A [^1]

reference C [^2]
reference B [^3]

[^1]: footnote A (first in document)
[^2]: footnote C (inserted between A and B)
[^3]: footnote B (last in document)
```

## Screenshots
<img width="726" alt="image" src="https://user-images.githubusercontent.com/42705243/181045331-51792b91-f58a-4e21-93af-3f8652beaa2b.png">

## Device

- [X] Desktop
- [ ] Mobile

## Additional Context

N/A

**Comment by pjkaufman** [comment] 2022-07-27 11:24
Thanks for reporting this. This definitely seems odd. Hopefully it will not be too odd when it comes to how this is being caused in the code.

**Comment by pjkaufman** [comment] 2022-07-30 22:27
@olearydj, to make sure I understand what the issue is, you are saying that the footnotes should be positioned based on the order found in the document not based on the footnote character (i.e. `[^1]` not based on the 1), right?

If that is the case, the above reproducible example is slightly incorrect in that it assumes the linter will correct the double usage of footnote characters (i.e there are two instances of references to `[^1]` with different values). The linter can be responsible for correct ordering based on position in the file, but adding automatic ordering would be a feature request from my understanding.

**Comment by pjkaufman** [comment] 2022-07-30 22:33
Do you mind adding a little explanation on why a duplicate footnote reference would actually result in the correct order for footnotes at the end of the file?

**Comment by pjkaufman** [comment] 2022-07-31 00:14
Here are a couple ideas that I have had for how to properly create the footer order at the end of the file when footer references are missing:
- First match those that have references
  - If more than 1 matches a reference, then determine position in ending list based on the character index of the first footnote reference prior to the footnote contents that has not already been used by another footnote
- If a footnote is missing a reference
  - Use the order of the character index where the footnote is pulled from to determine where it falls in comparison with the other footnotes
  - If there are both unmatched footnote references and unmatched footnotes, match them based on the order they show up in the document (earliest instance with earliest instance)

The above methods can be quite unreliable and inaccurate if the assumptions that the orders of unmatched footnote references and unmatched footnotes is incorrect.

Do the two methods listed above for missing footnote reference matches make sense? And do you have a preference on which to use first or if I should not use one?

**Comment by pjkaufman** [comment] 2022-07-31 12:22
If we do not want to try to fix orphaned references, I believe I have a fix for this.

**Comment by olearydj** [comment] 2022-07-31 15:00
Yeah, I see this is tricky. I was imagining that the combination of re-index and consolidate options would be smart enough to deal with insertion "automagically," but did not consider that inserting a reference requires you to reconcile the duplicated numbering it creates.

I believe that the methods you described make sense. I'm not sure I can answer re: preferences because it is hard for me to imagine how they might interact.

If I'm overlooking the "right way" to use this functionality I'm happy to call it user error if you prefer. Otherwise, I'll test and feedback on any adjustments made.

Thank you.

**Comment by pjkaufman** [comment] 2022-07-31 16:49
Thanks for the feedback. If by saying you expect that re-index and consolidate being able to properly deal with the following scenario, then I have a fix that should work:

``` markdown
reference A [^1]

reference C [^2]
[^2]: footnote C (inserted between A and B)

reference B [^2]

[^1]: footnote A (first in document)
[^2]: footnote B (last in document)
```

becomes the following after moving to the end of the document:

``` markdown
reference A [^1]

reference C [^2]
reference B [^2]

[^1]: footnote A (first in document)
[^2]: footnote C (inserted between A and B)
[^2]: footnote B (last in document)
```

Then it should become the following after the re-index:
``` markdown
reference A [^1]

reference C [^2]
reference B [^3]

[^1]: footnote A (first in document)
[^2]: footnote C (inserted between A and B)
[^3]: footnote B (last in document)
```

Is this what you were looking for @olearydj ?

**Comment by pjkaufman** [comment] 2022-07-31 21:22
If you would like to check the latest release and see if it address what you were looking for with this bug report, that would be great! It should now handle the scenario I listed above, but it still cannot and will error out on missing footnote references.

**Comment by olearydj** [comment] 2022-08-13 12:15
I haven't had the opportunity to rigorously test it but this seems to be mostly fixed.

I did notice yesterday that, if I concatenate two MD docs, both with sequentially numbered refs and footnotes at the end of the document, and lint the result, the numbering doesn't change. I'm going to add this as a comment now and come back to provide additional details next week, after I finish my PhD proposal.

**Comment by pjkaufman** [comment] 2022-09-17 02:24
Hey @olearydj , I am not sure if you have noticed any of the issues that you had mentioned potentially seeing. If you did, please let us know. Otherwise, I plan to close this issue out at the end of next week if I do not hear a response back by then.

**Comment by pjkaufman** [comment] 2022-09-27 11:41
I have not heard back on this, so I am going to close it. If the issues still exist please let us know.

**Closed by pjkaufman** 2022-09-27 11:41 UTC
Labels: bug, markdown
