### ISSUE TITLE
Bug: linter breaks pasting in editable embeded sections

### ISSUE THREAD

**Issue by Friedolito** [platers/obsidian-linter#1219] opened 2024-11-13 09:40 UTC
## Describe the Bug

When having on of the paste settings turned on, pasting in to embeded sections will break. 

## How to Reproduce

Seen in:
- obsmd preview on hover edit
    - cmd + hovering over an internal link will open the preview
    - there you can edit the file directly
    - if you paste text, it will be pasted on the last active cursor place in the original document not in to the preview window as        expected
- outliner.md by boninall
    - the plug-in will give you the option to directly edit embeded internal links 
    - there as well, when you paste text, it will be pasted on the last active cursor place in the original document not in to the preview window as expected

## Expected Behavior

- pasting text in to embeded section should add it where it is intended
- for anyone having the problem right now, disabling all the setting in the paste tab, will solve the issue

## Device

- [x] Desktop
- [?] Mobile

Thank you for considering and creating linter! :)

**Comment by pjkaufman** [comment] 2024-11-13 11:23
Hey @Friedolito . The paste is always designed to happen where the cursor is currently located. So I could be a bit confused here.

But currently I am not sure how pasting into an embedded file works. Because I thought by default they were just previews. So could you elaborate a little more on this?

**Comment by Friedolito** [comment] 2024-11-13 11:32
I think with the gifs it should be more clear :) 

Behavior when a pasting setting is turned on: 
![Screenshot -2024-11-13 at 12 28 00](https://github.com/user-attachments/assets/22076d4c-bc8f-48dd-8df2-643d8ac251a4)

Behavior when all pasting settings are turned off:
(the intended behavior) 
![Screenshot -2024-11-13 at 12 29 43](https://github.com/user-attachments/assets/6715ffa0-d95f-4243-b128-e5a5fd0f8688)

**Comment by pjkaufman** [comment] 2024-11-13 11:51
I think the problem is located here: https://github.com/platers/obsidian-linter/blob/7c408f01bb9db25efc0c8f4aa3e3e1118e5cb1a8/src/main.ts#L221. I need to use the editor specified by the paste event instead of assuming that the paste event is happening on the currently active editor. I will need to double check this though.

**Comment by pjkaufman** [comment] 2024-11-13 12:43
So, using that editor does fix the issue in question from what I am seeing. However it looks like it does create yet another problem... It seems like that editor does not work as expected for linting when the contents of a file changes.

**Comment by pjkaufman** [comment] 2024-11-13 12:51
I am going to have to reach out to the Obsidian discord and see if any devs know why I am getting odd results from the hover preview when a file changes.

**Comment by Friedolito** [comment] 2024-11-13 12:58
Thank you for putting in the work!!

**Comment by pjkaufman** [comment] 2024-11-13 13:10
No problem. Essentially the issue mentioned here has a fix. The problem is if you have the setting enabled to allow for the Linter to update the timestamp of a file when the user makes a change, editing any file via the hover that does not refer to the whole file causes problems.

The Linter assumes the editor will provide it the entire file's contents. But for some reason it only tells the Linter about a subset of the file's content's. As such, it causes the Linter to insert the YAML timestamp at the start of the linked to content. This is not how it should work.

A couple of ideas to get around this:
- If the editor and cached read disagree on the content of the file when the debounced logic runs, then assume that the editor is not reliable and do not run the updates on the editor
- If the change was made for `MarkdownFileInfo` instead of `MarkdownView` just ignore it for user edits because it is not really feasible to know if it should or should not be edited

**Comment by pjkaufman** [comment] 2024-11-13 23:55
Ok. I believe I have a fix for this. It can blow away editor folds, but there is not really a way around this at this time.

**Comment by pjkaufman** [comment] 2024-11-14 00:12
Thanks for reporting the issue!

The change for this should be on master and go out with the next release. Please let us know if this continues to be an issue.

**Closed** 2024-11-14 00:11 UTC
Labels: bug, obsidian, reproducible
