### ISSUE TITLE
Bug: Linter reporting file error

### ISSUE THREAD

**Issue by swehba** [platers/obsidian-linter#1034] opened 2024-03-04 17:37 UTC
- [x] I have verified that I am on the latest version of the Linter

Yes, I am on version 1.23.1

## Describe the Bug

Linter is configured to lint on save. On saving a note, a popup appears saying the following:

> An unknown error occurred during linting.
> See console for more details.

Looking at the console, I see this:

```
plugin:obsidian-linter:43 [Obsidian Linter] Lint File Error in File 'Courses/Python/Type Annotations in Python/Section 3 - Advanced Typing/TAIP - Lesson 25 - Homework.md':
TypeError Cannot read properties of undefined (reading 'trim')
TypeError: Cannot read properties of undefined (reading 'trim')
    at eval (plugin:obsidian-linter:2852:3633)
    at Le (plugin:obsidian-linter:118:1205)
    at lo.runCustomRegexReplacement (plugin:obsidian-linter:2852:3423)
    at lo.lintText (plugin:obsidian-linter:2852:1657)
    at Oo.runLinterEditor (plugin:obsidian-linter:2861:7921)
    at originalSaveCallback.n.callback (plugin:obsidian-linter:2861:4041)
    at Jq (app://obsidian.md/app.js:1:1792124)
    at e.executeCommand (app://obsidian.md/app.js:1:1793657)
    at e.eval (plugin:obsidian-kanban:77:14406)
    at e.o (plugin:obsidian-kanban:23:77313)
    at e.eval (plugin:dbfolder:491:3722)
    at e.i [as executeCommand] (plugin:dbfolder:487:75925)
    at e.onTrigger (app://obsidian.md/app.js:1:1155885)
    at e.handleKey (app://obsidian.md/app.js:1:748623)
    at e.handleKey (app://obsidian.md/app.js:1:748736)
    at t.handleKey (app://obsidian.md/app.js:1:748945)
    at e.onKeyEvent (app://obsidian.md/app.js:1:749879)
Ld @ plugin:obsidian-linter:43
handleLintError @ plugin:obsidian-linter:2866
runLinterEditor @ plugin:obsidian-linter:2861
originalSaveCallback.n.callback @ plugin:obsidian-linter:2861
Jq @ app.js:1
e.executeCommand @ app.js:1
eval @ plugin:obsidian-kanban:77
o @ plugin:obsidian-kanban:23
eval @ plugin:dbfolder:491
i @ plugin:dbfolder:487
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
```

I have used Linter for a long time, and this is the first time I have ever seen this error.

## How to Reproduce

1. Save then current note with ⌘S.
2. Obsidian displays the error described above.

Here is my Linter data.json file:

[data.json](https://github.com/platers/obsidian-linter/files/14485065/data.json)

## Expected Behavior

I expect Linter to run as it used to without display a message and without writing error information to the debugger.

## Screenshots

See https://share.cleanshot.com/sLXNhHFh

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2024-03-04 17:52
Hey @swehba . Thanks for taking the time to open an issue. This is actually something that will be fixed in the next release (#1025 ). There is a suggested fix in the meantime where you go in and add a label for any custom replaces that do not have it and then remove them as that should fix the issue from my understanding.

**Comment by pjkaufman** [comment] 2024-03-04 19:07
No problem. I am glad that the issue is resolved for you and that you find the Linter useful.

**Comment by pjkaufman** [comment] 2024-03-05 17:50
I am going to close this since it duplicates another ticket that already had a code change made to fix this. The fix should go out in the next release.

**Closed** 2024-03-05 17:50 UTC
Labels: bug, duplicate
