### ISSUE TITLE
Bug: "Footnote after Punctuation" Breaks Footnote

### ISSUE THREAD

**Issue by LloydThinks** [platers/obsidian-linter#682] opened 2023-04-09 21:56 UTC
## Describe the Bug

The footnote-after-punctuation linting rule appears to format the footnotes incorrectly. It thinks the colon after the footnote is regular punctuation, and therefore the footnote should be moved after it. This doesn't appear to be correct.

Could be related to the recent bug fixes / feature requests #625 and #626 .

## How to Reproduce

1. Enable the rule footnote-after-punctuation.
2. Lint the example below.

``` markdown
Hello, this is a footnote[^1]

[^1]: Footnote here.
```

3. Check the resulting modified markdown, which is broken.

```markdown
Hello, this is a footnote[^1]

:[^1] Footnote here.
```

Here are the logs
```logs
Running linter
Running Format Tags in YAML
Running Move Tags to Yaml
Running Footnote after Punctuation
Running Emphasis Style
Running Ordered List Style
Running Remove Multiple Spaces
Running Strong Style
Running Unordered List Style
Running Consecutive blank lines
Running Empty Line Around Code Fences
Running Heading blank lines
Running Line Break at Document End
Running Remove Empty Lines Between List Markers and Checklists
Running Space after list markers
Running Custom Regex
Running Capitalize Headings
Running Custom Lint Commands
```

## Expected Behavior

Expected output if applicable:

Same as the input markdown. There is nothing wrong with it.

## Device

- [x ] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2023-04-11 23:22
I am not able to reproduce this as it stands. Could you provide your `data.json`, so I can try with that? I am guessing the issue is caused by a combination of rules being run together.

**Comment by LloydThinks** [comment] 2023-04-11 23:44
Data.json

```json
{
  "ruleConfigs": {
    "escape-yaml-special-characters": {
      "enabled": false,
      "try-to-escape-single-line-arrays": false
    },
    "force-yaml-escape": {
      "enabled": false,
      "force-yaml-escape-keys": ""
    },
    "format-tags-in-yaml": {
      "enabled": true
    },
    "format-yaml-array": {
      "enabled": false,
      "alias-key": true,
      "tag-key": true,
      "default-array-style": "single-line",
      "default-array-keys": true,
      "force-single-line-array-style": "",
      "force-multi-line-array-style": ""
    },
    "insert-yaml-attributes": {
      "enabled": false,
      "text-to-insert": "aliases: \ntags: "
    },
    "move-tags-to-yaml": {
      "enabled": true,
      "how-to-handle-existing-tags": "Remove whole tag",
      "tags-to-ignore": ""
    },
    "remove-yaml-keys": {
      "enabled": false,
      "yaml-keys-to-remove": ""
    },
    "yaml-key-sort": {
      "enabled": false,
      "yaml-key-priority-sort-order": "",
      "priority-keys-at-start-of-yaml": true,
      "yaml-sort-order-for-other-keys": "None"
    },
    "yaml-timestamp": {
      "enabled": false,
      "date-created": false,
      "date-created-key": "date created",
      "force-retention-of-create-value": false,
      "date-modified": false,
      "date-modified-key": "date modified",
      "format": "dddd, MMMM Do YYYY, h:mm:ss a"
    },
    "yaml-title": {
      "enabled": false,
      "title-key": "title"
    },
    "yaml-title-alias": {
      "enabled": false,
      "preserve-existing-alias-section-style": true,
      "keep-alias-that-matches-the-filename": false,
      "use-yaml-key-to-keep-track-of-old-filename-or-heading": true
    },
    "capitalize-headings": {
      "enabled": true,
      "style": "Title Case",
      "ignore-case-words": true,
      "ignore-words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript, I",
      "lowercase-words": "via, a, an, the, and, or, but, for, nor, so, yet, at, by, in, of, on, to, up, as, is, if, it, for, to, with, without, into, onto, per"
    },
    "file-name-heading": {
      "enabled": false
    },
    "header-increment": {
      "enabled": false,
      "start-at-h2": false
    },
    "headings-start-line": {
      "enabled": false
    },
    "remove-trailing-punctuation-in-heading": {
      "enabled": false,
      "punctuation-to-remove": ".,;:!。，；：！"
    },
    "footnote-after-punctuation": {
      "enabled": true
    },
    "move-footnotes-to-the-bottom": {
      "enabled": false
    },
    "re-index-footnotes": {
      "enabled": false
    },
    "auto-correct-common-misspellings": {
      "enabled": false,
      "ignore-words": ""
    },
    "convert-bullet-list-markers": {
      "enabled": false
    },
    "emphasis-style": {
      "enabled": true,
      "style": "underscore"
    },
    "no-bare-urls": {
      "enabled": false
    },
    "ordered-list-style": {
      "enabled": true,
      "number-style": "ascending",
      "list-end-style": "."
    },
    "proper-ellipsis": {
      "enabled": false
    },
    "remove-consecutive-list-markers": {
      "enabled": false
    },
    "remove-empty-list-markers": {
      "enabled": false
    },
    "remove-hyphenated-line-breaks": {
      "enabled": false
    },
    "remove-multiple-spaces": {
      "enabled": true
    },
    "strong-style": {
      "enabled": true,
      "style": "asterisk"
    },
    "two-spaces-between-lines-with-content": {
      "enabled": false
    },
    "unordered-list-style": {
      "enabled": true,
      "list-style": "-"
    },
    "compact-yaml": {
      "enabled": false,
      "inner-new-lines": false
    },
    "consecutive-blank-lines": {
      "enabled": true
    },
    "convert-spaces-to-tabs": {
      "enabled": false,
      "tabsize": "4"
    },
    "empty-line-around-blockquotes": {
      "enabled": false
    },
    "empty-line-around-code-fences": {
      "enabled": true
    },
    "empty-line-around-math-blocks": {
      "enabled": false
    },
    "empty-line-around-tables": {
      "enabled": false
    },
    "heading-blank-lines": {
      "enabled": true,
      "bottom": true,
      "empty-line-after-yaml": true
    },
    "line-break-at-document-end": {
      "enabled": true
    },
    "move-math-block-indicators-to-their-own-line": {
      "enabled": false
    },
    "paragraph-blank-lines": {
      "enabled": false
    },
    "remove-empty-lines-between-list-markers-and-checklists": {
      "enabled": true
    },
    "remove-link-spacing": {
      "enabled": false
    },
    "remove-space-around-characters": {
      "enabled": false,
      "include-fullwidth-forms": true,
      "include-cjk-symbols-and-punctuation": true,
      "include-dashes": true,
      "other-symbols": ""
    },
    "space-after-list-markers": {
      "enabled": true
    },
    "space-between-chinese-japanese-or-korean-and-english-or-numbers": {
      "enabled": false
    },
    "trailing-spaces": {
      "enabled": false,
      "twp-space-line-break": false
    },
    "add-blockquote-indentation-on-paste": {
      "enabled": false
    },
    "prevent-double-checklist-indicator-on-paste": {
      "enabled": false
    },
    "prevent-double-list-item-indicator-on-paste": {
      "enabled": false
    },
    "proper-ellipsis-on-paste": {
      "enabled": false
    },
    "remove-hyphens-on-paste": {
      "enabled": false
    },
    "remove-leading-or-trailing-whitespace-on-paste": {
      "enabled": false
    },
    "remove-leftover-footnotes-from-quote-on-paste": {
      "enabled": false
    },
    "remove-multiple-blank-lines-on-paste": {
      "enabled": false
    }
  },
  "lintOnSave": false,
  "recordLintOnSaveLogs": true,
  "displayChanged": true,
  "settingsConvertedToConfigKeyValues": true,
  "foldersToIgnore": [],
  "linterLocale": "system-default",
  "logLevel": 4,
  "lintCommands": [],
  "customRegexes": [],
  "commonStyles": {
    "aliasArrayStyle": "single-line",
    "tagArrayStyle": "single-line",
    "minimumNumberOfDollarSignsToBeAMathBlock": 2,
    "escapeCharacter": "\""
  }
}
```

**Comment by pjkaufman** [comment] 2023-04-16 17:13
I am not able to reproduce this even with the config provided. Are you seeing this issue with the exact example provided?

I ask because I want to make sure that we are experiencing different results for the same file content.

I am using Obsidian v1.1.16. Is that the version you are using?

I am testing the example against master on for this repo.

**Comment by LloydThinks** [comment] 2023-04-16 17:25
Thank you for the persistence. Here are my details and a small video showing the linting action.

Obsidian Version: Version 1.1.16 (Installer 1.1.9)
Linter Version: 1.12.0

https://user-images.githubusercontent.com/6005999/232329826-325f7942-1ef1-455e-8090-149a853febd5.mp4

**Comment by pjkaufman** [comment] 2023-04-19 23:39
@LloydThinks , could you upload the file having the issue. I see the issue happening in your video, but I still cannot reproduce with Obsidian version 1.1.16 and Installer (1.1.16). It could be something to do with the mac that you seem to be using, but it also could be something else entirely.

**Comment by pjkaufman** [comment] 2023-05-13 18:50
I have not heard anything back on the exact file having the issue. I am not sure if this has been fixed, but I plan to close this PR on the 19th if there is no update on the information present here.

**Comment by LloydThinks** [comment] 2023-05-13 22:03
Hi there. Apologies for the silence, just occupied with other responsibilities at the moment. I think it is best to close this ticket since no one else has this issue and you cannot replicate it. If you are still interested in figuring out this strange issue, then I can send the file tomorrow.

Lloyd

**Comment by pjkaufman** [comment] 2023-05-13 23:18
Sending that file would definitely help. If I cannot reproduce it from the file it could be OS specific.

**Comment by LloydThinks** [comment] 2023-05-15 12:02
Here is the file:

[Broken Footnote Example.md](https://github.com/platers/obsidian-linter/files/11477441/Broken.Footnote.Example.md)

**Comment by pjkaufman** [comment] 2023-05-17 08:32
It seems that even with the file provided I am not able to reproduce this. This could be something specific to Macs, but I am not sure on this. Since I am unable to reproduce, I am going to close this issue, but with #725 , you hopefully can prevent formatting the footnote. It should release with the next release.

**Closed by pjkaufman** 2023-05-17 08:32 UTC
Labels: bug, question
