### ISSUE TITLE
Option to respect fold state of headers / list items

### ISSUE THREAD

**Issue by gavinmn** [platers/obsidian-linter#13] opened 2021-08-31 16:06 UTC
I'm not sure if / how this would be possible but it would be great if the linter would respect the folded state of headers and list items. Currently if you lint a file with collapsed headers or list items, they are all expanded.

It also looks like linting the file bumps you out of any zoom level you are currently in with the Zoom plugin https://github.com/vslinko/obsidian-zoom. Not sure if this could be avoided as well.

**Comment by gavinmn** [comment] 2021-09-02 02:41
With some more tests I was able to confirm this happens from the linting action rather than any specific rule. Linting a file that has collapsed headings or zoomed in headings returns you to the default view even with no rules enabled.

**Comment by zcysxy** [comment] 2021-09-02 05:57
+1 for this feature! Besides lint error addressed in PR #16, it would be nice if updating yaml frontmatter could also respect the folding state.

**Comment by gavinmn** [comment] 2021-09-02 23:49
Looks like the folding data can be accessed here (via the community discord).
![unknown](https://user-images.githubusercontent.com/59900904/131929932-f000dec2-b1ab-497c-8ddb-d3a58fedd3cf.png)

**Comment by platers** [comment] 2021-09-03 03:05
It looks like `editor.replaceRange` doesn't affect folds. I think we can calculate the diff between the original and linted file, and only replace the sections that are changed. Maybe using https://github.com/kpdecker/jsdiff

**Closed** 2021-09-03 05:41 UTC

**Comment by gavinmn** [comment] 2021-09-03 15:31
Tested this out with both folding and Zoom and it seems to be working perfectly for me! 🚀

**Comment by hogru** [comment] 2024-01-02 09:46
Apparently this is an old request and has been solved before, but it seems to be back with Obsidian 1.5.3 or at least I realized it with this version and a long note with folded headings. I have no custom commands on Save and disabled a number of plugins that, I felt, are related to heading/folders (but not all). Maybe a regression / changed behavior due to the abandoned legacy editor?

**Comment by pjkaufman** [comment] 2024-01-02 12:48
> Apparently this is an old request and has been solved before, but it seems to be back with Obsidian 1.5.3 or at least I realized it with this version and a long note with folded headings. I have no custom commands on Save and disabled a number of plugins that, I felt, are related to heading/folders (but not all). Maybe a regression / changed behavior due to the abandoned legacy editor?

Replace range is not currently being used because it does not play well with Live Preview and Reading Mode. I am open to solutioms to this, but I would create a new issue for this.
