### ISSUE TITLE
YAMLException$1 reason: 'end of the stream or a document separator is expected at line x, column x:'

### ISSUE THREAD

**Issue by QuaCKeReD** [platers/obsidian-linter#176] opened 2022-03-09 16:54 UTC
After spending some time with different options I wanted to use, I tried to lint all files in my vault...

Then hit this issue on many many files;

From lint all files in vault
```
main.ts:169 Linting error in file: Notes/TMS/Projects/Open Telemetry Conference/OpenTelemetry Research.md
main.ts:170 YAMLException$1 {name: 'YAMLException', reason: 'end of the stream or a document separator is expected', mark: Mark, message: 'end of the stream or a document separator is expec…column 1:\n    Capture point is metric event\n    ^', stack: 'YAMLException: end of the stream or a document sep…idian.md/app.js:1:1433729), <anonymous>:28440:32)'}mark: Mark {name: null, buffer: '---\n\n#date/2020/11/04\n\n## [OpenTelemetry - CNCF · …cting context from the RPC headers or envelope.\n\x00', position: 515, line: 28, column: 0}message: "end of the stream or a document separator is expected at line 29, column 1:\n    Capture point is metric event\n    ^"name: "YAMLException"reason: "end of the stream or a document separator is expected"stack: "YAMLException: end of the stream or a document separator is expected at line 29, column 1:\n    Capture point is metric event\n    ^\n    at generateError (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:19187:10)\n    at throwError (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:19193:9)\n    at readDocument (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:20565:5)\n    at loadDocuments (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:20608:5)\n    at Object.load$1 [as load] (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:20634:19)\n    at loadYAML (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:25220:32)\n    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:25691:33)\n    at formatYAML (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:25180:21)\n    at Rule.Example.Text to insert [as apply] (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:25689:16)\n    at LinterPlugin.lintText (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:28440:32)"[[Prototype]]: Error
eval @ main.ts:170
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
runLinterFile @ main.ts:161
eval @ main.ts:177
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
eval @ main.ts:175
eval @ main.ts:175
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
runLinterAllFiles @ main.ts:174
eval @ main.ts:400
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
eval @ main.ts:397
```

On save
```
main.ts:184 running linter
app.js:1 Command failed to execute:  editor:save-file
app.js:1 YAMLException$1 {name: 'YAMLException', reason: 'end of the stream or a document separator is expected', mark: Mark, message: 'end of the stream or a document separator is expec…column 1:\n    Capture point is metric event\n    ^', stack: 'YAMLException: end of the stream or a document sep…idian.md/app.js:1:1433729), <anonymous>:28440:32)'}mark: Markbuffer: "---\n\n#date/2020/11/04\n\n## [OpenTelemetry - CNCF · GitHub](https://github.com/open-telemetry)\n\n## Trace;\n\nEach has a trace identifier\n\nA collection of spans\n- root + children\n- Each has its own span identifier\n- Each has a span context identifier\n\nTracer Interface object\n- Tracks current span\n- Allows access to span to add attribs, events\n- Allows finishing span once workload is complete\n\nTracer provider\n- Allows for multiple tracers to be instantiated in a single process, with different options\n\n## Metric\n\nCapture point is metric event\n- metric plus time captured\n\nThree metric instruments\n1. Counter - value summed over time\n2. Measure - value aggregated over time (sum, count, last value, histogram)\n3. Observer - current value\n\n## Context\n\nTrace's span context\n\nTelemetry context (generalised), also known as correlation context\n- Set of keys and values that can be serialised and propagated between services that are using OpenTelemetry.\n- Used to propagate values from one service to next, but also between functions with a service\n\nPropagation\n- Either referring to the act of serializing and deserializing a context object and passing it to a new service, or\n- Referring to passing it from thread to thread (or thread-like object) in a service.\n   - The specifics of this depend heavily on individual language features\n- For service-to-service communication (often referred to as an RPC, a remote process call) you’ll see references to injecting and extracting context from the RPC headers or envelope.\n\u0000"column: 0line: 25name: nullposition: 512[[Prototype]]: ObjectgetSnippet: ƒ getSnippet(indent, maxLength)length: 2name: "getSnippet"prototype: {constructor: ƒ}arguments: (...)caller: (...)[[FunctionLocation]]: mark.js:16[[Prototype]]: ƒ ()[[Scopes]]: Scopes[3]0: Closure (anonymous) {obsidian: Module, commonjsGlobal: global, __awaiter: ƒ, dedent: ƒ, commonjsRequire: ƒ, …}1: Script {Pos: ƒ}2: Global {window: global, self: global, document: document, name: '', location: Location, …}toString: ƒ toString(compact)constructor: ƒ Mark(name, buffer, position, line, column)[[Prototype]]: Objectmessage: "end of the stream or a document separator is expected at line 26, column 1:\n    Capture point is metric event\n    ^"name: "YAMLException"reason: "end of the stream or a document separator is expected"stack: "YAMLException: end of the stream or a document separator is expected at line 26, column 1:\n    Capture point is metric event\n    ^\n    at generateError (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:19187:10)\n    at throwError (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:19193:9)\n    at readDocument (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:20565:5)\n    at loadDocuments (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:20608:5)\n    at Object.load$1 [as load] (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:20634:19)\n    at loadYAML (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:25220:32)\n    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:25691:33)\n    at formatYAML (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:25180:21)\n    at Rule.Example.Text to insert [as apply] (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:25689:16)\n    at LinterPlugin.lintText (eval at <anonymous> (app://obsidian.md/app.js:1:1433729), <anonymous>:28440:32)"[[Prototype]]: Errorconstructor: ƒ YAMLException$1(reason, mark)length: 2name: "YAMLException$1"prototype: Error {constructor: ƒ, toString: ƒ}constructor: ƒ YAMLException$1(reason, mark)toString: ƒ toString(compact)[[Prototype]]: Objectconstructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()arguments: (...)caller: (...)[[FunctionLocation]]: exception.js:5[[Prototype]]: ƒ ()[[Scopes]]: Scopes[3]toString: ƒ toString(compact)[[Prototype]]: Object
e.executeCommandById @ app.js:1
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
```

File in question
[OpenTelemetry Research.md](https://github.com/platers/obsidian-linter/files/8216652/OpenTelemetry.Research.md)

**Comment by pjkaufman** [comment] 2022-05-20 02:14
@QuaCKeReD , do you mind including your data.json to help us try to reproduce the issue? With my own configuration, I am unable to hit the issue you have mentioned on the file provided. Also is there a specific OS you are using?

**Comment by QuaCKeReD** [comment] 2022-05-20 10:42
[data.json.txt](https://github.com/platers/obsidian-linter/files/8738730/data.json.txt)
 Attached 

Just tested and manually linting (via save) both my copy and the attached file still shows same error

**Comment by QuaCKeReD** [comment] 2022-05-20 11:01
Just gone through the file, removing parts until found a section that causes issue - removing any of the lines, or removing the headings, resolves the issue
I cant see what issue is - only weird thing is the indent on the 5th line, which Obsidian won't remove the extra space from beginning from

```
# Heading
Text
# Heading
- Text
 - Text 
---

```

[YAMLExceptionTestFile.md](https://github.com/platers/obsidian-linter/files/8739004/YAMLExceptionTestFile.md)

**Comment by QuaCKeReD** [comment] 2022-05-20 11:04
removing the extra indent doesnt change result

**Comment by QuaCKeReD** [comment] 2022-05-20 11:10
and, copying and pasting the above code block into new file causes same issue 😀

**Comment by pjkaufman** [comment] 2022-05-20 16:05
It seems it has something to do with the three dashes. I am looking into it, but what are they being used for here?

**Comment by QuaCKeReD** [comment] 2022-05-20 16:13
Removing them or any other line resolves the issue

So, those dashes without the first block doesnt error, or without the second block

**Comment by pjkaufman** [comment] 2022-05-20 16:14
Interesting. It seems that the insert YAML attributes rule is not liking that. I need to take a look at what might be causing the underlying issue, but it is likely a regex identification failure.

**Comment by pjkaufman** [comment] 2022-05-20 16:24
I think I see a potential issue, but I am confirming my suspicions. Hopefully it will be a simple fix, but we will see.

**Comment by pjkaufman** [comment] 2022-05-20 16:33
It seems to think that the whole thing is yaml due to the yaml regex base insertion at the start of the file. I will see about excluding 3 consecutive dashes on their own line as part of the body content of the yaml and it should fix the issue.

**Comment by pjkaufman** [comment] 2022-05-20 16:48
It looks like it was the yaml regex that was allowing for too much flexibility in the yaml front matter to the point it would allow a file's content's to be included. I have tried to simplify the regex and get it to not allow plain text entries in the yaml frontmatter as from my understanding yaml frontmatter has key value pairs or a multiline array syntax, but nothing else.

**Comment by QuaCKeReD** [comment] 2022-05-20 17:11
Brilliant!

Would changing the 3 dashes to 3 asterisks (alternate horizontal line syntax) prove the issue, and fix? (Sorry, not at laptop at moment)

**Comment by pjkaufman** [comment] 2022-05-20 17:32
I believe it should fix the issue for you. I am adding an  exclusion to the regex to not allow 3 consecutive dashes in the middle of the regex. This should prevent the issue from my local tests.

**Comment by QuaCKeReD** [comment] 2022-05-20 17:54
Sounds good.

Happy to test on my vault if you want - there were several files that triggered exception.

**Comment by pjkaufman** [comment] 2022-05-20 18:05
@QuaCKeReD , if you would like, you can use the PR associated with this issue to see if it fixes your issue with linter not working. Otherwise, you can wait until it gets merged and try from there. I am just waiting on confirmation that the code looks good as that is how things have been done most places I have coded before.

**Closed** 2022-05-20 18:14 UTC
Labels: bug
