### ISSUE TITLE
Bug: random deletion of characters/words/line breaks throughout the note

### ISSUE THREAD

**Issue by hmu-duc-anh** [platers/obsidian-linter#1111] opened 2024-06-29 11:40 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Never had this problem before, but in the past week it's been frequent since I updated to the latest version (1.24.0) via Obsidian's community plugins update function. I did some testing and found out that there was something wrong in the communication of linting YAML and linting content. I narrowed down to 2 features: "Remove trailing space" and "Add created/modified date". In a note, especially with lots of square brackets like images, the linting will remove random characters/words, sometimes even line breaks, throughout the entire note's content. I got around by turning off 1 of those 2 features, linted, then turned the other on and linted once more. I decided to download an older version (1.20.1) and those 2 features along with many others worked well together.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment] 2024-06-29 13:05
Hey @hmu-duc-anh , could you provide your `data.json` and a file to reproduce the issue with?

**Comment by hmu-duc-anh** [comment] 2024-06-29 13:30
> Hey @hmu-duc-anh , could you provide your `data.json` and a file to reproduce the issue with?

Hi. The data.json has been updated with my new settings for the older Linter version, and I have manually fixed all my files. I don't want to forcefully recreate this error since I don't want to risk damaging my data. I can give a file in similar style with placeholder contents, hopefully it can be used to reproduce this bug.

[test_linter_bug.md](https://github.com/user-attachments/files/16040241/test_linter_bug.md)

This mock file represents a type of note that I use to generate Anki cards from Obsidian. It has:
- Some YAML lines
- #note as an Obsidian tag
- a bunch of "Anki card" chunks, characterized by:
  - starting with `[anki]` and ending with `[/anki]`
  - `001 Basic` is what I name a type of Anki card
  -  `Front:` and `Back:` are self-explanatory. The Front has a MCQ question with an image attached.
  - `**Explanation or Additional info**` still belongs to `Back:`
- I added some trailing space, and a space in front of each image

In the latest version of Linter (1.24.0 as of now), whenever I linted to add created/modified dates and remove trailing space, these following phenomenons usually occured:
- [anki] becomes [aki], [nki]
- 001 Basic becomes 01 Basic
- Front: becomes Frnt:, Front (without colon)
- Loss of MCQ choice's initial letter, like "B. bla bla bla" becomes ". bla bla bla"
- Loss of random letters and spaces

**Comment by pjkaufman** [comment] 2024-06-29 14:26
This sounds a lot like an issue that was fixed in beta version 1.25.0-rc-1. It is a BRAT release that I am planning on releasing to everyone soon.

Is the YAML getting broken?

**Comment by hmu-duc-anh** [comment] 2024-06-29 14:54
> This sounds a lot like an issue that was fixed in beta version 1.25.0-rc-1. It is a BRAT release that I am planning on releasing to everyone soon.
> 
> Is the YAML getting broken?

Nope, YAML still intact

**Comment by pjkaufman** [comment] 2024-06-29 15:02
Gotcha. I will have to take a look and see if I can reproduce in the beta version of the Linter.

**Comment by pjkaufman** [comment] 2024-06-30 20:11
So far with the information provided, I am not able to reproduce this issue. If you are able to upload your `data.json` even with the new changes, I may be able to reproduce. Without it, I am not able to reproduce. This could mean that the issue is fixed in the beta release or it could just mean that the settings do not overlap enough with the ones you have for the issue to occur.

**Comment by hmu-duc-anh** [comment] 2024-07-02 05:22
> So far with the information provided, I am not able to reproduce this issue. If you are able to upload your `data.json` even with the new changes, I may be able to reproduce. Without it, I am not able to reproduce. This could mean that the issue is fixed in the beta release or it could just mean that the settings do not overlap enough with the ones you have for the issue to occur.

Hi @pjkaufman , I've reupdated and reproduced the bugs. I couldn't also reproduce the bug with previous test file, I think it has something to do with non-English characters, or Unicode characters. Here's my new test files with Vietnamese, Greek and English letters:

Test file before linting:
[test_linter_bug_before.md](https://github.com/user-attachments/files/16062013/test_linter_bug_before.md)

Test file after linting:
[test_linter_bug_after.md](https://github.com/user-attachments/files/16062010/test_linter_bug_after.md)

Linter's data file: 
[data.json](https://github.com/user-attachments/files/16062029/data.json)

My intended Linter's features are:
- Add created and modified dates
- Delete trailing spaces
- Use regex to make the "Đ/S" bold

You'll see in the linted test file that the random deletion is everywhere except for YAML. Anki card fields are messed up, characters randomly removed and bold, even the embedded images are broken due to random deletion. You can try pasting your own images and see

**Comment by sevmonster** [comment] 2024-07-06 15:12
I also encounter this. The only thing I did after installing Linter is adjust settings.

[data.json](https://github.com/user-attachments/files/16116291/data.json)

Diff:
```diff Everyday\ Backpack\ v2\ review*                          3,4c3,4
<   - context/date/published/2023-02-13
<   - purpose/review
---
> - purpose/review
> - context/date/published/2023-02-13
13d12
<
57c56
< The FlexFold dividers ae attached with Velc— Ahem, *non-trademarked, unencumbered hook & loop material* to the front and back of the inside of the bag. The hook side is on the divider, and the loop side is very soft, so you don’t have to worry about scratching anything.
---
> The FlexFold dividers are attached with Velc— Ahem, *non-trademarked, unencumbered hook & loop material* to the front and back of the inside of the bag. The hook side is on the divider, and the loop side is very soft, so you don’t have to worry about scratching anything.
89c88
< ![[EverSday Backpack v2 laptop sleeve.jpg|You can kinda get in there if you bend the arch down, but you can clearly feel the bag was not meant to be opened like this, and prolonged bending may ruin the shaping]]
---
> ![[Everyday Backpack v2 laptop sleeve.jpg|You can kinda get in there if you bend the arch down, but you can clearly feel the bag was not meant to be opened like this, and prolonged bending may ruin the shaping]]
```

In this example, the removal of the space around the em dash is offset, and the replacement of the lowercase S to uppercase in an H1 immediately below the image link (not sure why it wanted to do that) was also offset.

**Comment by pjkaufman** [comment] 2024-07-06 15:45
This sounds a lot like the issue fixed in the beta version, but I will double check that this is not different and does happen in the beta with the provided test files.

**Comment by pjkaufman** [comment] 2024-07-06 16:30
@hmu-duc-anh , this does look to be fixed in the version that is in beta. I am not 100% sure that it is fixed, but running the Linter on the latest with what is on master (slightly ahead of the beta changes) does not reproduce the issue reported here. I will see about creating a release for these changes.

**Comment by sevmonster** [comment] 2024-07-06 22:15
On 1.25.0-rc-1, I can reproduce the issue in the exact same way.

Here is the source file:
https://blog.sev.monster/src/obsidian/posts/Everyday%20Backpack%20v2%20review.md

Settings are unchanged from the last post.

**Comment by pjkaufman** [comment] 2024-07-08 01:25
@hmu-duc-anh , I just released 1.25.0. Please let me know if that does not fix the issue. I plan to close this Wednesday if I have not heard from you by then.

**Comment by hmu-duc-anh** [comment] 2024-07-09 08:56
@pjkaufman I confirm that I can't reproduce the bug with v1.25.0 in Obsidian

**Comment by pjkaufman** [comment] 2024-07-09 09:04
Nice. I will go ahead and close this then. I am glad this is resolved.

**Closed by pjkaufman** 2024-07-09 09:04 UTC
Labels: bug

**Comment by s1rens** [comment] 2024-07-14 10:48
I am getting this bug with v1.25.0. As @hmu-duc-anh advised, I get it when using 'remove trailing whitespace' feature. Turning it off removes the issue. 

[data.json](https://github.com/user-attachments/files/16216529/data.json)

**Comment by hmu-duc-anh** [comment] 2024-07-14 10:58
@s1rens did you make sure to reload Obsidian after updating to 1.25.0? And perhaps you should also provide the devs sample files before and after linting

**Comment by pjkaufman** [comment] 2024-07-14 12:46
I fixed another scenario that causes this issue as well (see #1125 ). It also created this scenario. It is fixed on master, but has not beem released yet.
