### ISSUE TITLE
FR: Quarto-like latex blocks hault linter-progression through the file

### ISSUE THREAD

**Issue by Gewerd-Strauss** [platers/obsidian-linter#950] opened 2023-11-26 00:00 UTC
## Is Your Feature Request Related to a Problem? Please Describe.

I write a lot of quarto-formatted markdown in obsidian, but I use the linter to ensure notes conform to various formatting rules.

However, the rule regarding [spaces around math blocks](https://platers.github.io/obsidian-linter/settings/spacing-rules/#empty-line-around-math-blocks) breaks apart and stops the linter from working, if quarto-conforming latex-blocks are used, the presence of the [equation cross-ref-key](https://quarto.org/docs/authoring/cross-references.html#equations) haults linter-execution once encountered. 

Lines above are being linted, but no lines below will be processed.  
Quarto itself is an open-source publishing system that combines text, code, and output in one document and has a fairly well documented feature-set. 

## Describe the Solution You'd Like

**Please include an example where applicable:**

Example note:

```qmd

# Equation Referencing

The below works in
- pdf
- html
- docx

---
---

, yielding equations (@eq-fieldcapacityequation1) and (@eq-fieldcapacityequation2) describing the 100% Field Capacity and 0% Field Capacity substrate parameters respectively, where $m_{S}$ is the substrate mass used when repotting.  
(Result: `_Equation 1_`, `_Equation 2_`, text surrounded by `_` is part of hyperlink)

, and were found to conform to the equations (Eq. [-@eq-fieldcapacityequation1]) and (Eq. [-@eq-fieldcapacityequation2]) describing the 100% Field Capacity and 0% Field Capacity substrate parameters respectively, where $m_{S}$ is the substrate mass used when repotting.  
(Result: `(Eq. _1_)`,`(Eq. _2_) `, text surrounded by `_` is part of hyperlink)

$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation1}




$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation2}




dwa

During the second experiment, pots were watered twice a week.  
On the date of repotting, `r difftime(lubridate::dmy("15.05.2023"),lubridate::dmy("12.05.2023"),units ="days")` days after sowing all pots were watered with 250 mL.  
Until the establishment of experimental groups `r difftime(lubridate::dmy("22.05.2023"),lubridate::dmy("15.05.2023"),units = "days")` days after repotting, the volume supplied was calculated as a fraction of the field capacity (FC) from the mean weight of 15 randomly chosen pots. Following the creation of groups, each experimental group's mean weight was used for calculation of the FC. Following these principles, all groups were watered to a fieldcapacity of 90% until `r difftime(lubridate::dmy("29.05.2023"),lubridate::dmy("15.05.2023"),units = "days")` days post repotting.  
At this point the initial drought stress period was initiated by depriving stress groups except for the unstressed control UU of water for `r difftime(lubridate::dmy("11.06.2023"),lubridate::dmy("30.05.2023"),units = "days")` days.  
After the initial drought stress period has passed, the experimental groups were kept at different specific field capacities for the remainder of the experiment.

In case of the second experiment, the water volume supplied is a percentage fraction of the respective calculated FC (table \@ref(tab:tbl-WateringMethodTables)).  
Calculated volumes were rounded _to the closest_ multiple of 10.

Over the course of the experiment, the Field Capacity percentage supplied to each group changed; as outlined in the below table.





---
---

dwadaw

```

Example note:

```qmd

# Equation Referencing

The below works in
- pdf
- html
- docx

---
---

, yielding equations (@eq-fieldcapacityequation1) and (@eq-fieldcapacityequation2) describing the 100% Field Capacity and 0% Field Capacity substrate parameters respectively, where $m_{S}$ is the substrate mass used when repotting.  
(Result: `_Equation 1_`, `_Equation 2_`, text surrounded by `_` is part of hyperlink)

, and were found to conform to the equations (Eq. [-@eq-fieldcapacityequation1]) and (Eq. [-@eq-fieldcapacityequation2]) describing the 100% Field Capacity and 0% Field Capacity substrate parameters respectively, where $m_{S}$ is the substrate mass used when repotting.  
(Result: `(Eq. _1_)`,`(Eq. _2_) `, text surrounded by `_` is part of hyperlink)

$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation1}

$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation2}

dwa

During the second experiment, pots were watered twice a week.  
On the date of repotting, `r difftime(lubridate::dmy("15.05.2023"),lubridate::dmy("12.05.2023"),units ="days")` days after sowing all pots were watered with 250 mL.  
Until the establishment of experimental groups `r difftime(lubridate::dmy("22.05.2023"),lubridate::dmy("15.05.2023"),units = "days")` days after repotting, the volume supplied was calculated as a fraction of the field capacity (FC) from the mean weight of 15 randomly chosen pots. Following the creation of groups, each experimental group's mean weight was used for calculation of the FC. Following these principles, all groups were watered to a fieldcapacity of 90% until `r difftime(lubridate::dmy("29.05.2023"),lubridate::dmy("15.05.2023"),units = "days")` days post repotting.  
At this point the initial drought stress period was initiated by depriving stress groups except for the unstressed control UU of water for `r difftime(lubridate::dmy("11.06.2023"),lubridate::dmy("30.05.2023"),units = "days")` days.  
After the initial drought stress period has passed, the experimental groups were kept at different specific field capacities for the remainder of the experiment.

In case of the second experiment, the water volume supplied is a percentage fraction of the respective calculated FC (table \@ref(tab:tbl-WateringMethodTables)).  
Calculated volumes were rounded _to the closest_ multiple of 10.

Over the course of the experiment, the Field Capacity percentage supplied to each group changed; as outlined in the below table.

---
---

dwadaw

```

## Describe Alternatives You've Considered

Current alternatives are basically just turning off the plugin - which I REALLY want to avoid. However, the presence of such blocks as described above completely block the plugin anyways. Unfortunately, quarto does not offer any alternative syntax I could leverage instead :/

## Additional Context

I recognise that this is a niche request, however I would kindly ask if you could implement an optional fix for this issue.

---

Thank you.  
Sincerely,  
~Gw

**Comment by pjkaufman** [comment] 2023-11-26 00:44
Hey @Gewerd-Strauss . Is it correct that the cross reference key follows the following format: `{#any-non-whitespace-char}`?

**Comment by Gewerd-Strauss** [comment] 2023-11-26 17:27
As far as I am aware, equation ID's are always of format `{#eq-<alphanumeric>}`.
The `{#eq` and `}` are always static, but the remaining characters are letter-digit combinations. No spaces, no special chars[^1].

I cannot find any definitive information regarding what constitutes a valid ID, but the upper rule has held well so far across a couple hundred equations. 


[^1]: In this case, I refer to the group ` [A-Za-z0-9]`.

**Comment by pjkaufman** [comment] 2023-11-29 19:31
Hey @Gewerd-Strauss . Could you show how things are getting broken? I am not seeing the before and after that you are referencing.

Also, note that putting math blocks back to is risky if they have the same indicator level. I say this because some parsers like the one that I am using assume that they are a single math block (this is because it is not designed for all types of math blocks). For the example provided, it looks like they get considered to be a single math block. This is likely the cause of your problem: https://astexplorer.net/#/gist/cd28491afbfc2a2b415e0ec16245f085/9e78bfec9181f44376b98639be59271e86c5e385

I am not sure what exactly the problem is since I do not see a before and after block of what is happening, but if it is caused by the two math blocks not being considered to be separate, I would suggest one of the following:
1. Use a different number of `$` for math blocks that are next to each other
2. Add some content between the math blocks to make it so they are not considered to be 1 math block

I am open to other ways to get around this, but the parser is for math blocks (not latex in particular), so it could be tricky to handle.

**Comment by Gewerd-Strauss** [comment] 2023-11-29 20:05
Welp...

I must have been drunk when I made these examples.

Consider this as input:

```qmd
Text
More Text




$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation1}


<!-- comment -->




$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$  {#eq-fieldcapacityequation2}





During the second experiment, pots were watered twice a week.  
```


If the issue would not exist, the linter would now:

- Add 2 spaces at the end of Line 1 (`Text  `)
- remove all but two linefeeds from the end of `More Text`
- remove all but two linefeeds from the end of `<!-- comment -->`
- remove all but two linefeeds from the end of `$$ {#eq-fieldcapacityequation1}`
- remove all but two linefeeds from the end of `$$  {#eq-fieldcapacityequation2}`



Thus, the expected final result _should_ be:

```qmd
Text  
More Text

$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation1}

<!-- comment -->

$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation2}

During the second experiment, pots were watered twice a week.  
```

---

However, this is the actual result:

```qmd
Text  
More Text

$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation1}


<!-- comment -->




$$

Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]

$$  {#eq-fieldcapacityequation2}





During the second experiment, pots were watered twice a week.
```

---

Issues:

- two linefeeds from `$$ {#eq-fieldcapacityequation1}` are not removed
- three linefeeds from `<!-- comment -->` are not removed
- four linefeeds from `$$  {#eq-fieldcapacityequation2}` are not removed

As you can see, the linter works properly first - it lints up to the first latex block, and then it gets complicated.

1. The linter splits the second latex-block apart:

```qmd
$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation2}
```

becomes 

```qmd
$$

Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]

$$  {#eq-fieldcapacityequation2}
```

2. The superfluous spaces _after_ this second latex block however are not linted. In fact, _nothing_ after the second latex block is linted.
3. It is worthwhile to mention that if you remove the second latex block, the linter still stops working after the first latex blocks. I also don't know why the second latex block is split apart like this, while simultaneously nothing else is processed.

---

> 2\. Add some content between the math blocks to make it so they are not considered to be 1 math block

Does an html-comment work as separator for the sake of the comment? 
It is basically the only nonprinting markdown I can think off which could be used to add text without adding it. Because it is pretty common to add several latex equations after each other.  
To my knowledge quarto does not support nested latex blocks, which means I I cannot use this as a solution in my case.

---

Again, I want to apologise for the fucked-up example. I hope you now understand what my issue is.

**Comment by pjkaufman** [comment] 2023-11-29 20:37
Interesting. I assumed that the comment would work as well. I even put a header between the math blocks, but that did not seem to fix the issue either. I will see about asking a question on the remark form. My best guess is that the remark parser assumes that a math block cannot end with anything else on the same line or else it is not considered to be a math block indicator. I need to double check that understanding with the remark docs and the previous question I posed around this. If that is the case, there is really no way I can handle Quarto references in the Linter while still using remark to recognize the math blocks.

**Comment by pjkaufman** [comment] 2023-11-29 20:46
Looks like the issue is due to the parser based on the discussion here: https://github.com/orgs/remarkjs/discussions/1069

So the Quarto cross reference is not valid according to that parser as it works like \`\`\` does. This means that they must be on their own line. I would recommend adding a linter ignore around the math blocks that do have Quarto cross references given this seems to be an issue with the parser that may not change.

Here is a way to make sure that the Linter does not update the math blocks:
``` markdown
<!-- linter-disable -->
$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$ {#eq-fieldcapacityequation1}
<!-- linter-enable -->



<!-- linter-disable -->
$$
Potweight_{100\% FC} = `r paste(signif(13231.123123,digits = 3))` \times m_{S} + `r paste(signif(13231.123123,digits = 3))` \ [g]
$$  {#eq-fieldcapacityequation2}
<!-- linter-enable -->
```

**Comment by Gewerd-Strauss** [comment] 2023-11-29 22:10
...I _completely_ forgot this was a thing I could do. That should resolve the issue fully. 

Thank you. I suppose we can close this issue.

**Comment by pjkaufman** [comment] 2023-11-29 22:34
Sounds good. I will close this FR then. I am glad this fixes your issue.

**Closed by pjkaufman** 2023-11-29 22:34 UTC
Labels: rule suggestion
