### ISSUE TITLE
Bug: Move Math Block Indicators to Their Own Line duplicates text before block math delimiter

### ISSUE THREAD

**Issue by calofmijuck** [platers/obsidian-linter#996] opened 2024-01-17 13:14 UTC
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

The rule `Move Math Block Indicators to Their Own Line` duplicates text before block math delimiter.

## How to Reproduce

1. Create a new vault, enable community plugin, install this linter.
2. Enable `Lint on save` rule for simplicity.
3. Enable `Move Math Block Indicators to Their Own Line` Rule
4. Write `a$$b$$` in the editor.
5. Save (or Lint the file)
6. (Additionally) repeatedly linting the file keeps on duplicating the text before the block math delimiter.

## Expected Behavior

Expected output if applicable:

``` markdown
a
$$
b
$$
```

## Screenshots

https://github.com/platers/obsidian-linter/assets/38686321/b75863cf-5654-452d-ba5b-98d953b11fb2

## Device

- [x] Desktop (MacOS)
- [ ] Mobile

## Additional Context

I checked the source code and found that this is actually a feature for math blocks inside blockquotes (`>`).
For blockquotes, 

```
> $$a$$
```

should be linted to

```
> $$
> a
> $$
```

which is probably why the `a` in my example keeps getting duplicated. Is this intended behavior?

**Comment by pjkaufman** [comment] 2024-01-27 01:25
Hey @calofmijuck . Thanks for reporting this issue. This is something that is not intended. It does seem to be caused by the blockquote logic. I will need to look at why it is running for non-blockquotes (probably an oversight on my part).

**Comment by pjkaufman** [comment] 2024-01-27 02:15
I believe that I have a fix for this. It is still a work in progress since it is currently break some older UTs, but I am down to one broken UT now. Hopefully I can get that fixed and ready soon.

**Comment by pjkaufman** [comment] 2024-01-27 02:38
Got it working. I just want to tackle one more scenario for blockquotes since that is a more complex scenario for knowing when to trim whitespace prior to the opening math block indicator because it was moved to a new line.

**Comment by pjkaufman** [comment] 2024-01-27 12:23
I believe I have it tackled. I will go ahead and create a PR.

**Closed** 2024-01-27 12:40 UTC
Labels: bug, math

**Comment by pjkaufman** [comment] 2024-01-27 12:41
I have merged the changes that should address this issue. This issue should be fixed on master and in the next release. Please let us know if that is not the case.

**Comment by calofmijuck** [comment] 2024-01-27 16:35
Thank you very much for looking into this bug. I truly appreciate your hard work. I hope you have an amazing weekend.
