### ISSUE TITLE
Bug: Linter setting breaks 'Share Note' plugin

### ISSUE THREAD

**Issue by paradeiser** [platers/obsidian-linter#1155] opened 2024-08-29 17:51 UTC
If the setting

_**Format Tags in YAML**_
_Remove Hashtags from tags in the YAML frontmatter, as they make the tags there invalid._

is turned on, Linter also removes the hashtag from the 'share_link' value in frontmatter (although it's not within the "tags" section).
This results in an error when re-sharing a note using the "Share Note" plugin, as described here: https://github.com/alangrainger/share-note/issues/57

A sample frontmatter section would be:
```
---
created: 2024-08-29T19:28:47+02:00
updated: 2024-08-29T19:48:06+02:00
title: Share note Test
aliases: 
tags: []
share_link: https://share.note.sx/r0w1vdtw#goaVfYU2NExAphdG8oHzVUZ2h8E22JDbJHC5BBEsZPo
share_updated: 2024-08-29T19:37:28+02:00
---
```

After linting the file it looks like:
```
---
created: 2024-08-29T19:28:47+02:00
updated: 2024-08-29T19:48:06+02:00
title: Share note Test
aliases: 
tags: []
share_link: https://share.note.sx/r0w1vdtwgoaVfYU2NExAphdG8oHzVUZ2h8E22JDbJHC5BBEsZPo
share_updated: 2024-08-29T19:37:28+02:00
---
```

**Comment by pjkaufman** [comment] 2024-08-31 21:13
Hey @paradeiser , thanks for reporting this. I am able to reproduce the issue. It looks like an issue with the underlying regex not properly handling this scenario, but I will have to look at things closer to see if I can figure out what is going on here.

**Comment by pjkaufman** [comment] 2024-08-31 21:20
Looks like the regex used there was pretty old and outdated. I have gone ahead and updated it. It should no longer have this issue with that. I should be able to push up a fix for this shortly.

**Comment by pjkaufman** [comment] 2024-08-31 21:33
I have gone ahead and merged the change that should fix this. Please let us know if this is not fixed on master or in the next release.

**Closed** 2024-08-31 21:32 UTC
Labels: bug, reproducible
