### ISSUE TITLE
Bug: YAML Timestamp changes modified date despite no changes to the file

### ISSUE THREAD

**Issue by frigvid** [platers/obsidian-linter#568] opened 2022-12-23 14:52 UTC
## Describe the Bug
Related: #221 and #225 

If the system locale time format does not match the `YAML Timestamp` time format specified in the settings, the modified date key is updated on each lint. Whether that be through manual saving with `Lint on save` enabled or using `Ctrl` + `P` → `Linter: Lint the current file`.

I'm uncertain if it actually is an issue for date formats as well, but I think we can err on the side of caution and assume it is until proven otherwise.

## How to Reproduce
1. Enable the `YAML Timestamp` in the plugin settings, only modified is necessary
2. Set the time format to not match the system locale. E.g. if the machine is using a twenty-four hour clock, use a twelve hour clock. And vice versa.
2. Create a new file
3. Save manually to add key and date
4. Save again, modified date key should be updated
5. `Ctrl` + `P` → `Linter: Lint the current file`, modified date key should be updated
6. Fix the time format in settings, such that it matches the system locale.
7. Save manually again, modified date key should not be updated
8. `Ctrl` + `P` → `Linter: Lint the current file`, modified date key should not be updated

As an example, my machine is using a twenty-four hour clock. The format I was using before was `YYYY-MM-DDThh:mm:ssZ, [week] WW [of] MMMM [on] dddd`. This results in a line like `2022-12-23T03:09:29+01:00, week 51 of December on Friday` for the modified key value, but it is updated every time linting is run.

Changing the format to `YYYY-MM-DDTHH:mm:ssZ, [week] WW [of] MMMM [on] dddd`, uppercasing the hours and telling it that it should follow a twenty-four hour format, results in a line like `2022-12-23T15:33:49+01:00, week 51 of December on Friday`. However, this does not cause an update when linting is run.

Here is the [configuration for Linter](https://pastes.io/xqdcd0pdy3). I would've pasted it to pastebin, but apparently they have a [filter now and it doesn't like](https://i.imgur.com/TZeQ03j.png) the configuration file lol.

There was [nothing of note](https://pastebin.com/SzuCcZkt) in the log at `ERROR`, `TRACE` or `DEBUG` levels of logging.

## Expected Behavior
`YAML Timestamp` should be able to handle or warn about system locale time format mismatches. `hh` and `HH` should both work on systems using either a twenty-four or twelve hour clock without updating the date modified front matter key on each lint.

## Device
Tested on a fresh installation of Linux and Obsidian.

- OS: Linux
- Distro: Arch Linux
- Obsidian: 1.1.8
- `/etc/locale.conf` has `LANG` set to `en_US.UTF-8` and `LC_TIME` to `nb_NO.UTF-8`

**Comment by pjkaufman** [comment] 2023-01-12 12:23
Thanks for reporting this. This definitely seems luike an interesting issue. Have you verified that the timestamp format is considered valid by moment? If it considers it to not be valid, it would likely cause the issue you are seeing. I will try to take a look at this as I whittle through the issues that piled up while I was out.

**Comment by frigvid** [comment] 2023-01-12 14:30
That depends on how you try to validate it. I've tested with saving the generated string as a variable, e.g. `const date = moment("2022-12-23T03:09:29+01:00")` and then running it through `isValid()` to check if it returns true.

Generating the timestamp itself does show that Moment.js is parsing it correctly, and it was designed within spec. However, validating it requires you to remove the non-date elements, e.g. `,`, `[week]`, `[of]` and `[on]`. Take the date `2022-12-23T03:09:29+01:00`, it is parsed as a valid date. Likewise, `51 December` is parsed as valid, though `51 December Friday` strangely is not. But the entire string, `2022-12-23T03:09:29+01:00, week 51 of December on Friday` is correctly parsed to be invalid.

Regardless, I doubt the issue is the timestamp format itself. If that is the case, then the issue should have persisted after changing the locale, as the actual issue hadn't been resolved and it was simply parsing it incorrectly. Yet changing the system locale to the correct locale _does_ fix the issue. Of course, it might just be confirmation bias, but I'm not familiar enough with this code base to speak much more on it. I hope this helps a little.

**Comment by pjkaufman** [comment] 2023-01-12 17:28
The locale does need to be correct for moment to be able to parse the timestamp correctly. It uses that to check if the timestamp is valid. So if you have an locale for the Linter set and that value does not coincide with that of the format of the timestamp in the front matter it will try to change it since it is not valid for the specified locale.

**Comment by frigvid** [comment] 2023-01-12 17:34
Yes, that's why the recommendation is to add a warning to end users about a mismatch between system and Linter timestamp format locales. Such that they are informed and thus aware of what causes the issue, and with it, able to either find the information they need or solve it outright.

**Comment by pjkaufman** [comment] 2023-01-12 17:39
I think I am better understanding what you are saying, but I think I am misunderstanding why it was updating the value every time.

Is the following a correct description of the problem?
When the computer and Obsidian system locale are not the same, the Linter keeps generating the date timestamps for a file no matter what?

I ask because I don't think I have access to the device locale.

**Comment by frigvid** [comment] 2023-01-12 17:42
Yes, if the system locale does not match the program locale, the modified timestamp that Linter inserts will update regardless of actual changes. Even when no changes are made and linting is activated manually, the front matter timestamp is modified, even if the file's actual modification timestamp is not.

**Comment by pjkaufman** [comment] 2023-01-13 23:20
I will try to reproduce this when I get a chance. I have used Spanish as my locale in Obsidian before and I have not seen the same issue. My device does not use a Spanish locale for the OS, so if I am understanding correctly, when I save the file, it should always be updating the date modified value. If that scenario would not cause the issue based on your understanding, please let me know.

**Comment by frigvid** [comment] 2023-01-14 11:10
Yes. However, depending on your operating system, setting a language locale does not always set or change the date and time locale for the machine (especially if you've set a custom one for one reason or another). So if it works perfectly fine for you, it might be worth checking if there's some discrepancy between the date-time locale of the system or not too.

**Comment by pjkaufman** [comment] 2023-01-24 00:24
I was not able to reproduce using the different locale. However using a different type of time format does seem to cause an update each time. I need to take a closer look at why on this.

**Comment by pjkaufman** [comment] 2023-01-24 00:32
For some reason the following line is resulting in a larger number than expected: https://github.com/platers/obsidian-linter/blob/master/src/rules/yaml-timestamp.ts#L112
``` Typescript
Math.abs(modifiedDateTime.diff(modified_date, 'seconds')) > 5
```

**Comment by pjkaufman** [comment] 2023-01-24 00:59
I will have to take a closer look at this some time later. It keeps coming back as more than 5 seconds different. It looks like there are is automatically a 12 hour difference added to the time stamps, but I am not sure why.

**Comment by frigvid** [comment] 2023-01-25 13:13
No problem, take your time. I appreciate the help. Sadly, aside from testing on my side, I won't be of much help either. Time zones and format handling is far from my strong suit.

**Comment by pjkaufman** [comment] 2023-01-25 23:50
I believe I have a fix for this. I don't like it that much as it is kind of hacky, but it does the job. Essentially what I am doing is converting the date times to the format specified in the settings and then doing the compare. In order to do that, I have to format one of the moment values to a string and then convert it back to a moment instance to get it working. But it seems to fix the problem.

**Comment by pjkaufman** [comment] 2023-01-26 00:04
The fix seems to be working, so I am going to push it up. Hopefully this resolves the problem entirely. I am not the best with some of these things as it is also outside of my normal expertise. However this one seems simple enough to fix.

**Closed** 2023-01-26 00:05 UTC
Labels: bug

**Comment by pjkaufman** [comment] 2023-01-26 00:06
This change should be in master now and will be included in the next release. Please let us know if this issue persists on master or in the next release.

**Comment by frigvid** [comment] 2023-01-26 10:15
Thank you for the help, I appreciate it. I'll test it out when given time, should the issue persist, I'll update the issue. Hopefully everything works though :)
